3liz/lizmap-web-client

- lizmap/modules/lizmap/controllers/service.classic.php
Fix https://github.com/3liz/lizmap-web-client/issues/134
> When maptip value is defined only display it

- lizmap/modules/admin/locales/es_ES/admin.UTF-8.properties
Two new sentences translated (the first one proposed was already into Spanish).
> admin.UTF-8.properties Spanish localization

- lizmap/modules/admin/controllers/config.classic.php
Fix notices/warnings in saveRepositoryRightsFromRequest and remove $save parameter
It seems that the url parameter named in $param does not exists sometimes
in the request, so null is given to array_values (and then $values is null
and there are some warning on other line of codes).
Moreover, the $save parameter is not used
> Fix notices/warnings in saveRepositoryRightsFromRequest

- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/lizmapWMTSRequest.class.php
- lizmap/modules/lizmap/controllers/wmts.cmdline.php
Fixed #443 Tile cache seeding - add option to restrict geographically
> [Feature] add bbox option to wmts seeding command line

- lizmap/www/css/media.css
- lizmap/www/themes/default/css/media.css
a partial fix for https://github.com/3liz/lizmap-web-client/issues/701
>  [bugfix] small graphical details

- lizmap/modules/view/templates/main.tpl
- lizmap/modules/view/templates/map_headermenu.tpl
- lizmap/var/themes/default/jauth/index.tpl
- lizmap/var/themes/default/master_admin/index_login.tpl
- lizmap/var/themes/default/master_admin/main.tpl
- lizmap/var/themes/default/master_admin/zone_admin_infobox.tpl
> [BUGFIX] small graphical details between LWC desktop mode and mobile mode

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/controllers/embed.classic.php
- lizmap/modules/view/locales/en_US/map.UTF-8.properties
- lizmap/modules/view/locales/fr_FR/map.UTF-8.properties
- lizmap/modules/view/templates/map_permalink.tpl
- lizmap/www/css/embed.css
- lizmap/www/css/map.css
- lizmap/www/js/attributeTable.js
- lizmap/www/js/map.js
- lizmap/www/themes/default/css/embed.css
- lizmap/www/themes/default/css/map.css
Defined a controller to provide a map to embed it with an adapted style.
> [Feature] Embed controller

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/www/js/map.js
Finalize #489 WIP: [FEATURE] Limit the amount of features per layer displayed in popup
Complete 3liz/lizmap-plugin#88 [FEATURE] Configure the amount of features per layer displayed in popup
Fixed #630 Feature Count limited to 10
Fixed #430 [question] Nombre d'éléments retournés via popup
> [FEATURE] Limit the amount of features per layer displayed in popup 

- lizmap/modules/lizmap/controllers/service.classic.php
This is a work in progres.
The idea is to limit the ammount of features showed in the popup per each layer
@mdouchin what do you think of such a functionality? do you want me to code it further (UI part, ...)  or do you think we should not have this in Lizmap? if yes just let me know and I'll do
> WIP: [FEATURE] Limit the amount of features per layer displayed in popup

- lizmap/install/qgis/montpellier.qgs
- lizmap/install/qgis/montpellier.qgs.cfg
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/js/atlas.js
Navigate through features and for each feature, optionally:
* highlight the feature
* zoom or center to the feature
* display the feature popup
* filter the layer for the feature (and its children)
To navigate you can:
* use the combobox listing of feature.
* use the previous or next button
* use the play button to automatically move to the next feature after some time
The map editor can modify these options with Lizmap plugin
> [FEATURE] New Atlas tool - Navigate through the features of a layer

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
- lizmap/modules/view/locales/fr_FR/edition.UTF-8.properties
- lizmap/modules/view/templates/map_geolocation.tpl
- lizmap/www/js/edition.js
- lizmap/www/js/map.js
Add some tools in the geolocation dock to add point to geometry
> [Feature] Draw geometry directly with geolocation dock

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/logs_detail.tpl
translation required for log detail pagination
> translation required - log detail pagination

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/view/controllers/lizAjax.classic.php
- lizmap/modules/view/controllers/media.classic.php
Some methods are not supposed to be called from a browser,
but are called only from other controllers methods. So they
must not be public.
> Fix visibility of some controllers methods

- lizmap/install/backup.sh
- lizmap/install/restore.sh
including LDAP authentication, if configured
> including LDAP authentication

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/responses/myHtmlMapResponse.class.php
- lizmap/www/js/attributeTable.js
- lizmap/www/js/popupQgisAtlas.js
This feature permits you to get a print composer for the element you selected as a link in the popup if your popup is activated for this layer.
> Atlas popup - Link to visualize the element in the popup for a layer with atlas

- lizmap/www/css/embed.css
Should fix #797 
I didn't changed the place of the button because its not only for the refresh of the things selected by adress but can be used with the locate too. I think people may think it was only for the adress search if it was in it, maybe i'm wrong.
> Add of the refresh button in the Embed controller

- lizmap/modules/dataviz/classes/datavizPlot.class.php
The pie will now work without need of rework on the table, you just have to select your X and Y field and chose an aggregate method (sum, avg, median, stddev, first, last, min, max, count) and it will automatically regroup the Y with same X according to your choice.
> Dataviz - enhancement of the pie 

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/3_Support_request.md
- .github/ISSUE_TEMPLATE/4_documentation_issue.md
Templates for github that will help reporters to provide
all informations we need to fix the issues
> [github] issue templates

- INSTALL.md
I took the install.md from master and copy/pasted it in 3.1. So it should be OK for your GIT waterfall between 3.1, 3.2 and master if I understood.
> improve install.md about packages and debug

- lizmap/modules/view/templates/main.tpl
- lizmap/www/js/view.js
This feature will help you to find the project you want easily, you just need to type a few characters corresponding to the title of your project and it will only show the ones relevant. It's useful if you have a lot of project.
> [Enhancement] Add of a search bar in the projects page

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
Very hard to switch back to PHP after many years in Python ...
Fix for #902 
Should I open this PR against 3.1, 3.2 or master? I think 3.2 is ok because it's still not release and the current implementation might be seen fragile.
> force geometry to Z and/or M when saving from lizmap

- lizmap/modules/view/templates/main.tpl
https://github.com/3liz/lizmap-web-client/pull/908
> add translation for search bar/projects page

- lizmap/www/js/attributeTable.js
Fixed #688 attribute table (related table) - photo column/field alias
Activate renderer without tested the first feature attributes
> [BUGFIX] Attribute table cell renderer

- lizmap/modules/lizmap/classes/qgisProject.class.php
QgisProjectVersion will now be correctly calculated.
Version 2.4.2 will be 020402 (20402) instead of 204020.
> [BUGFIX] QgisProjectVersion was not calculated correctly

- lizmap/www/css/dataviz/dataviz.css
> dataviz tool - align dock top with layers dock top

- lizmap/www/js/map.js
insert the apikey in the thunderforest URL
APIKEY is in the  .qgs.cfg file, 
cf https://github.com/3liz/lizmap-web-client/issues/440
and https://github.com/3liz/lizmap-plugin/issues/109
> [FEATURE] update opencyclemap definition, to be usable

- INSTALL.md
Minor update on the install readme.
I expect this commit to fall next in 3.2 and master
> minor update on the install

- lizmap/modules/lizmap/install/sql/lizgeobookmark.pgsql.sql
Related on https://github.com/3liz/lizmap-web-client/commit/1c5215c9e99904df08060a7d2b7decff2b749875#diff-5b9c4fe8b17d1975a7eb97a29eab1964 on the master branch
> [bugfix] follow up with #1c5215c lizmap install with postgresql backend

- lizmap/www/js/attributeTable.js
Fix "attribute table" part in https://github.com/3liz/lizmap-web-client/issues/491
> Sort attribute layers as given by creation order in Lizmap plugin

- lizmap/var/themes/default/jcommunity/login.tpl
add translation for "connecter" button on sign in page
> add translation for "connecter" button on sign in page

- lizmap/modules/lizmap/controllers/service.classic.php
> fix popups that use QGIS maptip backport

- lizmap/install/qgis/montpellier.qgs
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/js/edition.js
- lizmap/www/js/map.js
Fixed #1068 popup - used once, allways remains activated
In the same time, popup in minidock dimension #1065 is calculated after content added.
> [Bugfix] Popups - always remained active and minidock dimensions

- lizmap/www/js/map.js
In some case, we could have several part of the code that want to retrieve the same feature almost at the same time (it could be the case with some custom event listeners). If the first request is not finished whereas an other component wants same data, the current code launch a second request for the same thing.
This patch avoid this second request, and all callbacks for the same feature will be called after the first request.
> map.js: use a callback pool for the getFeatureData function

- lizmap/www/js/atlas.js
- lizmap/www/js/attributeTable.js
- lizmap/www/js/edition.js
- lizmap/www/js/map.js
- lizmap/www/js/switcher-layers-actions.js
- lizmap/www/js/timemanager.js
Un peu de ménage de printemps.
> Clean commented code in js

- lizmap/modules/lizmap/controllers/service.classic.php
Layer id, feature id etc may be needed in custom templates
> WMS service: inject more template variables into templates

- lizmap/install/qgis/montpellier.qgs
- lizmap/modules/lizmap/classes/lizmapProject.class.php
Fixed #1100 The print icon disappears in QGIS 3
> [Bugfix] Parsing QGS file build with QGIS 3 for printing

- lizmap/install/qgis/montpellier.qgs.cfg
typo in montpellier project abstract
layer: quartiers
> typo in montpellier project abstract

- .github/ISSUE_TEMPLATE/1_Bug_report.md
Just an idea if it helps in debugging?
> add QGIS project version in the bug report

- lizmap/www/js/attributeTable.js
With QGIS Server 3.4 DescribeFeatureType requests return 'int' and not 'integer' for integer type.
> Fix attributte table - order by field type number Fix #1156

- lizmap/www/css/map.css
This will allow to display images in the correct orientations, for example inside popups
> CSS - Images: use exif data to display correct orientation

- lizmap/www/js/map.js
When I right click on a layerswitcher item to access "Inspecter l'élement" (in french) it shows informations, it is annoying and I think we only want to able left click.
> Display informations only on left click

- lizmap/modules/lizmap/templates/user_menu.tpl
> Better display of top menu bar on mobile

- CONTRIBUTING.md
Little howto for testing Lizmap in Android browsers in Ubuntu host.
> Contributing : Android browsers in Ubuntu

- lizmap/www/js/fileUpload/jquery.fileupload.js
- lizmap/www/js/fileUpload/jquery.iframe-transport.js
Update blueimp jQuery-File-Upload
Probably fixed issue #1114
> Update jQuery File Upload v9.28.0

- lizmap/www/js/edition.js
> [BUGFIX] Unique values indicate wrong column values

- lizmap/modules/lizmap/classes/qgisForm.class.php
Fix #1197 [feature] edit widget - color
Jelix 1.6.23 provides a color widget
> Edition: Add color widget

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
Compatibility with QGIS3 #1075
> QGIS Project 3 Edition config compatibility

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
The GetCapabilities responses are not yet stored in cached.
To get faster lizmap GetCapabilities request, the result has been stored in cahce with session_id and the user login.
> [Feature] Cached GetCapabilities

- lizmap/www/js/map.js
https://stackoverflow.com/a/23797348/2000654
> Download export files via POST request. Fix #1263

- lizmap/www/css/media.css
> Smaller search input on screen < 480px. Stretched on focus

- lizmap/modules/lizmap/classes/qgisForm.class.php
> [Regression] Display values from Array field in lizmap edit form.

- lizmap/modules/admin/classes/config.listener.php
- lizmap/modules/admin/controllers/landing_page_content.classic.php
- lizmap/modules/admin/forms/landing_page_content.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/landing_page_content.tpl
- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/templates/main.tpl
- lizmap/var/config/mainconfig.ini.php
- lizmap/www/js/ckeditor5/ckeditor_ckfullandmedia.js
Fix https://github.com/3liz/lizmap-web-client/issues/1347
> Custom html projects page

- lizmap/modules/lizmap/controllers/service.classic.php
> [Bugfix] Add HTTP code in service controller responses

- lizmap/modules/view/templates/map_geobookmark.tpl
It will be easier to override texts with theme for example. I need it for Forland.
> Add div to ease override of geobookmark text

- lizmap/modules/proj4php/classes/proj4phpCommon.php
- lizmap/modules/proj4php/classes/proj4phpDatum.php
- lizmap/modules/proj4php/classes/proj4phpProj.php
- lizmap/modules/proj4php/classes/projCode/aea.php
- lizmap/modules/proj4php/classes/projCode/aeqd.php
- lizmap/modules/proj4php/classes/projCode/cass.php
- lizmap/modules/proj4php/classes/projCode/gnom.php
- lizmap/modules/proj4php/classes/projCode/gstmerc.php
- lizmap/modules/proj4php/classes/projCode/krovak.php
- lizmap/modules/proj4php/classes/projCode/laea.php
- lizmap/modules/proj4php/classes/projCode/merc.php
- lizmap/modules/proj4php/classes/projCode/nzmg.php
- lizmap/modules/proj4php/classes/projCode/omerc.php
- lizmap/modules/proj4php/classes/projCode/ortho.php
- lizmap/modules/proj4php/classes/projCode/stere.php
Last proj4php version should be installed with composer instead. All those mistakes were visible thanks to PHP intelephense in VS Code.
> Add missing dollars for some variables

- .gitignore
- lizmap/modules/admin/controllers/upload_image.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/www/css/main.css
- lizmap/www/js/ckeditor5/ckeditor_ckfullandmedia.js
> Add image upload in landing page content

- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
- lizmap/modules/view/templates/map_edition.tpl
- lizmap/www/css/map.css
- lizmap/www/js/edition.js
> Display current/total segment length and angle in edition mode

- lizmap/www/js/atlas.js
- lizmap/www/js/edition.js
- lizmap/www/js/filter.js
- lizmap/www/js/map.js
it unhilight the modified feature after the save. The selection may not correspond anymore to the modified feature, so we should unselect the feature.
Refs #1479
> Fix edit selection

- lizmap/www/js/filter.js
> Set as maximal date the max date of the features

- CONTRIBUTING.md
- INSTALL.md
@laurentj @nboisteault Can you check?
I noticed we have install commands in :
* INSTALL.md
* CONTRIBUTING.md
* assets/README.md
It would be nice to concentrate these, no?
> review INSTALL.md about zip package

- assets/src/components/GeolocationSurvey.js
- assets/src/components/Snapping.js
- assets/src/images/svg/refresh.svg
- assets/src/index.js
- assets/src/modules/Edition.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Map.js
- assets/src/modules/Snapping.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
- lizmap/modules/view/templates/map_edition.tpl
- lizmap/www/assets/css/map.css
- lizmap/www/assets/js/edition.js
- lizmap/www/assets/js/map.js
**Funded by**: French province "Département des Pyrénées-Atlantiques"
http://www.le64.fr/accueil.html
> Snapping while editing

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
Depending of the version of Qgis, we have 0/1 or 'true'/'false' as values, for boolean properties. We didn't support fully 'true'/'false' values.
> Fix support of boolean values in qgis form properties with Qgis 3

- lizmap/www/assets/js/map.js
Use promise.all to fetch config and capabilities queries in parallel when LWC init (faster)
Before :
After :
> Fetch init queries in parallel

- lizmap/www/css/map.css
move close button in right dock and align marker and headers between docks
> move close button in right dock

- lizmap/responses/myHtmlMapResponse.class.php
- lizmap/www/OpenLayers-2.13/lib/OpenLayers/Events.js
Message in console was : [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
Fix #1619
> Fix bug in Chrome when scrolling in map

- docker/README.md
- docker/lizmap-entrypoint.sh
* Add a couple of more env variable in lizmap-entrypoint
* Update README
> Add env variable for customising php

- lizmap/modules/lizmap/classes/qgisForm.class.php
Fixed #1647
Check field has a jFormsControl defined in form.
> Fix: Wrong UPDATE query sent to PostgreSQL, data loss

- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
Move WMS request logic from controllers to dedicated class `lizmapWmsRequest`.
Needed for features layers access control.
> Move wms request part 1

- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
Move WFS request logic from controllers to dedicated class `lizmapWfsRequest`.
Needed for features layers access control.
> Move DescribeFeatureType to lizmapWFSRequest

- assets/src/modules/Lizmap.js
- assets/src/modules/SelectionTool.js
- lizmap/www/assets/js/attributeTable.js
- lizmap/www/assets/js/map.js
- lizmap/www/assets/js/switcher-layers-actions.js
Since 4699401119070910b881519f9aedc7d9c8e9eedc it is not possible to parse WFSCapabilities with jQuery. Parse with DOMParser and refactor code using it
* Ticket : should fix #1681 
*
> Parse WFSCapabilities w/o jQuery.

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
Fix the exception for request not supported.
> [Bugfix] Request not supported: code and message

- assets/src/components/Geolocation.js
- assets/src/modules/Geolocation.js
- lizmap/www/assets/css/map.css
Map can be centered at an interval defined by user and not at every geolocation position changes
> [Geolocation] Let user set bind interval

- assets/src/components/Digitizing.js
- assets/src/components/SelectionTool.js
- assets/src/index.js
- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- assets/src/modules/SelectionTool.js
- extra-modules/lizmapdemo/qgis-projects/demoqgis/montpellier.qgs
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/css/map.css
- lizmap/www/assets/js/dataviz/dataviz.js
- lizmap/www/assets/js/filter.js
Funded by [CD84](https://www.vaucluse.fr/-1.html).
> Make digitizing a web component

- lizmap/www/OpenLayers-2.13/lib/OpenLayers/Control/lizmapMousePosition.js
- lizmap/www/js/map.js
@rldhont this PR will have to be added to master by building OL2.
> Display mouse position in QGIS project's projection

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
To simplify the lizmap service controller and port a maximum of logic in classes, the lizmap OGC Request builder can use the request as XML as defined by OGC.
> Use Lizmap OGC Request builder in lizmap service controller

- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
The acces to parameters in `lizmapWFSRequest` is not based on param function.
> Fix lizmapWFSRequest parameters access

- .travis.yml
Quick try to setup Travis
I would prefer GitHub actions, but it was hanging and I didn't want to spend time setting this up
As @mdouchin is writting some PHP tests next to me ;-)
CC @laurentj FYI
> Tests - add travis config

- lizmap/modules/filter/classes/filterDatasource.class.php
Fix wrong extent & feature count when QGIS vector layer has a provider filter (SQL syntax)
> Filter by form - Use QGIS layer subquery if not empty

- Makefile
- lizmap/modules/filter/classes/filterDatasource.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- lizmap/modules/lizmap/module.xml
- tests/units/edition/qgisVectorLayerDatasourceTest.php
* Improved the way LWC parses QGIS vector layer datasource (for database based layers).
* Add unit tests to cover some cases
> Vector layer datasource - Add dedicated datasource parser covered by unit tests

- Makefile
run with 
```bash
make tests
```
> Tests - Add php unit test in Makefile

- lizmap/www/OpenLayers-2.13/lib/OpenLayers/Control/lizmapMousePosition.js
If this PR is ok I'll put it in master too.
> Use QGIS project CRS for mouse position only when output format is 'm'

- lizmap/modules/lizmap/classes/qgisAttributeEditorElement.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
Fixed #1647
Check field has a jFormsControl defined in form.
> Fix 3.3: Wrong UPDATE query sent to PostgreSQL, data loss

- lizmap/www/js/fileUpload/jquery.fileupload.js
- lizmap/www/js/fileUpload/jquery.iframe-transport.js
Fix a regression in lizmap file upload
https://github.com/blueimp/jQuery-File-Upload
> Upgrade jQuery File Upload to version 10.31.0

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/module.xml
- tests/units/classes/lizmapServicesTest.php
- tests/units/phpunit.xml
Adding tests for the lizmapServices class
> adding lizmapServices tests

- CHANGELOG-3.2.md
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
> Don't sort values with ValueMap widget to keep order defined in QGIS

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
> modifying the way lizmapProject are stored and the way to get them

- lizmap/modules/admin/controllers/maps.classic.php
- lizmap/modules/admin/templates/maps.tpl
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/controllers/repository.cmdline.php
- tests/units/classes/lizmapRepositoryTest.php
- tests/units/classes/lizmapServicesTest.php
Creating tests for lizmapRepository class + improvement of some things in the class.
The last tests (testGetProject and testGetProjects) are not working because of some Jelix dependencies inside lizmapProject.
The tests will be operational after the refactoring of lizmapProject.
> Lizmap repository tests + refactoring

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapLog.listener.php
- lizmap/modules/lizmap/classes/lizmapLogConfig.class.php
- lizmap/modules/lizmap/classes/lizmapLogItem.class.php
- lizmap/modules/lizmap/module.xml
- tests/units/classes/lizmapLogConfigTest.php
Adding tests for lizmapLogConfig class + remodeling some things in the class.
Moved the the getLogItem and getLogItemList methods from the lizmap class to lizmapLogConfig
> Lizmap log config

- lizmap/modules/lizmap/classes/lizmapProject.class.php
Bad return statement in lizmapProject::getLoginFilteredConfig()
> fixing bug in lizmapProject

- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/module.xml
More comments. Some methods have been renamed, in order to be less dependent to Jelix.
> Move and rework the new AppContextInterface interface

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/lizmapProject.class.php
New feature, restrict filter by user on edition only, based on lizmap plugin config https://github.com/3liz/lizmap-plugin/pull/265
Funded by Conseil Départmental du Calvados
> [Feature] Filter by user on edition only

- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
Adding setCache, clearCache, logMessage and logException in AppContextInterface and JelixContext.
Updating these methods in the Lizmap\Project namespace.
> AppContextInterface update

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- lizmap/modules/lizmap/classes/qgisAttributeEditorElement.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisForm.listener.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/classes/qgisServer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/events.xml
- lizmap/modules/lizmap/module.xml
- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
- lizmap/modules/view/templates/edition_form.tpl
- lizmap/modules/view/templates/edition_form_container.tpl
- lizmap/plugins/formwidget/htmlbootstrap/htmlbootstrap.formwidget.php
- lizmap/www/assets/js/edition.js
- tests/units/classes/lizmapWktTest.php
- tests/units/classes/qgisExpressionUtilsTest.php
- tests/units/edition/qgisAttributeFormTest.php
* Use QGIS Expression in Lizmap editor
* Linked to lizmap plugin [implementing lizmap server side](https://github.com/3liz/lizmap-plugin/pull/196)
* Funded by Conseil Départemental des Pyrénées-Atlantiques
> Use QGIS expression in Lizmap edition

- CHANGELOG-3.4.md
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/css/map.css
- lizmap/www/assets/js/popupQgisAtlas.js
Sponsored development by : [Conseil départemental du Vaucluse](https://www.vaucluse.fr/)
> Add UI to let user define custom labels before printing atlas feature from popups

- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Project/Project.php
Adding getUrl and getFullUrl methods that were missing and needed by Project.
> adding missing methods in appContext

- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/Repository.php
Moving lizmapRepository to namespace Project.
> Lizmap\Project\Repository

- lizmap/www/assets/css/media.css
Improve user interface for smartphones, touchscreens.
> Improve mobile ui

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapLog.listener.php
- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/classes/qgisLayerDbFieldsInfo.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
Coding style modification on all lizmap Classes
> coding style

- .github/workflows/lint.yml
Issue : #1824 
This PR will add a Github Action on each push and PR that will fix the coding style of all the php files of lizmap/modules/* using the .php_cs.dist config file.
> adding php-cs-fixer ghAction

- .github/workflows/lint.yml
> fixing the action

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- tests/units/classes/qgisExpressionUtilsTest.php
Fix regular expression to get current_value() and @current_geometry in QGIS expression and add tests
>  Fix regular expression to get current_value() and @current_geometry in QGIS expression

- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
Change the locale for upload choice update from `Update` to `Add/Update`
Funded by [Conseil Departemental du Calvados](https://calvados.fr)
> [Edition] Upload choice update locale: Add/Update

- lizmap/www/js/map.js
Ticket : https://github.com/3liz/lizmap-web-client/issues/1508
> Add zoomlevels to baselayers (Update map.js)

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
> fixing custom dates bug

- lizmap/modules/lizmap/classes/qgisForm.class.php
> fixing double-conversion bug

- tests/README.md
- tests/docker-compose.yml
- tests/lizmap-ctl
- tests/run-docker
At each branch, containers have now different names, and we can set a custom name. Port can also be changed.
Refs #1550
> [tests] fix possibility to run test containers of several branch

- lizmap/modules/lizmap/classes/lizmapLogConfig.class.php
- lizmap/modules/lizmap/classes/lizmapLogItem.class.php
- lizmap/modules/lizmap/lib/Logger/Config.php
- lizmap/modules/lizmap/lib/Logger/Item.php
> Fix some issues into the logger

- .gitignore
- lizmap/modules/lizmap/classes/qgisForm.listener.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/module.xml
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/TestContext.php
- tests/units/classes/Project/qgisProjectForTests.php
Refactorisation of QgisForm and QgisFormControl to make it more testable.
> Form/FormControl Refactor

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/controllers/media.classic.php
> Load CSS common to repositories in same directory

- lizmap/www/js/filter.js
This PR should handle filter UI when there is no data
* Ticket : #1468
*
> Don't display filter when no data

- lizmap/www/assets/js/filter.js
- lizmap/www/assets/js/map.js
- lizmap/www/assets/js/timemanager.js
> Filter button hidden when no filter in the config

- lizmap/www/js/edition.js
If the form is reopned because of a failed server side, the geometry was destroyed.
Funded by Conseil Département des Pyrénées Atlantiques
> [Bugfix] Edition: On insert failed keep the geometry

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
> fixing repo creation bug

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
Last part of the new feature, restrict filter by user on edition only https://github.com/3liz/lizmap-web-client/pull/1775, based on lizmap plugin config 3liz/lizmap-plugin#265
Using the filter by login in edition.
Funded by Conseil Départmental du Calvados
> [Feature] Filter by user on edition only - use in edition

- .php_cs.dist
- lib/jelix-admin-modules/jauthdb_admin/controllers/default.classic.php
- lib/jelix-admin-modules/jauthdb_admin/templates/crud_list.tpl
- lib/jelix-admin-modules/jauthdb_admin/urls.xml
- lib/jelix-www/js/authdb_admin.js
- lizmap/var/themes/default/jauthdb_admin/crud_list.tpl
- lizmap/www/assets/jelix/js/authdb_admin.js
*  Ticket : #1717 
*  There is now an autocompletion on the input form to view user infos of the user management page.
> adding autocompletion for jAuthdb

- lizmap/install/qgis/montpellier.qgs
- lizmap/www/js/edition.js
* Do not activate combobox or autocomplete on disabled select
* Fix widget relation value for tram_stop_id in tram_stop_works
> Edition, manage children: Do not activate combobox or autocomplete on disabled select

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/locales/fr_FR/admin.UTF-8.properties
> Setting non-editable field ReadOnly in Services config

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/www/assets/js/attributeTable.js
- lizmap/www/assets/js/edition.js
This is the last feature to use **Filter by user on edition only** https://github.com/3liz/lizmap-plugin/pull/265 after https://github.com/3liz/lizmap-web-client/pull/1775 and https://github.com/3liz/lizmap-web-client/pull/1869
The idea is to get the editable features to provide edition buttons to the right features.
Funded by Conseil Départmental du Calvados https://www.calvados.fr
> [Feature] Get editable features based on login filter

- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/www/js/edition.js
ref https://github.com/3liz/lizmap-plugin/pull/302
Fix #1665
> Use new config param 'allow_without_geom'

- .gitignore
- tests/qgis-projects/tests/README.md
- tests/qgis-projects/tests/filter_layer_by_user.md
- tests/qgis-projects/tests/filter_layer_by_user.qgs
- tests/qgis-projects/tests/filter_layer_by_user.qgs.cfg
- tests/qgis-projects/tests/filter_layer_by_user.sql
- tests/qgis-projects/tests/tests_projects_schema.sql
@laurentj @lhirlimann @Gustry @mdouchin @rldhont  : this is how a manual test might be added.
We have : 
- a *.md file with checkboxes to validate each tests
- a QGIS project + Lizmap *.cfg
- a dump (structure + data) of the schema containing tests data made from pgadmin4
For the dump, I'm not totally sure if we should have one SQL file for each QGIS + Lizmap project or a single one as I made.
- Several files can make easier to follow each test added but we have to make a dump of every tables/views needed
- One file is easier to make as we just make the dump from the schema. But it will harder to follow each change.
When everything is ok, I'll change docker configuration to automate what can be automated (drop/load sql dump(s) for example).
Then we could configure CI.
> Add 'filter layer by user' manual tests

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
> adding ISO Date Format handling + seconds in datetimepicker

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
To finalize  #1921 add override login by filter in request headers
> [Bugfix] With lizmap plugin server side, override login by filter is not respected in Headers

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
> [refactor] Moving Proxy/Request classes

- README.md
* Add some main features of lizmap in Readme.md.
If you have other main features in mind, you can give them
> Adding main features list in Readme

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
#1943 but based on release_3_4 + lint fix
> defining undefined variables in lizmapWMSRequest

- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
On my server the datasource variable doesn't contains "sql=" 
To be able to use leaflet I was forced to change the regex.
> fix table regex

- assets/src/components/SelectionTool.js
- assets/src/modules/SelectionTool.js
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/templates/view.tpl
- lizmap/www/assets/js/attributeTable.js
This PR is a cherry pick of 4 fixes made in master but to be put in release_3_4.
> Cherry picking 4 nboisteault's fixes made in master but to be put in release_3_4

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
> fixing parameters issue in qgisExpressionUtils

- tests/qgis-projects/tests/form_edition_all_field_type.md
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/form_edition_all_field_type.qgs.cfg
- tests/qgis-projects/tests/form_edition_all_field_type.sql
Add some tests to form edition.
> Form edition all field type

- lizmap/www/assets/js/timemanager.js
> [BUGFIX] Time manager - correct max slider value

- lizmap/modules/view/templates/map_timemanager.tpl
- lizmap/www/assets/js/timemanager.js
- lizmap/www/themes/default/css/map.css
* Make sure layers are correctly (un)filtered on slider reset & dock toggle
* Display also the end date(time) when necessary
> Timemanager improvements

- tests/qgis-projects/tests/form_type_relational_value.md
- tests/qgis-projects/tests/form_type_relational_value.qgs
- tests/qgis-projects/tests/form_type_relational_value.qgs.cfg
- tests/qgis-projects/tests/form_type_relational_value.sql
*Adding test project after fixbug concerning the relational value
> Adding test project to test relational value 

- lizmap/modules/lizmap/classes/lizmapFtsSearch.listener.php
> Remove warning about lizmap_search

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
> Fix foreach warning in getLoginFilters()

- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
We could need to add custom headers with WMS requests (for metrics, monitoring or else at the qgis server side)
> Custom Wms headers

- .gitignore
- tests/docker-compose.yml
- tests/docker-conf/phpfpm/Dockerfile
- tests/run-docker
Fix docker tests:
* Set user uid/gid as build arguments for phpfpm Dockerfile
* Create `.env` file in `run-docker` instead of exporting variables
* Declare postgres version as compose parameter
* Fix postgres data volume 
* Set default postgres to postgres 11, postgis 2.5
> Fix docker tests

- CONTRIBUTING.md
PR to try mainly the backport bot
> Update contributing.md about bugfix commits

- .gitignore
- .vscode/settings.json
- assets/src/modules/Digitizing.js
- tests/qgis-projects/tests/test_import_kml.cfg
- tests/qgis-projects/tests/test_import_kml.md
- tests/qgis-projects/tests/test_import_kml.qgs
- tests/qgis-projects/tests/test_import_kml/kml_with_xml_header.kml
- tests/qgis-projects/tests/test_import_kml/kml_without_xml_header.kml
If the KML file contain the xml header, it was not parsed.
Fixes #2015
> [Bugfix] Draw: import KML does not draw anythings if xml headers

- lizmap/modules/lizmap/classes/lizmapFtsSearch.listener.php
This solves an issue when Lizmap Web Client could not find the `lizmap_search` table: in some cases, the following PostgreSQL queries run by Lizmap, for example when authenticating the user, woul fail with a `ERROR: current transaction is aborted` message.
* Ticket : #2008
> FTS PostgreSQL Search - Use a transaction to avoid PostgreSQL connection issue

- .github/workflows/php-stan.yml
- lizmap/modules/action/classes/actionDatasource.class.php
- lizmap/modules/filter/classes/filterDatasource.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- lizmap/modules/lizmap/controllers/geobookmark.classic.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- phpstan.neon
* Getting PhpStan from @alagroy-42  [commit](https://github.com/3liz/lizmap-web-client/pull/2029/commits/e71a15e9f00758e304ad72eb1fd7a40539432570)
* Fixing errors flagged by PhpStan
> Fixing errors flagged by PhpStan [For Release 3_4]

- tests/qgis-projects/tests/form_type_relational_value.qgs
- tests/qgis-projects/tests/form_type_relational_value.qgs.cfg
- tests/qgis-projects/tests/form_type_relational_value.sql
> [Tests] Enhance form_type_relational_value

- tests/qgis-projects/tests/dnd_form.md
- tests/qgis-projects/tests/dnd_form.qgs
- tests/qgis-projects/tests/dnd_form.qgs.cfg
- tests/qgis-projects/tests/dnd_form.sql
> [Tests] Enhance Drag'N Drop Edition form test to avoid regression

- lizmap/modules/admin/classes/config.listener.php
> Apply php-cs-fixer version 2.18

- tests/qgis-projects/tests/project_acl.md
- tests/qgis-projects/tests/project_acl.qgs
- tests/qgis-projects/tests/project_acl.qgs.cfg
> [tests] Check project ACL

- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
> [Bugfix] Assert $layer exists

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
> Manually backport #2092

- .github/workflows/e2e_tests_cypress.yml
> [CI] Cypress CI cache docker build

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- tests/js/cypress/integration/form_edition_spec.js
> Fix notice in logs

- lizmap/www/assets/js/dataviz/dataviz.js
* Ticket : fix https://github.com/3liz/lizmap-web-client/issues/2068
> fix loading custom layout of dataviz plot with id 0

- CHANGELOG-3.3.md
- lizmap/modules/lizmap/lib/Logger/MigratorFromSqlite.php
- lizmap/modules/lizmap/lib/Users/MigratorFromSqlite.php
> Fix the sqlite to pgsql migrator

- lizmap/www/assets/css/map.css
> Fix popup compact table margin-left

- tests/qgis-projects/tests/replace_database_connection_qgs_project.sh
This PR adds a script to change the database connection in all qgs tests projects.
> Adding script to replace connection in qgs tests projects

- CHANGELOG-3.4.md
- lizmap/www/assets/js/map.js
- tests/layer_legends.sql
- tests/qgis-projects/tests/layer_legends.md
- tests/qgis-projects/tests/layer_legends.qgs
- tests/qgis-projects/tests/layer_legends.qgs.cfg
> Hide label in legend for layers w/ single symbol rendering

- assets/src/modules/Digitizing.js
- tests/qgis-projects/tests/test_import_kml.md
- tests/qgis-projects/tests/test_import_kml/kml_multilinestring.kml
- tests/qgis-projects/tests/test_import_kml/kml_multipoint.kml
- tests/qgis-projects/tests/test_import_kml/kml_multipolygon.kml
- tests/qgis-projects/tests/test_import_kml/kml_polygon.kml
> Make MultiGeometry KML importable/exportable and focus on features extent after load

- tests/qgis-projects/tests/selection.md
- tests/qgis-projects/tests/selection.qgs
- tests/qgis-projects/tests/selection.qgs.cfg
- tests/qgis-projects/tests/selection.sql
* Linked to cmc and tdpa issues
> [tests] first selection test w/ filter by group

- tests/qgis-projects/tests/test_tags.md
- tests/qgis-projects/tests/test_tags_nature_flower.qgs
- tests/qgis-projects/tests/test_tags_nature_flower.qgs.cfg
- tests/qgis-projects/tests/test_tags_nature_tree.qgs
- tests/qgis-projects/tests/test_tags_nature_tree.qgs.cfg
> Adding new test to the feature of filtering by tags

- .github/workflows/e2e_tests_cypress.yml
> [CI] Install Lizmap plugin before docker start

- .github/workflows/e2e_tests_cypress.yml
> [e2e] Display Lizmap errors.log and fail if not empty

- CHANGELOG-3.4.md
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/js/edition.js
- tests/js/cypress/integration/form_edition_spec.js
- tests/qgis-projects/tests/end2end_form_edition.qgs
- tests/qgis-projects/tests/end2end_form_edition.qgs.cfg
- tests/qgis-projects/tests/end2end_form_edition.sql
> Always display form in edition mode

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
@rldhont @mdouchin @laurentj  just a simple review without test should be enough. If you run form_edition_spec.js with cypress you'll get this notice if needed.
> Fix 'Undefined index' notice

- lizmap/www/assets/js/map.js
* Fix js undefined layer in GetPrint methods
* Fix js to print layer starts with ign
* Fix js to only print QGIS layers or groups
> Some fixes in the js to getprint

- lizmap/www/assets/js/edition.js
- tests/js/cypress/integration/form_edition_spec.js
- tests/qgis-projects/tests/end2end_form_edition.qgs.cfg
- tests/qgis-projects/tests/end2end_form_edition.sql
> Fix gh 2190

- lizmap/www/assets/js/map.js
> [Backport release_3_4] Some fixes in the js to getprint

- lizmap/www/js/map.js
> [Backport release_3_3] Some fixes in the js to getprint

- lizmap/modules/admin/classes/listProjectDatasource.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/controllers/project.cmdline.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/view/zones/ajax_view.zone.php
- lizmap/modules/view/zones/main_view.zone.php
Avoid high memory usage when there is a lot of projects
Manual backport 05c2eb9d5bace5c442e12704a37e3ad64ec6c11f in release_3_4
> [BUGFIX] Get only projects metadata for the landing page

- CHANGELOG-3.3.md
Update Changelog for 3.3.15 Release
> Changelog 3.3.15

- CHANGELOG-3.3.md
- lizmap/www/assets/js/map.js
- tests/qgis-projects/tests/popup.md
- tests/qgis-projects/tests/popup.qgs
- tests/qgis-projects/tests/popup.qgs.cfg
- tests/qgis-projects/tests/popup.sql
> Fix: tabs in anchored popup were not toggling

- CHANGELOG-3.3.md
- lizmap/www/assets/js/filter.js
- tests/qgis-projects/tests/form_filter.md
- tests/qgis-projects/tests/form_filter.qgs
- tests/qgis-projects/tests/form_filter.qgs.cfg
- tests/qgis-projects/tests/form_filter.sql
> Fix filter support 1116

- CHANGELOG-3.3.md
- lizmap/www/assets/js/map.js
> Fix: some IGN base layers w/ free keys not displayed

- lizmap/install/backup.sh
- lizmap/install/restore.sh
* Ticket : #
Add backup and restore support for PHP modules installed with composer.
> Backup and restore composer modules installed with lizmap

- INSTALL.md
> Fix heading level

- docker/README.md
> Small language cleanups.

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
This change allow to edit postgres geography column on lizmap.
> add postgresql geography type to geometryDatatypeMap

- CHANGELOG-3.5.md
- lizmap/modules/view/classes/lizmapMapDockItem.class.php
- lizmap/modules/view/controllers/lizMap.classic.php
> Allow use of JS modules (ES6) with docks

- CHANGELOG-3.4.md
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/css/main.css
- lizmap/www/assets/css/map.css
- lizmap/www/assets/js/map.js
> Display spinner, disable button waiting for print

- lizmap/modules/lizmap/classes/qgisProject.class.php
* Ticket : #2327 
* Adding check to test if wmsextent is not null
> Check if wmsextent is not null

- lizmap/modules/lizmap/classes/qgisProject.class.php
Manually backport #2338
Authored by: @drillinP
> [Backport release_3_3] Check if wmsextent is not null

- .github/ISSUE_TEMPLATE/bug-form.yml
- .github/ISSUE_TEMPLATE/config.yml
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
> Bug form for Github

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- tests/js/cypress/integration/form_edition_all_field_type_spec.js
- tests/qgis-projects/tests/form_edition_all_field_type.md
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/form_edition_all_field_type.qgs.cfg
- tests/qgis-projects/tests/form_edition_all_field_type.sql
> Fix form multiple selection

- tests/units/classes/lizmapWktTest.php
Use dedicated assertion instead of only assertTrue or assertFalse.
> [Tests] Enhance WKT parser tests

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/lib/App/XmlTools.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- tests/units/classes/App/XmlToolsTest.php
- tests/units/classes/Project/Ressources/WMSInfotest_invalid.qgs
Firstly fix `Object of class LibXMLError could not be converted to string` in OGCRequest.
Secondly add error log messages about QGIS Project XML loading
Then add error log messages about WMS GetCapabilities loading in WMTS classes.
* Funded by CRIGE-PACA
> Fix some log messages about XML loading

- lizmap/modules/lizmap/lib/Project/Project.php
* metadata panel has wrong WMS/WMTS url and wrong label
* in checkAclByUser(): options were not readed from the right object
* Ticket : #2391
> Fix regressions in the Project class

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/lib/App/XmlTools.php
- tests/units/classes/App/XmlToolsTest.php
- tests/units/classes/Project/Ressources/WMSInfotest.qgs
- tests/units/classes/Project/Ressources/WMSInfotest_invalid.qgs
- tests/units/composer.json
> [Backport release_3_4] Fix some log messages about XML loading

- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/www/assets/js/edition.js
- tests/js/cypress/integration/form_advanced_spec.js
- tests/js/cypress/integration/form_edition_all_field_type_spec.js
- tests/qgis-projects/tests/form_advanced.qgs
- tests/qgis-projects/tests/form_advanced.qgs.cfg
- tests/qgis-projects/tests/form_advanced.sql
- Fix: boolean checked value for checkbox which was sent was incorrect
> Fix and add tests for advanced forms

- CONTRIBUTING.md
> Add where people can find help if they want to contribute

- lizmap/modules/lizmap/controllers/wmts.cmdline.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
Ths Lizmap WMTS command line only contains methods to create cache and nothing to clear it.
The commit add a new tool to clean cache.
> Command wmts:cleaning - to clear cache with command line

- CHANGELOG-3.4.md
- lizmap/modules/view/templates/map_dock.tpl
- lizmap/modules/view/templates/map_rightdock.tpl
- lizmap/www/assets/css/map.css
- lizmap/www/assets/js/edition.js
> Improve dock in edition mode

- lizmap/modules/lizmap/classes/lizmapProject.class.php
> Avoid Undefined property: stdClass::$editionLayers

- CHANGELOG-3.4.md
- CHANGELOG-3.5.md
- lizmap/www/assets/js/filter.js
> fix export in filter data with form

- lizmap/www/assets/js/filter.js
Backport #2503
Authored by: @drillinP
> [Backport release_3_4] fix export in filter data with form

- tests/units/classes/Project/ProjectConfigTest.php
* Inspired by https://github.com/3liz/lizmap-web-client/pull/2348
> Test an empty project config

- lizmap/modules/lizmap/lib/Project/Project.php
> Fix regression with the print button

- lizmap/modules/view/classes/popup.class.php
- phpstan.neon
> [Backport release_3_4] [Bugfix] View Popup class: manually canonize path to authorize symlink

- .github/workflows/php-stan.yml
- .gitignore
- lib/jelix/db/jDb.class.php
- lib/jelix/events/jEvent.class.php
- lib/jelix/forms/jFormsBase.class.php
- lib/jelix/init.php
- phpstan.neon
- tests/docker-conf/phpfpm/appctl.sh
- tests/lizmap-ctl
- tests/units/composer.json
> [tests] fix issues with phpstan, and add lizmap-ctl phpstan subcommand

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- tests/docker-conf/nginx-default.conf
- tests/lizmap-ctl
In form containing upload controls, the `accept` attribute was not filled correctly because of errors during the parsing of the qgis filter.
> Fix file upload

- lizmap/www/assets/css/map.css
Change icons color on hover over buttons with btn-primary class
Without this commit
With this commit
> Use white icons on button.btn-primary class hover

- CHANGELOG-3.4.md
- lizmap/www/assets/js/map.js
- tests/qgis-projects/tests/base_layers.qgs
- tests/qgis-projects/tests/base_layers.qgs.cfg
Backport #2619
Authored by: @drillinP
> [Backport release_3_4] Change URL ign basemap 

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/customProjectVariables.qgs
- tests/units/testslib/QgisProjectForTests.php
> Add getter for custom QGIS project variables

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
* Manually Backport #2638
* Authored by: @nboisteault
> [Backport release_3_4] Add getter for custom QGIS project variables (#2638)

- lizmap/www/assets/js/map.js
> Translate mini-dock-close button

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/www/assets/js/map.js
> [Backport release_3_4][BUGIX] Selection & Export - Use the selectiontoken & POST to QGIS Server

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/relations.qgs
- tests/units/testslib/QgisProjectForTests.php
Relation data should be read during the xml parsing, not at runtime.
* Ticket : #2661
> Fix a regression during the init of relation references into forms

- lizmap/modules/view/templates/map_edition.tpl
- lizmap/www/assets/js/edition.js
- tests/qgis-projects/tests/form_edition_snap.md
- tests/qgis-projects/tests/form_edition_snap.qgs
- tests/qgis-projects/tests/form_edition_snap.qgs.cfg
- tests/qgis-projects/tests/tests_dataset.sql
This part of the code is hard to change and there are regression risks. I'll try to add some more tests later.
* Ticket : #2611
> Fix: Snapping missing when editing existing feature

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
Backported from the release 3.5
* Funded by Valabre
> Attribute table - Fix the link of selected features between a parent a child layer

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
> [Backport release_3_5][Bugfix] ValueMap widget parsing config

- docker/lizmapConfig.ini.php.dist
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/var/config/lizmapConfig.ini.php.dist
Fix server URL when using FCGI for the Lizmap entrypoint
> Fix server URL when using FCGI for the Lizmap entrypoint

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/js/map.js
- tests/end2end/cypress/fixtures/export/export_data_uids.geojson
- tests/end2end/cypress/fixtures/export/export_data_uids_features_2_and_4.geojson
- tests/end2end/cypress/fixtures/export/export_parent_layer.geojson
- tests/end2end/cypress/fixtures/export/export_parent_layer_feature_2.geojson
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/qgis-projects/tests/feature_toolbar.qgs
- tests/qgis-projects/tests/feature_toolbar.qgs.cfg
* when the layer is not spatial
* when the layer has parenthesis inside its name
* Ticket : #2715
@rldhont need to check if I need to backport it to 3.4
> Attribute table - Fix the export when a selection or a filter is active

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- tests/end2end/cypress/integration/form_edition_all_field_type-ghaction.js
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/form_edition_all_field_type.qgs.cfg
- tests/qgis-projects/tests/tests_dataset.sql
- tests/units/classes/Project/QgisProjectTest.php
> Fix parsing of map values 

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
- lizmap/www/assets/jelix/js/jforms_jquery.js
- tests/end2end/cypress/integration/form_advanced-ghaction.js
- tests/qgis-projects/tests/form_advanced.qgs
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2783
> [Backport release_3_4][Bugfix] For Value Relation, Empty value is added for required fields

- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/controllers/search.classic.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2723
> [Backport release_3_4]Fix Remove user private group from request to QGIS Server

- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/controllers/search.classic.php
Search controller and FTS does not use appContext
> Search without private group

- lizmap/modules/lizmap/classes/qgisProject.class.php
Regression in refactoring QGIS Project class
> [Bugfix] Get CRS Proj4 definition from QGIS project

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2797
> [Backport release_3_4] Fix: Extract Version from OGC XML Request

- lizmap/modules/lizmap/controllers/service.classic.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
The method getProj4 from project return string and not DOM element
> [Bugfix] lizmap service GetProj4 request

- lizmap/modules/lizmap/controllers/service.classic.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2815
> [Backport release_3_4] [Bugfix] lizmap service GetProj4 request

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2824
> [Backport release_3_4][Bugfix] Empty value in Jelix menulist

- lizmap/modules/lizmap/controllers/edition.classic.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2841
> [Backport release_3_4] [Bugfix] Edition: update and delete is not authorized for feature id 0

- lizmap/modules/lizmap/classes/lizmapProject.class.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2853
> [Backport release_3_4] Filter by attribute: the attribute can be upper case

- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
Add end2end tests to check drill down fields
> [Tests] end2end: finalize cypress form value relation tests

- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/controllers/searchFts.classic.php
- tests/end2end/cypress/integration/lizmap_search-ghaction.js
- tests/qgis-projects/tests/load_sql.sh
- tests/qgis-projects/tests/set_tests_lizmap_search.sql
The lizmap_search can be filtered by user.
> [Bugfix] lizmap_search application context from project

- assets/src/components/FeatureToolbar.js
- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Utils.js
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/www/assets/css/map.css
* Ticket : support 1798
* Funded by: Les portes du soleil
> Add export button to featureToolBar

- lizmap/modules/view/controllers/media.classic.php
UX - Allow thumbnail with capital letters in the extension
> UX - Allow thumbnail with capital letters in the extension

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
Lizmap Web Client is checking TYPENAME parameter, but TYPENAME is not mandatory if FEATUREID is defined.
> [Bugfix] Request WFS: Typename or feature id are mandatory

- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/2908
>  [Backport release_3_4] [Bugfix] WFS GetCapabilities - Default version 1.0.0

- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/2904
> [Backport release_3_4][Bugfix] Request WFS: Typename or feature id are mandatory

- lizmap/modules/dataviz/controllers/service.classic.php
- phpstan-baseline.neon
Errors were not well returned and docstrings missing.
> Dataviz: Add service method docstring and fix errors

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/dataviz/controllers/service.classic.php
- phpstan-baseline.neon
Backport https://github.com/3liz/lizmap-web-client/pull/2911
> [Backport release_3_5] Dataviz: Add service method docstring and fix errors

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- phpstan-baseline.neon
Fixing some bugs:
* Getting shortName for layer tree group
* Gettting showFeatureCount for layer tree
Funded by 3Liz
> Fix layer tree parsing for QGIS 3.22 project

- lizmap/modules/lizmap/classes/lizmapProject.class.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2922
> [Backport release_3_4] Fix layer tree parsing for QGIS 3.22 project

- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- phpstan-baseline.neon
Clear the PHPStan errors baseline for file lizmap/modules/lizmap/lib/Project/QgisProject.php
> Clean up PHPStan errors baseline for \Lizmap\Project\QgisProject

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- tests/units/classes/lizmapWktTest.php
- tests/units/classes/qgisExpressionUtilsTest.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2934
> [Backport release_3_4] [Bugfix] Lizmap WKT parser: support Multi

- lizmap/modules/action/classes/actionConfig.class.php
- lizmap/modules/action/controllers/service.classic.php
- lizmap/modules/filter/controllers/service.classic.php
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/controllers/repository.cmdline.php
- lizmap/modules/lizmap/controllers/service.classic.php
- phpstan-baseline.neon
Try to fix some PHPStan errors. Some errors are du to multiple serviceCtrl classes in the code.
> PHPStan fixing

- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/controllers/translate.classic.php
- lizmap/responses/myHtmlResponse.class.php
No more necessary since https://github.com/3liz/lizmap-web-client/pull/2729
> Revert old cache rules

- lizmap/www/assets/jelix/js/jforms_jquery.js
If the content of dynamic fill is updated, the form looses the value.
In Lizmap case, the content of a fill is updated by the geometry and we loose the value set by the PHP part.
* Funded by Ville d'Avignon
> [Bugfix] Jelix jForms jQuery dynamicFillAjax - keep value

- lizmap/www/assets/js/map.js
- tests/end2end/cypress/integration/print.js
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2892
Also cherry-pick 9014c16b527f8e69bf285615e8f00735ad5cab69 by @nboisteault
> [Backport release_3_4] [Bugfix] Force to open GetPrint in blank window

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- tests/units/classes/lizmapWktTest.php
Before parsing WKT string, checking it.
> Add Lizmap WKT check method

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php
- tests/units/classes/lizmapWktTest.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2951
> [Backport release_3_4] Add Lizmap WKT check method

- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
Manually Backport https://github.com/3liz/lizmap-web-client/pull/2957
> [Backport release_3_4] [Bugfix] attribute table - doesn't export when a selection is active

- lizmap/www/assets/js/dataviz/dataviz.js
- lizmap/www/assets/js/map.js
* Ticket : 
* #2767 --> plot in popup maintains json customization defined in lizmap plugin
* #491 --> plots order in popup respects plot order defined in lizmap plugin
* Tethys S.r.l. www.tethys.srl
> Bugfix dataviz popup

- lizmap/www/assets/js/map.js
- tests/end2end/cypress/integration/print-ghaction.js
The changes done with #2892 [Bugfix] Force to open GetPrint in blank window do not provide the filename and extension
* Funded by TACTIS
> [Bugfix] Download export with the filename

- tests/add_server_plugins.sh
Tests - Use the Lizmap server plugin
> Tests - Use the Lizmap server plugin

- CHANGELOG-3.6.md
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/modules/view/locales/en_US/edition.UTF-8.properties
- lizmap/modules/view/templates/map_edition.tpl
- lizmap/www/assets/js/edition.js
- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
Provide the capability to update geometry with GPS and form coordinates.
* Inspired by SDEE 48
> [Feature] Edition: Button to restart drawing geometry

- tests/end2end/cypress.json
- tests/end2end/cypress/integration/cmdline-wmts-ghaction.js
- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
- tests/end2end/cypress/integration/lizmap_search-ghaction.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
- tests/end2end/cypress/support/commands.js
Refactor login and password in cypress : 
* Make login and logout special test function for cypress
* Make login and password dynamic so we can test on other Lizmap instance easier by giving environment variable
Funded by 3Liz
> Tests - Refactor login and password in cypress

- tests/README.md
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
- tests/end2end/cypress/integration/print-ghaction.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
- tests/end2end/cypress/integration/treeview-ghaction.js
- tests/end2end/cypress/support/commands.js
- tests/end2end/cypress/support/function.js
Subset of #3020 
@nboisteault What do you think about this `mapClick` command ?
> Tests - Add common functions for cypress

- lizmap/www/assets/js/switcher-layers-actions.js
- tests/end2end/cypress/integration/theme.js
- tests/qgis-projects/tests/theme.qgs
- tests/qgis-projects/tests/theme.qgs.cfg
> Fix theme. Style not switching when layer has a shortname

- tests/docker-conf/phpfpm/Dockerfile
- tests/docker-conf/phpfpm/appctl.sh
When test docker stack is launched, JS files are automatically built
Build is remake on JS file modification
Funded by 3Liz
> Build JS files automatically

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3079
> [Backport release_3_5][Bugfix] Attribute table refreshing

- tests/end2end/cypress/integration/form-filter-ghaction.js
- tests/qgis-projects/tests/form_filter.md
Tests - Add form filter cypress test
Funded by 3Liz
> Tests - Add form filter cypress test

- tests/end2end/cypress/integration/external_wms_layer-ghaction.js
- tests/qgis-projects/tests/external_wms_layer.qgs
- tests/qgis-projects/tests/external_wms_layer.qgs.cfg
The WMS ign.fr is sometimes too slow for cypress. Let's try our server :)
https://demo.lizmap.com/lizmap/index.php/lizmap/service/?repository=cypress&project=base_external_layers&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
Hidden project from the UI
Funded by 3Liz
> Tests - Switch from ign.fr to lizmap.com to provide an external WMS in cypress

- lizmap/modules/dataviz/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/end2end/cypress/integration/dataviz-ghaction.js
- tests/qgis-projects/tests/dataviz.qgs
- tests/qgis-projects/tests/dataviz.qgs.cfg
Regression #3029
By fixing it, I got one deprecated notice in `lizmap/var/log/errors.log` which must stay empty ...
Funded by 3Liz
> UX - Fix icon not displayed for dataviz panel

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
The filtered layer's attribute table has to be filtered at the opening.
Funded by 3Liz
> [Bugfix] Open filtered layer attribute table 

- tests/end2end/cypress/integration/attribute_table-ghaction.js
Based on cherry-picking #3116
Funded by 3liz
> [Tests] e2e Attribute Table: Check selection / filter / refresh

- assets/src/legacy/filter.js
As described in the documentation, we should use a OR clause between the selected values of the same field
Fixes #2694
Funded by [Ville d'Avignon, France](https://cartes.mairie-avignon.com/cartes/)
> Form filter - Use OR between the uniques values of the same field

- lizmap/modules/view/controllers/app.classic.php
- lizmap/modules/view/controllers/embed.classic.php
- lizmap/modules/view/controllers/lizAjax.classic.php
- lizmap/modules/view/controllers/map.classic.php
- lizmap/modules/view/controllers/media.classic.php
- phpstan-baseline.neon
> PHPStan: view/controllers enhancement

- assets/src/legacy/map.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/css/map.css
No more "SERVICE NON DISPONIBLE!"  🎉
@Gustry @mdouchin @rldhont Do you have any better proposition for the error message?
Funded by 3Liz
> Cleanly handle project loading error at startup

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/controllers/server_information.classic.php
Linked to #2972
Need to add a new step when releasing a version to edit this new file with latest version of the Lizmap server plugin version
> Config - Make a single configuration for version using an INI file

- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
> Server info - always fetch metadata from qgis server even if we are not an admin

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/cypress/integration/requests-getcapabilities-ghaction.js
- tests/end2end/cypress/integration/requests-service-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3174
> [Backport release_3_5] fix(request): OGC GetCapabilities with tests

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- tests/end2end/cypress/integration/requests-getcapabilities-ghaction.js
- tests/end2end/cypress/integration/requests-service-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3174
> [Backport release_3_4] fix(request): OGC GetCapabilities with tests

- assets/src/legacy/map.js
Following the call from OSM
https://twitter.com/OSM_Tech/status/1564685832300134402
https://github.com/openstreetmap/operations/issues/737
> OL - Remove legacy OSM tile servers

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
no more php error in php8
Ticket : #3154
> quick fix using is_array

- tests/docker-compose.yml
- tests/docker-conf/phpfpm/Dockerfile
- tests/docker-conf/phpfpm/xdebug.ini
Install the xdebug extension into the php-fpm container.
Funded by 3Liz
> [tests] install xdebug

- lizmap/modules/lizmap/lib/Server/Server.php
Metadata - Add a flag if the saas module is enabled
Funded by 3Liz.com
> Metadata - Add a flag if the saas module is enabled

- lizmap/app/responses/AbstractLizmapHtmlResponse.php
- lizmap/app/responses/adminHtmlResponse.class.php
- lizmap/app/responses/adminLoginHtmlResponse.class.php
- lizmap/app/system/mainconfig.ini.php
To improve the security of Lizmap.
Funded by 3Liz
> New configuration param to setup the Content Security Policy header

- phpstan-baseline.neon
A fix removing no longer existing errrors in php stan baseline
> fix phpstan-baseline for release 3.5

- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
- tests/end2end/cypress/integration/form_advanced-ghaction.js
- tests/end2end/cypress/integration/form_edition-ghaction.js
- tests/end2end/cypress/integration/form_edition_reverse_geom-ghaction.js
- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
- tests/end2end/cypress/integration/form_edition_without_creation-ghaction.js
- tests/end2end/cypress/integration/popup-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3238
> [Backport release_3_5] [Tests] e2e cypress: Switch to mapClick helper

- tests/end2end/cypress/integration/print-ghaction.js
- tests/qgis-projects/tests/test_print.qgs
- tests/qgis-projects/tests/test_print.qgs.cfg
* Update the **test_print** project
* Ada a simple atlasprint test
Funded by 3Liz
>  [Tests] Add a simple test for atlasprint

- assets/src/components/FeatureToolbar.js
- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
> Fix feature tool bar

- lizmap/modules/view/controllers/media.classic.php
- phpstan-baseline.neon
Backport https://github.com/3liz/lizmap-web-client/pull/3246
> [Backport release_3_5] Tests: PHPSTan - pathinfo always returns filename

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/cypress/integration/requests-getcapabilities-ghaction.js
Fixes #3174
Fixes #3128
Funded by Andromede Oceanologie https://www.andromede-ocean.com
> fix(request): OGC GetCapabilities with tests

- lizmap/app/system/mainconfig.ini.php
Set Lizmap server to minimum version 1.2.0
> Set Lizmap server to minimum version 1.2.0

- .github/workflows/e2e_tests_cypress.yml
- tests/run-docker
GH Action - Show the .env file when running the workflow
> GH Action - Show the .env file when running the workflow

- assets/src/components/Digitizing.js
- assets/src/legacy/map.js
- assets/src/modules/Digitizing.js
- assets/src/modules/SelectionTool.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
Migrate draw tool from OpenLayers 2 to OpenLayers 7
Funded by [Avignon](https://avignon-tourisme.com/)
> Draw OL2 to OL7

- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
Try QGIS Server with WMS GetCapabilities Without MPA only if lizmap plugin is not well installed or configured.
Funded by 3Liz
> Try QGIS Server if lizmap server plugin error

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/end2end/cypress/integration/form_edition_all_field_type-ghaction.js
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/tests_dataset.sql
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3254
Authored by: @mdouchin
> [Backport release_3_5] Editing - Fix: the HTML form widget must use WYSIWYG editor

- .github/workflows/e2e_tests.yml
- .github/workflows/e2e_tests_cypress.yml
- README.md
> Playwright Github Action

- assets/src/modules/Map.js
- tests/end2end/cypress/integration/base_layers-ghaction.js
- tests/qgis-projects/tests/base_layers.qgs.cfg
Fix #2978  weird zoom behavior - zoom stops at 14076 value in the scale
Funded by 3liz
> [Bugfix] Scaleline values are constraint by default baselayer and not the map

- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/dataviz/controllers/service.classic.php
- lizmap/modules/lizmap/controllers/edition.classic.php
The Dataviz module has not been updated after commit 2da404ce145eff12626b757175e69bd537eaa758 **[API] Introducing \Lizmap\Request\OGCResponse**
Funded by Grand Narbonne https://www.legrandnarbonne.com/
> [Bugfix] Dataviz: fetching WFS data from file

- lizmap/modules/lizmap/classes/lizmap.class.php
- tests/end2end/cypress/integration/projects_filename_dot_space-ghaction.js
- tests/end2end/playwright/startup.spec.js
- tests/qgis-projects/tests/base_layers with space.qgs
- tests/qgis-projects/tests/base_layers with space.qgs.cfg
- tests/qgis-projects/tests/base_layers.withdot.qgs
- tests/qgis-projects/tests/base_layers.withdot.qgs.cfg
project file name can now have space or . in it (test.cats.qgs, "my filename.qgs" 
Ticket : #2353   and #2020
Funded by 3Liz
> allow space and dot in project filename

- lizmap/modules/lizmap/classes/lizmap.class.php
- tests/end2end/cypress/integration/filename_with_dots_space-ghaction.js
- tests/qgis-projects/tests/base_layers with space.qgs
- tests/qgis-projects/tests/base_layers with space.qgs.cfg
- tests/qgis-projects/tests/base_layers.with.dot.qgs
- tests/qgis-projects/tests/base_layers.with.dot.qgs.cfg
only for 3.5
manual backport of #3289
due to playwright test unavailable in 3.5
Funded by 3liz
> Dots space in project filename (lwc 3.5)

- lizmap/modules/dataviz/classes/datavizPlot.class.php
- tests/end2end/cypress/integration/dataviz-ghaction.js
- tests/qgis-projects/tests/dataviz.qgs
- tests/qgis-projects/tests/dataviz.qgs.cfg
When there is more than one Y value for each X value, the plot was not well rendered if the option "Horizontal" was set.
Funded by: Valabre https://www.valabre.com/
> Dataviz - Fix wrong display for the horizontal bar charts

- .github/workflows/e2e_tests.yml
- tests/docker-compose.yml
- tests/end2end/othersite/index.html
CI - Fix some issues on Cypress and upgrade it : 
* Upgrade Cypress action to 5.0.0
* Add the othersite host
* Skip CRON test on Lizmap 3.5
Funded by 3Liz
> CI - Fix some issues on Cypress and upgrade it

- lizmap/modules/lizmap/lib/Project/QgisProject.php
fix #3331 
fix #3326
Funded by 3liz
> empty xml count failed

- lizmap/www/assets/css/admin_lizpoi.css
- lizmap/www/assets/css/map.css
- lizmap/www/assets/css/media.css
> Remove legacy CSS

- lizmap/modules/admin/classes/config.listener.php
- lizmap/modules/admin/controllers/landing_page_content.classic.php
- lizmap/modules/admin/controllers/logs.classic.php
- lizmap/modules/admin/controllers/qgis_projects.classic.php
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/controllers/theme.classic.php
- lizmap/modules/admin/install/install.php
- lizmap/modules/admin/install/upgrade_newAclRights.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/locales/en_US/jacl2.UTF-8.properties
- lizmap/modules/admin/templates/config_section.tpl
- lizmap/modules/admin/templates/config_services.tpl
- lizmap/modules/admin/templates/config_theme.tpl
- lizmap/modules/admin/templates/landing_page_content.tpl
- lizmap/modules/admin/templates/logs_counter.tpl
- lizmap/modules/admin/templates/logs_detail.tpl
- lizmap/modules/admin/templates/logs_view.tpl
- lizmap/modules/admin/templates/project_list.tpl
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/admin/templates/theme.tpl
- lizmap/modules/admin/templates/user_groups.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Repository.php
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
- tests/end2end/cypress.json
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/end2end/cypress/support/commands.js
- tests/qgis-projects/tests/set_tests_respository_rights.sql
This addition will allow the Lizmap desktop plugin to retrieve the needed data to help the publisher
* the list of groups of users
* the list of Lizmap repositories with 
* the groups allowed to view the projects and to edit the layers
* the list of projects
Funded by Direction Départementale de la Terre et de la Mer de l'Hérault (DDTM 34): https://www.herault.gouv.fr/Services-de-l-Etat/Agriculture-environnement-amenagement-et-logement/Direction-Departementale-des-Territoires-et-de-la-Mer-de-l-Herault-DDTM-34
> JSON Lizmap Metadata - Add groups and repositories

- assets/src/modules/Digitizing.js
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3402
> [Backport release_3_6][Bugfix] Defined Digitizing context 

- assets/src/modules/Digitizing.js
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3402
>  [Backport release_3_5][Bugfix] Defined Digitizing context

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
UX - Explain a little that some projects are not displayed
Funded by 3Liz
> UX - Explain a little that some projects are not displayed

- assets/src/legacy/map.js
Funded by Le Grand Narbonne https://www.legrandnarbonne.com/
> Filter performance - Avoid to launch many useless GETFILTERTOKEN request

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/tests_dataset.sql
To be sure a checkbox is valid, even when it is readonly, the default value has to be equal to check or uncheck value.
https://github.com/jelix/jelix/blob/jelix-1.6.x/lib/jelix/forms/controls/jFormsControlCheckbox.class.php#L53
Funded by Terre de Provence Agglomération https://www.terredeprovence-agglo.com/
> [Bugfix] Form: A checkbox has to have a default equal to check or uncheck value

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
> [Bug] The source key defined by QGIS for Postgres layer may not be a field

- .github/workflows/e2e_tests.yml
- .gitignore
- tests/end2end/cypress/integration/print-ghaction.js
Cypress - Fix test about atlas and improve GH Action debug
> Cypress - Fix test about atlas and improve GH Action debug

- lizmap/composer.json
- lizmap/modules/filter/classes/filterDatasource.class.php
- lizmap/modules/filter/controllers/service.classic.php
use [violet/streaming-json-encoder](https://packagist.org/packages/violet/streaming-json-encoder) to stream data in a streamedResponse instead of fetching all results in php
Funded by 3liz
> use stream json encoder to stream data in a streamed Response

- lizmap/composer.json
- lizmap/modules/filter/classes/filterDatasource.class.php
- lizmap/modules/filter/controllers/service.classic.php
Backport https://github.com/3liz/lizmap-web-client/pull/3462
Authored by: @nworr
> [Backport release_3_6]  use stream json encoder to stream data in a streamed Response

- lizmap/modules/filter/controllers/service.classic.php
quickfix #3462 
Funded by 3liz
> use binaryResponse instead of deprecated streamedResponse

- phpstan-baseline.neon
> removing phpstan ignored error fixed in jelix

- lizmap/modules/lizmap/commands.php
- lizmap/modules/lizmap/controllers/project.cmdline.php
- lizmap/modules/lizmap/lib/CliHelpers/RepositoryWMSChecker.php
- lizmap/modules/lizmap/lib/Commands/ProjectLoad.php
- phpstan-baseline.neon
`project:load jelix command` alternative for console.php using CliHelpers
use a output callback in helper as a simple solution
Funded by 3liz
> All project WMS test commands in console.php

- assets/src/components/Print.js
- assets/src/modules/Digitizing.js
- tests/end2end/playwright/print.spec.js
- tests/qgis-projects/tests/print.qgs.cfg
> Display draw for print redlining

- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/www/assets/js/admin/activate_datatable.js
Backport https://github.com/3liz/lizmap-web-client/pull/3449 
Authored by: @nworr
> [Backport release_3_6] Admin : Projects Panel convert lizmap plugin version from int to sortable string

- assets/src/legacy/map.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3478
> [Backport release_3_5] [Bugfix] Selection by Point - The bbox is empty

- assets/src/legacy/attributeTable.js
- assets/src/legacy/map.js
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/end2end/cypress/integration/requests-wfs-ghaction.js
Fixes https://github.com/3liz/lizmap-web-client/issues/3474
If the layers are not in EPSG:4326 to zoom button in the attribute table goes the map to far away.
And `getDataAndFillAttributeTable` and `getFeatureData` as iso
Funded by 3liz https://3liz.com/
> [Bugfix] zoom to feature (from the attribute table) goes to far away

- tests/end2end/cypress/integration/requests-service-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3513
> [Backport release_3_5] [Tests] e2e: Enhancing the way to check proj4 string

- lizmap/composer.json
- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/OGCResponse.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/ProxyResponse.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- phpstan-baseline.neon
Backport https://github.com/3liz/lizmap-web-client/pull/3505
> [Backport release_3_6] Using Guzzle Stream to speed up WFS GetFeature

- .github/workflows/e2e_tests.yml
- .gitignore
- lizmap/modules/admin/controllers/maps.classic.php
- tests/README.md
- tests/end2end/package-lock.json
- tests/end2end/package.json
- tests/end2end/playwright.config.js
- tests/end2end/playwright/maps-management.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/3415
> [Backport release_3_5] [Bugfix] Defined default repository rights

- assets/src/components/FullScreen.js
- assets/src/images/svg/fullscreen-exit.svg
- assets/src/images/svg/fullscreen.svg
- assets/src/index.js
- lizmap/www/assets/css/map.css
Custom element button allowing to display an element in full screen.
Use the `selector` parameter to select the element e.g.: `<lizmap-fullscreen selector="#map"></lizmap-fullscreen>`
Funded by 3Liz
> Feature: lizmap-fullscreen element

- lizmap/modules/dynamicLayers/controllers/map.classic.php
- lizmap/modules/lizmap/controllers/default.classic.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- phpstan-baseline.neon
remove phpstan ignored errors by usging phpDoc TypeHint for `jresponseRedirect`
Funded by 3liz
> [phpstan] phpDoc TypeHint for redirect response

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/var/config/mainconfig.ini.php
- tests/units/classes/Project/ProjectConfigTest.php
Add methods to check if the project needs an update which lead to a warning.
> [Backport release_3_5] Check if the project needs an update which lead to a warning

- lizmap/modules/lizmap/commands.php
- lizmap/modules/lizmap/controllers/wmts.cmdline.php
- lizmap/modules/lizmap/lib/CliHelpers/WMTSCache.php
- lizmap/modules/lizmap/lib/Commands/WMTSCacheClean.php
- lizmap/modules/lizmap/lib/Commands/WMTSCapabilities.php
- lizmap/modules/lizmap/lib/Commands/WMTSSeed.php
- tests/docker-conf/phpfpm/appctl.sh
- tests/end2end/cypress/integration/cmdline-wmts-ghaction.js
- tests/lizmap-ctl
` wmts:capabilities ` `wmts:seed` and  `wmts:clean` jelix command  alternative for `console.php`
Use a new Helper Class
Funded by 3liz
> wmts cache command

- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- lizmap/modules/view/templates/main.tpl
Enhancing the landing page by displaying the message with link to check the server information panel.
Ticket #3367 #3544
Funded by 3liz
> Fix message about maps cannot be displayed

- dev/Dockerfile
- dev/Makefile
- dev/README.md
> Fix the docker image to build lizmap

- .gitignore
- tests/Makefile
- tests/qgis-server-plugins/upgrade_projects.py
Linked to #3511 and #3585
Well, this script is not a QGIS plugin, despite its folder name
> Tests - Add makefile command to upgrade QGIS projects

- assets/src/legacy/attributeTable.js
- assets/src/legacy/filter.js
- tests/end2end/cypress/integration/key_value_mapping-ghaction.js
- tests/qgis-projects/tests/key_value_mapping.qgs
- tests/qgis-projects/tests/key_value_mapping.qgs.cfg
The attribute layer and form filter are concerned by this fix
Ticket : # 
Funded by
> Fix key value for layer not published in WFS

- lizmap/www/assets/css/filter.css
Funded by 3liz
simple css to fix form filter box rendering
> fix form filter select rendering

- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
The feature toolbar end2end tests were falcky because of children GetFeatureInfo POST request.
> [Tests] e2e: Unflacky feature toolbar

- assets/src/legacy/attributeTable.js
The GetSelectionToken method does not check if the provided typename is the right wms name. The wms name of a layer is the shortname or the name of the layer.
Funded by SMICA https://www.smica.fr/
> [Bugfix] Use shortname in selection token if provided

- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/3614
> [Backport release_3_6][Tests] e2e: Unflacky feature toolbar

- assets/src/legacy/attributeTable.js
Backport https://github.com/3liz/lizmap-web-client/pull/3613
> [Backport release_3_6][Bugfix] Use shortname in selection token if provided

- assets/src/legacy/attributeTable.js
Backport https://github.com/3liz/lizmap-web-client/pull/3613
> [Backport release_3_5][Bugfix] Use shortname in selection token if provided

- lizmap/app/system/mainconfig.ini.php
Linked to #3605 and https://github.com/3liz/qgis-lizmap-server-plugin/pull/38
CC @rldhont
> Bump minimal Lizmap server plugin version to 2.7.1

- assets/src/legacy/attributeTable.js
The EXP_FILTER was not build for cascade and pivot layers
Funded by Keolis Rennes https://www.keolis-rennes.com/
> [Bugfix] Build EXP_FILTER for casade and pivot layers

- tests/end2end/cypress/integration/attribute_table-ghaction.js
Checking the boody of post requests and the parameters of getmap requests
> [Tests] e2e: enhancing attribute table

- assets/src/legacy/map.js
Backport https://github.com/3liz/lizmap-web-client/pull/3630
> [Backport release_3_6] [Bugfix] GetPrint: Use baselayer shortname

- assets/src/legacy/map.js
Backport https://github.com/3liz/lizmap-web-client/pull/3630
>  [Backport release_3_5] [Bugfix] GetPrint: Use baselayer shortname

- lizmap/modules/lizmap/lib/Server/Server.php
> Add webdav informations into Lizmap metadata

- lizmap/modules/lizmap/lib/Server/Server.php
Follow up from #3629
Done on 3.6 if we do a quick release soon
> Metadata - Use better right if the user can access

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
Follow up from https://github.com/3liz/lizmap-web-client/pull/3629 and #3642
I guess we want to make our users aware later.
> UX - Display the URL of webdav if possible

- assets/src/components/FeatureToolbar.js
> Fix: export in popup featureToolBar

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
Hi, 
we use uuid in forms for relational values. 
We simply add this line and it works for us.
Ticket : # 
Funded by
> Add uuid type in relationnal values support

- assets/src/legacy/attributeTable.js
Backport https://github.com/3liz/lizmap-web-client/pull/3684
Authored by: @mdouchin
> [Backport release_3_5] Data filtering - Fix the filter not applied to the children layers

- lizmap/modules/lizmap/lib/Project/Project.php
```
2023-06-02 15:01:15	[8]	Undefined index: qgsmtime	/srv/lizmap-web-client/lizmap/modules/lizmap/lib/Project/Project.php	170
```
Funded by Geolab.re
> Fix: Warning about qgsmtime for embedded layer

- assets/src/legacy/attributeTable.js
- assets/src/legacy/bottom-dock.js
- assets/src/legacy/edition.js
- assets/src/legacy/filter.js
- assets/src/legacy/timemanager.js
Backporting manually somes fixes from https://github.com/3liz/lizmap-web-client/pull/3073
> [Backport Release_3_6] Bugfix javascript modules

- assets/src/legacy/map.js
Fixes #3671 [Bug]: OpenTopoMap base map layer don't work in Lizmap
> [Bugfix] Support openTopoMap

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/playwright/qgis-request.spec.js
To get maximum data in JSON GetLegendGraphic, the requests for each layer are done separatly then merged.
> [Feature] GetLegendGraphic - request each layer separatly for json

- assets/src/legacy/switcher-layers-actions.js
- lizmap/modules/lizmap/classes/qgisProject.class.php
Ticket : fix #3519 
Funded by Festival Balélec - Téo Goddet
> Fix visibility preset error

- assets/src/legacy/switcher-layers-actions.js
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/themes-3_22.qgs
- tests/units/classes/Project/Ressources/themes-3_26.qgs
Fixes #3519 the right way and added tests
Funded by 3Liz
> [Bugfix] Fix visibility preset error

- assets/src/modules/state/LayerTree.js
- tests/js-units/node/config/layer.test.js
- tests/js-units/node/state/layerTree.test.js
If a layer or a group is checked, its parents will be checked.
If a group is unchecked, its children are not visible
> [JavaScript] LayerTreeItem cheked and visibility management

- assets/src/modules/State.js
- assets/src/modules/config/LayerTree.js
- assets/src/modules/config/LayersOrder.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/MapLayer.js
- tests/js-units/node/config/layerTree.test.js
- tests/js-units/node/config/layersOrder.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
> [JavaScript] Module State MapLayer

- lizmap/modules/lizmap/lib/Project/Project.php
> simplify test for phpstan

- assets/src/legacy/attributeTable.js
- assets/src/legacy/map.js
- assets/src/modules/Map.js
- assets/src/modules/ProxyEvents.js
- assets/src/modules/State.js
- assets/src/modules/state/Layer.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/Map.js
- assets/src/modules/state/MapLayer.js
- tests/js-units/data/montpellier-capabilities.json
- tests/js-units/node/state/layer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/map.test.js
- tests/js-units/node/state/maplayer.test.js
New events:
* `layer.selection.changed`
* `layer.selection.token.changed`
* `layer.filter.changed`
* `layer.filter.token.changed`
> [JavaScript] Module State layer

- assets/src/modules/state/Layer.js
- tests/js-units/data/mutually-exclusive-capabilities.json
- tests/js-units/data/mutually-exclusive-config.json
- tests/js-units/node/state/layer.test.js
The visibility of item in a Layer Group is managed at the `LayerItemState`
> [JavaScript] Manage Layer Group mutually exclusive

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Events/LizmapMetadataEvent.php
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
The new metadata event will allow any modules like webdav to provide metadata on the url /view/app/metadata.
The webdav module will also use the existing LizmapServerVersion event to show information on the server information panel.
Funded by 3Liz
> Remove webdav stuff. The webdav module will bring info via events.

- assets/src/components/Treeview.js
- assets/src/modules/state/Symbology.js
A screenshots are better than description.
The Rule Based Renderer Tree
The Rule Based Renderer filtering
> [JavaScript] TreeView : Respect QGIS Rule Based Renderer tree

- assets/src/legacy/atlas.js
- tests/qgis-projects/tests/atlas.qgs
- tests/qgis-projects/tests/atlas.qgs.cfg
> Fix popup from atlas not working with shortnames

- assets/src/legacy/switcher-layers-actions.js
Fix #3660 but just for next Lizmap 3.7. @mdouchin @rldhont Any other idea to fix it for previous versions?
Funded by 3Liz
> Fix export layer with accent

- assets/src/legacy/map.js
- assets/src/modules/BaseLayersMap.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Permalink.js
New permalink as we move from OL2
Funded by 3Liz
> New permalink not OL2 dependant

- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/install/upgrade_commconfig.php
This parameter is for jCommunity 1.4+
Funded by 3Liz
> [internal] support of new config parameter notificationReceiverEmail

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
It is possible to find in log these lines
```
2023-08-31 12:21:06 162.19.21.20 [8]	Undefined index: crs
/srv/lizmap-web-client/lizmap/modules/lizmap/lib/Request/WMSRequest.php	1051
/cartes/index.php/lizmap/service?repository=flux&project=fond_pnr_osm&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=fond_PNR_osm&STYLES=&WIDTH=256&HEIGHT=256&FORMAT=image/jpeg&SRS=EPSG:2154&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&BBOX=616064.80224160198122263,7011947.87807862646877766,619451.47568167827557772,7015334.55151870287954807
array (   'repository' => 'flux',   'project' => 'fond_pnr_osm',   'SERVICE' => 'WMS',   'VERSION' => '1.1.1',   'REQUEST' => 'GetMap',   'LAYERS' => 'fond_PNR_osm',   'STYLES' => '',   'WIDTH' => '256',   'HEIGHT' => '256',   'FORMAT' => 'image/jpeg',   'SRS' => …
```
> [Bugfix] Notice Undefined index: crs

- assets/src/components/Print.js
Note: rotation does not work. Is it a QGIS bug?
Funded by 3Liz
https://github.com/3liz/lizmap-web-client/assets/2145040/cfd462cc-0703-4e17-9418-46da3c6ebc09
> Redlining: print labels w/ given size

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
- tests/end2end/cypress/integration/form-filter-ghaction.js
- tests/qgis-projects/tests/attribute_table.qgs
- tests/qgis-projects/tests/attribute_table.qgs.cfg
- tests/qgis-projects/tests/form_filter.qgs
- tests/qgis-projects/tests/form_filter.qgs.cfg
> Use `wmsName` for WMS requests

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- phpstan-baseline.neon
The Polygon filter is provided by QGIS Server. The request could take a long time so the response as to be cached.
Funded by [Conseil Départemental du Calvados](https://www.calvados.fr/accueil.html)
> [PHP] Get cached Polygon filter for project, layer, login and editing context

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- phpstan-baseline.neon
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3895
> [Backport release_3_5] [PHP] Get cached Polygon filter for project, layer, login and editing context

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
In some cases, like editable view, the geometry value is not well retrived and check.
> [Bugfix] Check Geometry Edition constraint

- lizmap/modules/admin/controllers/landing_page_content.classic.php
- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/view/controllers/lizMap.classic.php
- phpstan-baseline.neon
- phpstan.neon
about 30 errors dropped
Funded by 3liz
> Fix phpdoc / update phpstan config to ignore Dao related method/properties

- lizmap/www/assets/js/dataviz/dataviz.js
API changed w/ Lizmap 3.7
Funded by 3Liz
> Fix: `display_when_layer_visible` was not handled

- assets/src/legacy/map.js
- assets/src/modules/WFS.js
> Don't block the map when there is a wrong layer name in URL parameters

- .github/workflows/e2e_tests.yml
> Tests - Try to run some new CI versions

- extra-modules/lizmapdemo/qgis-projects/demoqgis/events.qgs.cfg
- extra-modules/lizmapdemo/qgis-projects/demoqgis/montpellier.qgs.cfg
- tests/end2end/cypress/integration/base_layers-ghaction.js
- tests/qgis-projects/tests/base_layers with space.qgs.cfg
- tests/qgis-projects/tests/base_layers.qgs.cfg
- tests/qgis-projects/tests/base_layers.withdot.qgs.cfg
- tests/qgis-projects/tests/events.qgs.cfg
- tests/qgis-projects/tests/overview-3857.qgs.cfg
> Remove Stamen tiles from files used in tests

- lizmap/modules/view/controllers/map.classic.php
Funded by [SDEC énergie](https://www.sdec-energie.fr/)
> Extendable map parameters for redirection after authentication

- assets/src/modules/Map.js
- lizmap/www/assets/css/map.css
> Zoom to box w/ OL8

- assets/src/legacy/search.js
Backport https://github.com/3liz/lizmap-web-client/pull/3991
Ticket : #3591
Funded by 3Liz
> [Backport release_3_6] use IGN geoplateforme geocode completion service

- CHANGELOG-3.7.md
All changelog in the 3.7 file combined in one for the final release
Most important is the `Added` and `Changed` sections.
Did I miss anything @nboisteault @rldhont @mdouchin ?
`Fixed` is not really true because commits have been backported mainly.
> Docs - Changelog for the 3.7.0 final

- assets/src/legacy/map.js
- assets/src/modules/config/Metadata.js
- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- tests/end2end/cypress/integration/requests-getprojectconfig-ghaction.js
- tests/js-units/data/backgrounds-config.json
- tests/js-units/data/cadastre-caen-config.json
- tests/js-units/data/layer_order-config.json
- tests/js-units/data/montpellier-config.json
- tests/js-units/data/mutually-exclusive-config.json
- tests/js-units/node/config/metadata.test.js
- tests/qgis-projects/tests/dataviz_filtered_in_popup.qgs
- tests/qgis-projects/tests/dataviz_filtered_in_popup.qgs.cfg
- tests/qgis-projects/tests/hide_project.qgs
- tests/qgis-projects/tests/hide_project.qgs.cfg
- tests/qgis-projects/tests/world-3857.qgs
- tests/qgis-projects/tests/world-3857.qgs.cfg
- tests/qgis-projects/tests/world-4326.qgs
- tests/qgis-projects/tests/world-4326.qgs.cfg
Linked to #3983
I will manually backport
> Tests - Upgrade old CFG file having a 3.4 target version

- assets/src/components/MousePosition.js
- assets/src/components/Print.js
- assets/src/legacy/edition.js
- assets/src/legacy/map.js
- assets/src/modules/Action.js
- assets/src/modules/Digitizing.js
- assets/src/modules/Geolocation.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Map.js
- assets/src/modules/Popup.js
- assets/src/modules/SelectionTool.js
- assets/src/modules/interaction/Draw.js
- lizmap/modules/view/templates/map.tpl
- lizmap/www/assets/css/map.css
- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
- tests/end2end/cypress/integration/form_advanced-ghaction.js
- tests/end2end/cypress/integration/form_edition-ghaction.js
- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
- tests/end2end/cypress/integration/test_import_kml.js
- tests/end2end/cypress/support/commands.js
- tests/end2end/playwright/draw.spec.ts
- tests/end2end/playwright/embedded-relation.spec.ts
- tests/end2end/playwright/popup.spec.js
- tests/end2end/playwright/print.spec.ts
- tests/end2end/playwright/webdav-upload.spec.ts
- tests/qgis-projects/tests/feature_toolbar.qgs.action
- tests/qgis-projects/tests/geolocation.qgs
- tests/qgis-projects/tests/geolocation.qgs.cfg
> Put OpenLayers 8 maps on top

- .gitignore
- .gitlab-ci.yml
- lizmap/modules/action/classes/action.listener.php
Fix action.js should not be loaded here : https://demo.snap.lizmap.com/lizmap_3_7/index.php/view/map?repository=testsrepository&project=feature_toolbar
Funded by 3Liz
> Remove completly action.js

- assets/src/modules/Permalink.js
- lizmap/modules/view/templates/map_projects.tpl
The permalink has changed so the way to provide bbox between maps.
> [Bugfix] Projects in map: Keep extent between map

- assets/src/modules/Digitizing.js
- tests/qgis-projects/tests/import_kml.qgs
- tests/qgis-projects/tests/import_kml.qgs.cfg
> Fix import data to draw tool

- lizmap/modules/lizmap/lib/Project/Project.php
- tests/qgis-projects/tests/layer_group_visible_only.qgs
- tests/qgis-projects/tests/layer_group_visible_only.qgs.cfg
Funded by 3Liz
Linked to support 2430
> Fix layer group visible only and location

- assets/src/legacy/map.js
Backport https://github.com/3liz/lizmap-web-client/pull/4101
> [Backport release_3_7] [Bugfix] JS Attribute Table: using wmsName for getFeaturePopupContent

- lizmap/modules/lizmap/lib/Project/Project.php
Funded by Territoire de Belfort, Avignon
> [Bugfix] keep print capabilities even if the config has not been updated to 3.7

- tests/end2end/cypress/integration/projects_homepage-ghaction.js
- tests/end2end/playwright/project-homepage.spec.js
Ticket : https://github.com/3liz/lizmap-web-client/pull/4055#issuecomment-1908260909
Funded by 3Liz
> [end2end]fix DOM search in cypress test

- tests/docker-conf/phpfpm/lizmapConfig.ini.php
- tests/end2end/playwright/bad-repository.spec.js
End2end test for ticket : #4076 
closes #4076 
Funded by 3Liz
> [end2end] test bad repository

- assets/src/components/FeatureToolbar.js
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/add_server_plugins.sh
- tests/end2end/playwright/print.spec.ts
Backport https://github.com/3liz/lizmap-web-client/pull/4114
> [Backport release_3_7] Fix regression : keep atlasprint plugin

- assets/src/modules/map.js
Build base layers after overlay layers to get the base layers zIndex which is the layer min zIndex - 1 Withnthis value, we will be sure that base layers are under the others layers
> [Bugfix] Force base layers zIndex

- assets/src/modules/BaseLayersMap.js
Backport https://github.com/3liz/lizmap-web-client/pull/4122
> [Backport release_3_7] [Bugfix] Force base layers zIndex

- assets/src/legacy/attributeTable.js
- assets/src/legacy/filter.js
> [Bugfix] JS: Get typeName from config

- assets/src/modules/Lizmap.js
Backport https://github.com/3liz/lizmap-web-client/pull/4127
> [Backport release_3_7] JS: Created the map and modules after toolbar created

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.ts
Funded by Conseil Départemental du Vaucluse
> [Bugfix] JS: catch invalid data saved for Digitizing

- tests/end2end/playwright/draw.spec.ts
To complete https://github.com/3liz/lizmap-web-client/pull/4077
> Tests end2end Digitizing: welle check drawn features

- assets/src/modules/Permalink.js
- tests/end2end/playwright/permalink.spec.ts
- tests/end2end/playwright/theme.spec.ts
The Permalink module can receive`hashchange` event even if the hash has not changed.
> [Bugfix] Permalink was apply even if it does not change

- assets/src/modules/config/BaseLayer.js
> IGN baselayers - Fix inversion between scan & plan

- assets/src/components/Treeview.js
- assets/src/modules/config/Options.js
- tests/end2end/playwright/treeview.spec.ts
> Fix hideGroupCheckbox

- .github/workflows/docs.yml
- Makefile
- docs/jsdoc.json
* Skip files having errors
* Skip MGRS.js
> JSDoc - Skip files having errors, skip MGRS.js

- assets/src/modules/Lizmap.js
- assets/src/modules/Map.js
- assets/src/modules/Permalink.js
- assets/src/modules/state/Map.js
- assets/src/utils/EventDispatcher.js
- tests/end2end/cypress/integration/dataviz-api-ghaction.js
- tests/end2end/playwright/permalink.spec.ts
- tests/end2end/playwright/theme.spec.ts
> [Backport release_3_7] JS: Enhancing the way Map is managed

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
> [Bugfix] WMS GetLegendGraphic for no symbols layer

- lizmap/modules/view/controllers/media.classic.php
To speed up main page loading, an ETAG header is added to the illustrations.
> Add ETAG header to project illustration

- lizmap/www/assets/css/media.css
- tests/end2end/playwright/viewport.spec.js
The display of docks was not configured with pointer: coarse.
Funded by VSB
> [Bugfix] CSS: display docks with pointer: coarse

- assets/src/modules/BaseLayersMap.js
- tests/end2end/playwright/viewport.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4219
> [Backport release_3_7] [Bugfix] Disbale High DPI support

- assets/src/modules/state/MapLayer.js
- tests/js-units/node/state/maplayer.test.js
- tests/js-units/package-lock.json
> [Bugfix] JS MapLayer State: WMS Parameters for Group As Layer

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
> locale for project warning can't be html, escaping it before display

- tests/end2end/playwright/n_to_m_relations.spec.ts
Follow up 405676a384fae211dd571c4f7a4f0ffaafba0956
> Fix E2E tests after strings update

- tests/end2end/playwright/project_load_warning.spec.js
- tests/qgis-projects/tests/project_cfg_warnings.qgs
- tests/qgis-projects/tests/project_cfg_warnings.qgs.cfg
Follow up from #4226 
It doesn't seem easy for now to check for http://localhost:8130/admin.php/admin/qgis_projects
Funded by 3Liz
> Tests - Add E2E tests for warnings display

- assets/src/legacy/map.js
The language is missing for DataTable for compact table of children in Popup
> [Bugfix] Language for compact table of children in Popup

- assets/src/legacy/map.js
> [Backport release_3_7] [Bugfix] Language for compact table of children in Popup

- assets/src/legacy/map.js
Manually backport https://github.com/3liz/lizmap-web-client/pull/4257
> [Backport release_3_6] [Bugfix] Language for compact table of children in Popup

- assets/src/modules/Errors.js
- assets/src/modules/Utils.js
- assets/src/modules/WFS.js
- assets/src/modules/WMS.js
To get right errors when using fetch : fetchJSON and fetchHTML methods have been added to Utils to do it.
> JS: defined fetch methods

- assets/src/modules/Lizmap.js
- assets/src/modules/Utils.js
- tests/js-units/node/utils.test.js
- tests/js-units/node/wfs.test.js
- tests/js-units/node/wms.test.js
- tests/js-units/package-lock.json
- tests/js-units/package.json
Backport https://github.com/3liz/lizmap-web-client/pull/4271
> [Backport release_3_7] JS: expose a fetch method that provide a successful response and enhance docs

- assets/src/modules/Lizmap.js
- assets/src/modules/map.js
Now it is possible to define base layers in the project, so it is possible de defined min and max scale for these layers.
> [Bugfix] Apply min and max resolutions to base layers

- assets/src/modules/BaseLayersMap.js
- assets/src/modules/Lizmap.js
Backport https://github.com/3liz/lizmap-web-client/pull/4278
> [Backport release_3_7] [Bugfix] Apply min and max resolutions to base layers

- lizmap/modules/lizmap/controllers/service.classic.php
Enhancing the way Lizmap build Etag and add an Etag to GetKeyValueConfig
> Etag: enhancing building etag in service controller

- assets/src/components/Print.js
- assets/src/modules/Config.js
- assets/src/modules/config/BaseLayer.js
- tests/end2end/playwright/print.spec.js
- tests/qgis-projects/tests/base_layers.qgs
- tests/qgis-projects/tests/base_layers.qgs.cfg
Backport https://github.com/3liz/lizmap-web-client/pull/4299
> [Backport release_3_7] [Bugfix] Printing base layers withlayer in hidden group

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
The layer definition extracted from XML and identified by the layer id could be null.
> The layer definition extracted from XML could be null

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/units/README.md
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
Manual backport of #4236 and #4287 and #4298
> Check plugin version for recently edited QGS file

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/view/templates/popup_all_features_table.tpl
- tests/end2end/playwright/webdav-upload.spec.ts
- tests/qgis-projects/tests/form_upload_webdav.qgs
- tests/qgis-projects/tests/form_upload_webdav.qgs.cfg
- tests/qgis-projects/tests/tests_dataset.sql
Added support for the webdav url replacement in the child compact table when children are displayed in popup.
Updated tests accordingly.
> [Bugfix] Webdav url replacement in popup childrens compact table

- lizmap/modules/lizmap/lib/Project/ProjectCache.php
> Increase CACHE_FORMAT_VERSION to 10

- assets/src/legacy/edition.js
- assets/src/modules/Permalink.js
- assets/src/modules/map.js
- tests/end2end/playwright/permalink.spec.ts
- tests/end2end/playwright/startup.spec.js
> Reduce ol2 map dependency

- assets/src/modules/config/BaseLayer.js
- tests/qgis-projects/tests/base_layers_user_defined.qgs.cfg
Linked to https://github.com/3liz/lizmap-plugin/pull/574
Funded by 3Liz
> Use `default_background_color_index`

- assets/src/components/NavBar.js
- assets/src/index.js
- assets/src/legacy/map.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/modules/view/templates/map.tpl
- lizmap/www/assets/css/map.css
- tests/js-units/node/state/map.test.js
> Refactor NavBar as a web component and use new Lizmap API

- assets/src/legacy/map.js
- assets/src/legacy/view.js
- assets/src/modules/ExecuteJSFromServer.js
- lizmap/app/responses/AbstractLizmapHtmlResponse.php
- lizmap/app/responses/adminHtmlResponse.class.php
- lizmap/app/responses/adminLoginHtmlResponse.class.php
- lizmap/app/responses/myHtmlMapResponse.class.php
- lizmap/app/responses/myHtmlResponse.class.php
- lizmap/app/responses/simpleHtmlResponse.class.php
- lizmap/modules/action/classes/action.listener.php
- lizmap/modules/dataviz/classes/dataviz.listener.php
- lizmap/modules/filter/classes/filter.listener.php
- lizmap/modules/view/classes/view.listener.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/templates/view.tpl
- phpstan.neon
> Move inline JS scripts

- assets/src/components/Treeview.js
- assets/src/modules/State.js
- assets/src/modules/state/Layer.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/MapLayer.js
- assets/src/modules/state/Symbology.js
- tests/qgis-projects/tests/treeview.qgs
- tests/qgis-projects/tests/treeview.qgs.cfg
Useful in case of rule based symbology with multiple levels.
Funded by [Châteauroux Métropole](https://www.chateauroux-metropole.fr/accueil)
> Handle symbols expanded state

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
> Fix XSS issues into features forms

- assets/package-lock.json
- assets/package.json
- assets/src/legacy/atlas.js
- assets/src/legacy/attributeTable.js
- assets/src/legacy/filter.js
- assets/src/legacy/map.js
- assets/src/modules/Popup.js
- lizmap/www/assets/css/map.css
- tests/end2end/cypress/integration/attribute_table-ghaction.js
- tests/end2end/cypress/integration/key_value_mapping-ghaction.js
- tests/end2end/playwright/xss.spec.js
- tests/qgis-projects/tests/tests_dataset.sql
- tests/qgis-projects/tests/xss.qgs
- tests/qgis-projects/tests/xss.qgs.cfg
> Handle XSS client side

- assets/src/modules/Digitizing.js
> Draw: keep draw visible when closing minidock

- assets/src/dependencies/ol.js
- assets/src/index.js
- tests/end2end/playwright/exposed_dependencies.spec.js
> Expose some ol classes in a library

- assets/src/modules/BaseLayersMap.js
- tests/end2end/cypress/integration/external_wms_layer-ghaction.js
Backport https://github.com/3liz/lizmap-web-client/pull/4380
> [Backport release_3_7] [Bugfix] Use external WMS when activated

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/get_feature_info_style.qgs
- tests/qgis-projects/tests/get_feature_info_style.qgs.cfg
Backport https://github.com/3liz/lizmap-web-client/pull/4368
Authored by: @mind84
> [Backport release_3_7] add STYLE parameter to GetFeatureInfo request

- assets/src/components/MousePosition.js
- assets/src/components/Print.js
- assets/src/components/Treeview.js
- assets/src/dependencies/ol.js
- assets/src/modules/Action.js
- assets/src/modules/Digitizing.js
- assets/src/modules/Geolocation.js
- assets/src/modules/SelectionTool.js
- assets/src/modules/interaction/Draw.js
- assets/src/modules/map.js
* JS Map: Add tool layers in a group
* JS OL: Add Grid module
* JS component TreeView: split templates
> JS factorize some map and treeview code

- assets/src/components/FeatureToolbar.js
- assets/src/components/Print.js
- assets/src/modules/Utils.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- tests/end2end/playwright/print.spec.js
If the serveur does encountered an error during generating print content, an error message is displayed to the user.
> [Bugfix] Display error message on error printing

- assets/src/components/FeatureToolbar.js
- assets/src/components/Print.js
- assets/src/modules/Utils.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- tests/end2end/playwright/print.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4384
> [Backport release_3_7] [Bugfix] Display error message on error printing

- .gitignore
- .gitlab-ci.yml
- assets/src/modules/SelectionTool.js
- assets/webpack.common.js
> lazy load jsts buffer

- tests/end2end/playwright/error-occurred.spec.js
Abort request to test the `error occured` message dispalyed.
> Tests e2e: Test error occured

- assets/src/components/Treeview.js
- assets/src/dependencies/ol.js
* Superseed #4393 
* Partial backport #4391
* Authored by: @rldhont
> [Backport release_3_7] JS factorize some treeview code

- assets/src/legacy/map.js
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/view/templates/popup_all_features_table.tpl
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/webdav-upload.spec.ts
- tests/qgis-projects/tests/popup.qgs
- tests/qgis-projects/tests/popup.qgs.cfg
Fix #3870
Funded by [VSB](https://www.vsb.energy/de/en/homepage/)
> Popup: FeatureToolbar in compact table

- lizmap/www/assets/js/dataviz/dataviz.js
- tests/qgis-projects/tests/dataviz_filtered_in_popup.qgs
- tests/qgis-projects/tests/dataviz_filtered_in_popup.qgs.cfg
@mdouchin this line makes an error in the HTML plot I have added : https://github.com/3liz/lizmap-web-client/commit/cf12831fa477438ab75b1f70d37621dec5e67a4b#diff-e736f3d4588193cb20a1abc33bb3dbcf9b1ba1aed7d96afde0a8e7f2e7381a26R456
> Fix HTML for dataviz filtered in popup

- tests/end2end/cypress/integration/dataviz-ghaction.js
- tests/qgis-projects/tests/dataviz_filtered_in_popup.qgs.cfg
The dataviz of a project has been updated but the tests was not.
It is linked to https://github.com/3liz/lizmap-web-client/pull/4401
> Fix tests e2e cypress dataviz

- lizmap/app/system/mainconfig.ini.php
Bump versions about required server plugin and recommended desktop plugin
> Bump versions about required server plugin and recommended desktop plugin

- lizmap/app/system/mainconfig.ini.php
Upgrade minimum recommended version for Lizmap desktop and server required
> Upgrade minimum recommended version for Lizmap desktop and server required

- tests/end2end/playwright/display_in_layer_tree.spec.js
- tests/end2end/playwright/embedded-relation.spec.ts
- tests/end2end/playwright/filter-layer-by-user.spec.ts
- tests/end2end/playwright/n_to_m_relations.spec.ts
- tests/end2end/playwright/popup.spec.js
- tests/end2end/playwright/singleWMS.spec.ts
- tests/end2end/playwright/snap.spec.ts
- tests/end2end/playwright/treeview.spec.ts
- tests/end2end/playwright/viewport.spec.js
- tests/end2end/playwright/webdav-upload.spec.ts
The playwright `request.postData()` is possibly null so `includes` could not derectly used.
> Tests e2e : playwright request.postData() is possibly null

- tests/end2end/playwright/display_in_layer_tree.spec.js
- tests/end2end/playwright/embedded-relation.spec.ts
- tests/end2end/playwright/filter-layer-by-user.spec.ts
- tests/end2end/playwright/popup.spec.js
- tests/end2end/playwright/treeview.spec.ts
- tests/end2end/playwright/viewport.spec.js
- tests/end2end/playwright/webdav-upload.spec.ts
Backport https://github.com/3liz/lizmap-web-client/issues/4442
> [Backport release_3_7] Tests e2e : playwright request.postData() is possibly null

- assets/src/modules/state/BaseLayer.js
- assets/src/modules/state/Layer.js
- tests/js-units/node/state/baselayer.test.js
Fix regression from https://github.com/3liz/lizmap-web-client/pull/4435
Funded by CC Bièvre Est
> Fix: Group with layers can be used as baselayer

- assets/src/legacy/map.js
- tests/end2end/playwright/popup.spec.js
> Fix popup display in minidock

- tests/end2end/package-lock.json
- tests/end2end/playwright/base-layers.spec.js
Adding tests on base layers projects
> Tests e2e Base layers enhancing

- assets/src/components/Treeview.js
- lizmap/www/assets/css/map.css
> UI: Greyscale symbols when layer is not visible

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
The parameters LEGEND_ON and LEGEND_OFF were not added to GetFeatureInfo parameters.
Funded by EPF Haut De france
> [Bugfix] LEGEND_ON and LEGEND_OFF parameters in GetFeatureInfo 

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4461
> [Backport release_3_7] [Bugfix] LEGEND_ON and LEGEND_OFF parameters in GetFeatureInfo 

- assets/src/components/Treeview.js
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/legend.spec.js
- tests/end2end/playwright/permalink.spec.ts
- tests/qgis-projects/tests/layer_legends.qgs
- tests/qgis-projects/tests/layer_legends.qgs.cfg
Backport https://github.com/3liz/lizmap-web-client/pull/4466
> [Backport release_3_7] [Bugfix] Treeeview symbols not in scale

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
> For admin, check plugin version first, before checking for warnings

- tests/README.md
- tests/end2end/cypress/integration/error_occurred-ghaction.js
- tests/end2end/cypress/integration/external_wms_layer-ghaction.js
- tests/end2end/cypress/support/commands.js
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/globals.js
- tests/qgis-projects/tests/invalid_layer.qgs
- tests/qgis-projects/tests/invalid_layer.qgs.cfg
@nboisteault This kind of helper would have helped me a lot yesterday about #4386 or for @rldhont about #4393
If possible @nboisteault should we use **everywhere** this kind of helper to open a map ?
Sorry, I'm not a JS dev...
I know there is an error about playwright now
> Tests - Add helper to test if the map is OK when opening it

- lizmap/app/system/mainconfig.ini.php
Update QGIS Desktop recommended version
> Update QGIS Desktop recommended version

- tests/end2end/playwright/timemanage.spec.js
- tests/qgis-projects/tests/time_manager.qgs
- tests/qgis-projects/tests/time_manager.qgs.cfg
Bump the time_manager project from 3.16.15 to 3.28.13
> Tests - Update time_manager project

- assets/src/components/Message.js
- assets/src/index.js
- lizmap/www/assets/css/map.css
Example : 
`<lizmap-message message="<h1>Help</h1>Lorem ipsum" type="success" close="true" placement="bottom" allowhtml="true">?</lizmap-message>`
https://github.com/3liz/lizmap-web-client/assets/2145040/38b80157-ef01-4655-93fc-13339e76be67
Funded by [PNR BV](https://www.parc-ballons-vosges.fr/)
> Create `lizmap-message` component

- assets/src/components/BaseLayers.js
- assets/src/legacy/switcher-layers-actions.js
- tests/end2end/playwright/theme.spec.js
- tests/qgis-projects/tests/theme.qgs
- tests/qgis-projects/tests/theme.qgs.cfg
Ref https://github.com/3liz/lizmap-web-client/issues/4501
Funded by 3Liz
> Handle baselayers visibility in theme

- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
Not the best, but better that just a number for now
> Admin - Display the list of warning ID in the admin panel, in the tooltip

- assets/src/dependencies/lit-html.js
- assets/src/dependencies/ol.js
- assets/src/index.js
- assets/src/modules/Lizmap.js
- tests/end2end/playwright/exposed_dependencies.spec.js
> Expose more OL 9 classes and lit-html

- assets/src/legacy/map.js
- assets/src/modules/Popup.js
> Popup: remove remaining OL2 dependencies

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs
- tests/qgis-projects/tests/popup.qgs.cfg
> Popup: respect `popupMaxFeatures` parameter

- assets/src/legacy/map.js
- tests/end2end/playwright/print_in_project_projection.spec.js
Funded by Agglomération Fécamp Caux Littoral
> [Bugfix] Error building GetPrint parameters for empty baselayer

- assets/src/legacy/switcher-layers-actions.js
- assets/src/modules/Config.js
- assets/src/modules/config/Options.js
- assets/src/modules/config/Theme.js
- lizmap/modules/view/controllers/map.classic.php
- tests/end2end/playwright/theme.spec.js
- tests/js-units/node/config.test.js
- tests/js-units/node/config/options.test.js
- tests/js-units/node/config/theme.test.js
Backport https://github.com/3liz/lizmap-web-client/pull/4514
> [Backport release_3_7] [Bugfix] JS config themes

- tests/qgis-projects/tests/dnd_form.qgs
- tests/qgis-projects/tests/dnd_form.qgs.cfg
- tests/qgis-projects/tests/events.qgs
- tests/qgis-projects/tests/events.qgs.cfg
- tests/qgis-projects/tests/form_edition.qgs
- tests/qgis-projects/tests/form_edition.qgs.cfg
- tests/qgis-projects/tests/form_type_relational_value.qgs
- tests/qgis-projects/tests/form_type_relational_value.qgs.cfg
- tests/qgis-projects/tests/startup.qgs
- tests/qgis-projects/tests/startup.qgs.cfg
Tests - Upgrade CFG which were on LWC 3.5 to 3.7 and QGIS 3.28
> Tests - Upgrade CFG which were on LWC 3.5 to 3.7 and QGIS 3.28

- assets/src/legacy/map.js
- assets/src/modules/Permalink.js
- lizmap/modules/view/templates/map_projects.tpl
- lizmap/modules/view/templates/view.tpl
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/permalink.spec.js
> [Backport release_3_7] [Bugfix] Still support bbox parameter

- assets/src/modules/Permalink.js
- assets/src/modules/config/Options.js
- tests/end2end/playwright/permalink.spec.js
- tests/js-units/node/config/options.test.js
> [Backport release_3_7] New option to disable the automatic permalink

- assets/src/modules/config/Options.js
- tests/end2end/playwright/theme.spec.js
- tests/js-units/node/config/options.test.js
After https://github.com/3liz/lizmap-web-client/pull/4586 that added `automatic_permalink` option the default value will be false.
> Automatic permalink will be disabled by default

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/attributions.spec.js
- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/base-layers.spec.js
- tests/end2end/playwright/display_in_layer_tree.spec.js
- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/embed.spec.js
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/exposed_dependencies.spec.js
- tests/end2end/playwright/form_relational_value.spec.js
- tests/end2end/playwright/legend.spec.js
- tests/end2end/playwright/permalink.spec.js
- tests/end2end/playwright/popup.spec.js
- tests/end2end/playwright/print.spec.js
- tests/end2end/playwright/print_in_project_projection.spec.js
- tests/end2end/playwright/project_load_warning.spec.js
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/startup.spec.js
- tests/end2end/playwright/theme.spec.js
- tests/end2end/playwright/timemanage.spec.js
- tests/end2end/playwright/viewport.spec.js
- tests/end2end/playwright/wmts.spec.js
- tests/end2end/playwright/xss.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4605
> [Backport release_3_7] Tests e2e playwright: replace require par import ... from

- tests/README.md
- tests/end2end/playwright/auth.setup.ts
> [Backport release_3_7] Tests - Do not hardcode localhost URL in tests

- assets/src/legacy/attributeTable.js
- assets/src/legacy/map.js
- tests/end2end/playwright/attribute-table.spec.js
- tests/qgis-projects/tests/attribute_table.qgs
- tests/qgis-projects/tests/attribute_table.qgs.cfg
> Fix: update `refresh data` button and fix export

- assets/src/modules/map.js
- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/base-layers.spec.js
By enhancing base layers e2e playwright tests for https://github.com/3liz/lizmap-web-client/pull/4633, a bug in XYZ Grid Tile has been found and fixed.
> Fix JS XYZ Grid Tile and Tests e2e playwrigth: enhancing base layers tests 

- lizmap/modules/lizmap/lib/Project/QgisProject.php
In some project the WMS Extent property of the project is empty.
Funded by SETEC
> Fix Project properties WMS Extent empty

- tests/end2end/cypress/integration/attribute_table-ghaction.js
- tests/qgis-projects/tests/attribute_table.qgs
- tests/qgis-projects/tests/attribute_table.qgs.cfg
Update attribute table project and e2e test to check table column order based on QGIS attribute table config.
> Tests : Attribute Table config

- tests/docker-conf/phpfpm/lizmapConfig.ini.php
- tests/docker-conf/phpfpm/localconfig.ini.php
- tests/end2end/playwright/localonly/map-projects-switcher.spec.js
- tests/end2end/playwright/map-projects-switcher.spec.js
Continuous Integration of Tests e2e playwright: Map projects switcher
> CI Tests e2e playwright: Map projects switcher

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs.cfg
> [Backport release_3_7] Fix: Enable popup when digitizing is disabled

- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Log/ConfigTest.php
- tests/units/classes/Log/ItemTest.php
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Request/OGCRequestTest.php
- tests/units/classes/Request/ProxyTest.php
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/classes/Request/WMTSRequestTest.php
- tests/units/classes/lizmapRepositoryTest.php
- tests/units/classes/lizmapServicesTest.php
Fix phpunit deprecation warnings on phpunit 10, (see  https://github.com/3liz/lizmap-web-client/pull/4679)
> Php unit 10 compatibility

- .github/workflows/tests.yml
- Makefile
- tests/units/composer.json
Linked to https://github.com/3liz/lizmap-web-client/pull/4675
> Tests - Update phpunit version

- .github/workflows/tests.yml
- Makefile
> Backport - Update the version of PHPUnit on GH Action

- lizmap/modules/lizmap/lib/Project/Project.php
Trying to add a small helper to avoid writing twice the key.
> PHP - Add helper for property_exists

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
People are wondering what is this date and some were thinking the date was wrong
> Admin panel - Update of string

- .github/workflows/tests.yml
- tests/units/composer.json
> Bump PHP unit to 11.3.1

- assets/src/legacy/map.js
Funded by Villefranche Agglomération
> [Bugfix] lizMap.getFeaturePopupContentByFeatureIntersection choosing scale

- assets/src/components/Digitizing.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
> Fix digitizing dropdown after BS5 upgrade

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
Backport https://github.com/3liz/lizmap-web-client/pull/4737
Authored by: @ppetru
> [Backport release_3_8] Try harder to find layers when deciding whether to cache them or not.

- lizmap/modules/admin/locales/en_US/jacl2.UTF-8.properties
For now, only vector layers can be downloaded
Ref #4741 #46
CC @katagen
> UX - Be more explicit about downloading vector files layers only

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
Backport https://github.com/3liz/lizmap-web-client/pull/4737
Authored by: @ppetru
> [Backport release_3_7] Try harder to find layers when deciding whether to cache them or not.

- lizmap/www/assets/jelix/js/jforms/password-editor.js
@laurentj @nworr I have this file modified on my master branch, after launching the docker stack.
Not sure about backports ?
> Update Jelix file about password

- assets/src/components/FeatureToolbar.js
Follow this PR https://github.com/3liz/lizmap-web-client/pull/4752
Linked to https://github.com/3liz/lizmap-web-client/pull/4768 and https://github.com/3liz/lizmap-web-client/pull/4635
> Bootstrap 5 tooltip on FeatureToolbar component

- assets/src/legacy/map.js
- lizmap/modules/view/controllers/lizAjax.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
count user js script and display message if js exception and user is kind of admin
Funded by 3Liz
> Backport 3.7 : Count user defined js , adapt message when js exception

- assets/src/components/Digitizing.js
- assets/src/components/FeatureToolbar.js
- assets/src/components/SelectionTool.js
- assets/src/legacy/attributeTable.js
Fix opening some dropdown menus after BS5 merge
Ticket : #
Funded by
> Fix BS5 dropdown opening

- .gitignore
- tests/docker-conf/phpfpm/lizmapConfig.ini.php
- tests/end2end/playwright/globals.js
> Tests - Improve Playwright helper to load a project with error

- .gitignore
- assets/src/legacy/map.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/globals.js
- tests/qgis-projects/tests/javascript_error.qgs
- tests/qgis-projects/tests/javascript_error.qgs.cfg
- tests/qgis-projects/tests/media/js/javascript_error/invalid_javascript.js
Follow up from #4776 
This test project was not used for loading the map, only on the landing page. I just added a layer in the project, to not have an empty tree view.
But the E2E test was expecting to have an empty tree view if there is an error (because we did only some fake 500 error on GetCapabilities @rldhont ?)
**Not an administrator**
**As administrator**
> Tests - Add E2E test about user defined JavaScript warning

- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/playwright/server-information.spec.js
> fix typo, improve html for module view

- tests/qgis-projects/tests/lizmap_features_table.qgs
- tests/qgis-projects/tests/print_in_project_projection.qgs
This project was using old ign.fr URL
> Tests - Change URL to data.geopf.fr

- tests/end2end/playwright/media.spec.js
I'm missing how to click the button for now in the attribute table
> Tests - Move a minor tests from manual to playwright

- assets/src/legacy/switcher-layers-actions.js
> Fix: base layer (i) information - stop working

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/end2end/playwright/embedded-form.spec.js
Backport #4847
**Authored by:** @mind84
> [Backport release_3_8] [Bug] Add embedded layers to keyValueConfig object

- tests/end2end/playwright/timemanage.spec.js
Force syncing and add explicit message for checing GteMap url parameters
> Tests e2e Timemanager: Enhancing

- lizmap/modules/lizmap/lib/Request/Proxy.php
- tests/end2end/playwright/timemanage.spec.js
Thanks to Torleif Berger for it's code for Tail tackling large files in PHP http://www.geekality.net/?p=1654
> Tests: tail proxylog to manage big file

- assets/src/modules/Search.js
- lizmap/modules/lizmap/controllers/osm.classic.php
> Update osm search

- lizmap/modules/lizmap/lib/Project/QgisProject.php
Linked to https://github.com/3liz/lizmap-web-client/issues/2058
> Remove some code related to QGIS < 3.0

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/location_search.spec.js
Testing that search is well activated.
> Tests e2e Playwright: Added Location seach

- tests/qgis-projects/tests/external_wms_layer.qgs
- tests/qgis-projects/tests/external_wms_layer.qgs.cfg
Linked to #4909
Just addind the WFS layer in the project to see if it works.
> Tests - Add WFS external layer in the test project

- assets/src/modules/Tooltip.js
> JS - Increase console logging from debug to warn for an "error" message, not blocking

- tests/end2end/playwright/tooltip.spec.js
- tests/qgis-projects/tests/tooltip.qgs
- tests/qgis-projects/tests/tooltip.qgs.cfg
> Tests - Add a quick test about tooltip

- tests/qgis-projects/tests/attribute_table.qgs
- tests/qgis-projects/tests/attribute_table.qgs.cfg
> Tests - Add some relations in the attribute_table project

- lizmap/modules/lizmap/lib/Server/Server.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
Include git commit into JSON metadata
> Include git commit into JSON metadata

- assets/src/legacy/map.js
- assets/src/modules/Popup.js
- assets/src/modules/Utils.js
- tests/end2end/playwright/xss.spec.js
- tests/qgis-projects/tests/xss.qgs.cfg
> XSS: sanitize more GFI content

- assets/src/components/FeatureToolbar.js
> [Bugfix] Feature toolbar: child layer is pivot

- lizmap/www/assets/jelix/js/jforms/password-editor.js
Update Jelix file modified when building LWC
I'm not sure to which branch it must be backported.
> Update Jelix file modified when building LWC

- assets/src/components/FeaturesTable.js
- assets/src/components/Print.js
- assets/src/legacy/map.js
- assets/src/modules/Action.js
- assets/src/modules/FeaturesTable.js
- assets/src/modules/config/Layer.js
- assets/src/modules/config/LayerTree.js
- assets/src/modules/utils/Enums.js
- lizmap/www/assets/js/dataviz/dataviz.js
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/embed.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/google-basemap.spec.js
- tests/end2end/playwright/media.spec.js
I tried Jetbrains Aqua and Jetbrains Webstorm, and I was checking some random warnings I got from the IDE.
I can give more try later, it was just to have a quick overview for now : grammar (French and English), `var`, and many other warnings that I didn't want to touch for now.
It also supports Cypress and Playwright
CC @rldhont @mdouchin  @nboisteault @mind84 @nworr
> Fix typo and JS lint

- lizmap/modules/lizmap/lib/Request/Proxy.php
@rldhont As seen with a use case today
I just tried with a `GetPrintAtlas` request by triggering a wrong layer name.
> Admin - See if an HTTP error occurred

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/opacity.qgs
- tests/units/classes/Project/Ressources/opacity_embed.qgs
- tests/units/classes/Project/Ressources/opacity_embed.qgs.cfg
- tests/units/classes/Project/Ressources/opacity_source.qgs
- tests/units/classes/Project/Ressources/opacity_source.qgs.cfg
> include layer opacity info for embedded layers

- .php-cs-fixer.dist.php
- lizmap/modules/action/classes/action.listener.php
- lizmap/modules/action/classes/actionConfig.class.php
- lizmap/modules/action/classes/actionDockable.listener.php
- lizmap/modules/action/controllers/service.classic.php
- lizmap/modules/action/install/install.php
- lizmap/modules/action/install/upgrade.php
- lizmap/modules/filter/classes/filterDatasource.class.php
- lizmap/modules/filter/controllers/service.classic.php
- lizmap/modules/filter/install/install.php
- lizmap/modules/filter/install/upgrade.php
Will be manually backported to active branch
> Add missing modules action and filter in PHP-CS-Fixer config

- assets/src/components/Digitizing.js
- assets/src/modules/Digitizing.js
Backport https://github.com/3liz/lizmap-web-client/pull/5012
**Authored by:** @neo-garaix
> [Backport release_3_9] Export FlatGeobuf

- assets/src/modules/Legend.js
- assets/src/modules/Lizmap.js
> Reduce mainLizmap dependencies in Legend module

- assets/src/modules/Edition.js
- assets/src/modules/Lizmap.js
_Based on #3857_  
Funded by 3liz
> Reduce mainLizmap dependencies in Edition module

- assets/src/modules/FeaturesTable.js
- assets/src/modules/Lizmap.js
> Reduce mainLizmap dependencies in FeaturesTable  module

- lizmap/.stylelintrc.json
- lizmap/www/themes/default/css/admin.css
- lizmap/www/themes/default/css/embed.css
- lizmap/www/themes/default/css/main.css
- lizmap/www/themes/default/css/map.css
- lizmap/www/themes/default/css/media.css
- lizmap/www/themes/default/css/view.css
Introduce https://stylelint.io/ for checking CSS files.
These were just automatically fixed by the tool. I had to disable a few `"rules"` for now in the configuration file.
I'm happy to discuss these with CSS maintainers.
This is part of an going effort "basic" checks on files (PHP, JS...)
> Lint - Introduce stylelint for CSS files

- lizmap/modules/action/install/install.php
- lizmap/modules/filter/classes/filterDockable.listener.php
> Fix PHP-CS-Fixer on master, due to recent merge

- assets/src/modules/Geolocation.js
- assets/src/modules/Lizmap.js
> Reduce mainLizmap dependencies in Geolocation module

- tests/end2end/playwright/filter-layer-by-user.spec.js
Tests WFS GetFeature requests with Filter layer data by user.
> [Tests] e2e Filter layer data by user - WFS GetFeature

- tests/end2end/playwright/globals.js
Playwright - Fix some warnings about docstrings and parameters from the JavaScript IDE
> Playwright - Fix some warnings about docstrings and parameters from the JavaScript IDE

- tests/end2end/playwright/globals.js
> [Backport release_3_7] Playwright - Fix some warnings about docstrings from the JavaScript IDE

- assets/package-lock.json
The package-lock.json was forgotten in #5010 
cc @Gustry 
Funded by 3liz
> Update package lock json with FlatGeobuf

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
Backport from #5066
It doesn't contain the new translated string as it's not in 3.7.
> [Backport release_3_7] Admin - Log OGC request if error #5066

- lizmap/modules/admin/classes/listProjectDatasource.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/lib/Project/ProjectMainData.php
- lizmap/modules/lizmap/lib/Project/Repository.php
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/zones/ajax_view.zone.php
- lizmap/modules/view/zones/main_view.zone.php
- tests/units/classes/Project/ProjectMainDataTest.php
Adding a class to get only project main data for main view
> Speed up main view with project main data

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
> [Bugfix] Fix null xml QgisProject property during projects loading

- assets/src/components/FeaturesTable.js
- assets/src/modules/FeaturesTable.js
- lizmap/modules/lizmap/controllers/features.classic.php
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/lizmap-features-table.spec.js
Backport #5013 
**Authored by:** @neo-garaix @mdouchin  
Funded by 3liz
> [Backport release_3_9] FeaturesTable structure & columns improvements

- lizmap/modules/lizmap/lib/Project/ProjectMainData.php
Abstract has to be a string
```
[8192] strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated
/srv/lzm/temp/lizmap/www/compiled/templates/modules/view/view_html_t_15.php 41
/index.php/view/
array (   \'module\' => \'view\',   \'action\' => \'default:index\', )
ref:Unknown referer
0 strip_tags() /srv/lzm/temp/lizmap/www/compiled/templates/modules/view/view_html_t_15.php : 41
1 template_97ecf81651077e876942eb1c8b4df3b8() /srv/lzm/lizmap/vendor/jelix/castor/lib/Castor/CastorCore.php : 290
2 Jelix\\Castor\\CastorCore->_fetch() /srv/lzm/lizmap/vendor/jelix/jelix/lib/jelix/tpl/jTpl.class.php : 181
3 jTpl->fetch() /srv/lzm/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.class.php : 287
4 jZone->_createContent()\t/srv/lzm/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.c …
```
> [Bugfix] Project abstract has to be a string for nl2br and strip_tags

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
Manual backport of https://github.com/3liz/lizmap-web-client/pull/5079
Funded by Etra
> [Feature] Circular geometry measurement on draw

- assets/src/legacy/attributeTable.js
Backport #5100
**Authored by:** @mdouchin
> [Backport release_3_9] Attribute table - Fix some misbehaviours

- assets/src/modules/Digitizing.js
https://github.com/user-attachments/assets/beb60a70-e966-479e-ba11-59a14c393024
Funded by 3Liz
> Draw: add translate interaction active by default

- assets/src/modules/Popup.js
- tests/end2end/playwright/layer_order.spec.js
- tests/qgis-projects/tests/layer_order.qgs
- tests/qgis-projects/tests/layer_order.qgs.cfg
Ticket : 3249 (paid support)
Funded by 3Liz, Biotope
> Fix: order popups following layers order

- assets/src/components/FeaturesTable.js
Ticket : #5146
- Optionally show the currently highlighted feature geometry in the map with a new optional attribute `data-show-highlighted-feature-geometry="true"`
- Optionally centre the map to this geometry with a new optional attribute `data-center-to-highlighted-feature-geometry="true"`
[Capture vidéo du 2025-01-02 14-07-23.webm](https://github.com/user-attachments/assets/9fd7fa2b-cffc-45dc-ba02-bea89ac5b8b8)
Funded by 3Liz
> Features table geometry additions

- .github/workflows/tests.yml
Update Github Action PHPUnit Matrix.
PHPUnit version has been updated and PHP 7.4 version added.
> Github Action PHPUnit Matrix update

- .github/workflows/tests.yml
> [Backport release_3_8] Github Action PHPUnit Matrix update

- .github/workflows/php-stan.yml
> [Backport release_3_8] Github Action PHPStan Matrix

- .github/workflows/php-stan.yml
> [Backport release_3_7] Github Action PHPStan Matrix

- .github/workflows/tests.yml
> [Backport release_3_7] Github Action PHPUnit Matrix update

- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
> Tests with PHP 8.4

- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
> [Backport release_3_8] Tests with PHP 8.4

- lizmap/modules/lizmap/lib/Project/QgisProject.php
> improve setLayerOpacity : split embedded and normal layer search with xpath

- .github/workflows/e2e_tests.yml
> Backport the work on CI GH Action about E2E, about logs

- .gitlab-ci.yml
- tests/docker-compose.yml
Minor changes from #5168, which were not strictly related to QJazz
> Docker updates about mount

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/media.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/pages/project.ts
- tests/end2end/playwright/project_load_warning.spec.js
- tests/end2end/playwright/snap.spec.js
> Tests - Start Page Object Model for Playwright

- tests/docker-conf/phpfpm/lizmapConfig.ini.php
CC @nboisteault @rldhont @nworr @mdouchin @rldhont
> Tests - Add a private repository

- tests/end2end/playwright/bad-repository.spec.js
- tests/end2end/playwright/landing_page_config.spec.js
- tests/end2end/playwright/maps-management.spec.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/homepage.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/server-information.spec.js
> [Backport 3.9] Tests - Extends base class for testing admin pages and landing page

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/timemanage.spec.js
> [Backport release_3_7] Tests e2e Playwright: Defined global getEchoRequestParams

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/ProxyResponse.php
- tests/end2end/cypress/integration/cmdline-wmts-ghaction.js
- tests/end2end/cypress/integration/requests-wfs-ghaction.js
- tests/end2end/cypress/support/function.js
- tests/end2end/cypress/support/index.js
- tests/units/classes/Request/ProxyResponseTest.php
- tests/units/classes/Request/ProxyTest.php
> [Backport release_3_7] Add X-Request-Id in request to QGIS Server headers

- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- assets/src/modules/LocateByLayer.js
- assets/src/modules/Snapping.js
- assets/src/modules/Tooltip.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
Backport https://github.com/3liz/lizmap-web-client/pull/3857
> [Backport release_3_9] [JavaScript] reduce mainLizmap dependencies

- assets/src/modules/SelectionTool.js
> Refacto: avoid duplication of code in selectionTool

- assets/src/modules/Digitizing.js
Use map's projection
Funded by 3Liz
> Fix: wrong distance constraint value

- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/lib/Server/Server.php
> API - Add a method to retrieve the QGIS Lizmap server endpoint URL

- .github/workflows/docs.yml
Follow up from #5270 and fe4a917bc20ffebe0d9869efb940563a51a9fa8a
> JSDoc - Try to forward the version number in the workflow

- .github/workflows/docs.yml
- .gitignore
- docs/index.html
> Fix again path in GH Action about docs

- assets/src/modules/Digitizing.js
> [Backport release_3_7] Fix: wrong distance constraint value

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/homepage.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/requests-metadata.spec.js
> Tests e2e playwright : Lint tests and POM

- .github/workflows/cron_e2e.yml
- tests/Makefile
- tests/end2end/cypress.json
- tests/end2end/playwright.config.ts
- tests/end2end/playwright/xss.spec.js
- tests/lizmap-ctl
- tests/qgis-projects/tests/tests_dataset.sql
GH Action - Follow up about previous commits on the E2E matrix
> GH Action - Follow up about previous commits on the E2E matrix

- .github/workflows/e2e_tests.yml
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/landing_page_config.spec.js
- tests/end2end/playwright/mock/README.md
- tests/end2end/playwright/print_in_project_projection.spec.js
Tests - Make flaky tests failing
> Tests - Make flaky tests failing

- .github/workflows/e2e_tests.yml
- assets/src/modules/Snapping.js
- eslint.config.mjs
- tests/end2end/othersite/main.js
Backport from #5357 
As #5334 is not backported, this will not as well
> GH Action - Add workflow check concurrency, eslint only in assets/src for now

- .github/workflows/php-stan.yml
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
- phpstan-baseline.neon
- phpstan-ci.neon
- phpstan.neon
- tests/units/composer.json
Manually backport some changes of https://github.com/3liz/lizmap-web-client/pull/4888
Authored by @laurentj
> [Release 3_8] Upgrade phpstan

- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/base-layers.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/mock/README.md
- tests/end2end/playwright/print_in_project_projection.spec.js
- tests/end2end/playwright/webdav-upload.spec.js
> Tests - Small helper to have a file path in Playwright

- .github/workflows/e2e_tests.yml
- tests/end2end/playwright/auth.setup.ts
Review E2E setup about tags and timeout on login page
> Review E2E setup about tags and timeout on login page

- tests/end2end/playwright/auth.setup.ts
- tests/end2end/playwright/globals.js
Tests - Wait for the main web page to be HTTP 200
> Tests - Wait for the main web page to be HTTP 200

- tests/end2end/cypress/integration/projects_homepage-ghaction.js
- tests/end2end/playwright/landing_page_config.spec.js
- tests/end2end/playwright/pages/homepage.js
- tests/qgis-projects/tests/project_acl.qgs
- tests/qgis-projects/tests/project_acl.qgs.cfg
Tests - Fix project home page cypress, moving to playwright
> Tests - Fix project home page cypress, moving to playwright

- tests/end2end/playwright/requests-dataviz-api.spec.js
Tests - Fix flaky about dataviz API, checking members only
> Tests - Fix flaky about dataviz API, checking members only

- .github/workflows/e2e_tests.yml
- tests/end2end/playwright.config.ts
- tests/end2end/playwright/print.spec.js
> Improve E2E tests reports

- assets/src/components/SelectionInvert.js
Try to update a five years old custom element
Linked to https://github.com/3liz/lizmap-web-client/pull/5375 to have ESLint with limit lines to less than 400 why not 125 !
> Refactoring lizmap-selection-invert

- assets/src/components/SelectionInvert.js
> [Backport release_3_9] Refactoring lizmap-selection-invert

- assets/src/modules/Utils.js
- tests/end2end/playwright/xss.spec.js
- tests/qgis-projects/tests/xss.qgs.cfg
Ticket : fix #4863
Funded by Valabre
> Fix: sandbox all iframes except those from the same origin

- assets/src/modules/Digitizing.js
- eslint.config.mjs
- tests/end2end/playwright/print.spec.js
Follow up from #5362
* Decrease to 350
* Fix regression from #5362 about these new variables I have added (and already backported in 3.9 in #5371)
> ESLint - Limit lines to 350

- assets/src/components/SelectionTool.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
> [Backport release_3_9] Refactoring lizmap-selection-tool

- assets/src/components/FeatureToolbar.js
- assets/src/components/Print.js
- assets/src/components/Treeview.js
- assets/src/legacy/map.js
- assets/src/modules/Digitizing.js
- assets/src/modules/FeaturesTable.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Popup.js
- assets/src/modules/Utils.js
- assets/src/modules/WFS.js
- assets/src/modules/WMS.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
- tests/js-units/node/utils.test.js
Cherry-pick from @Antoviscomi in #5411
@rldhont As discussed
> Javascript - Refactoring about Utils.js

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- tests/units/classes/lizmapWktTest.php
The regexp to check coords was not complete.
Linked to PR https://github.com/3liz/lizmap-web-client/pull/5368
Fixed https://github.com/3liz/lizmap-web-client/issues/5417
> [Bugfix] PHP Lizmap WKT utils - check coords

- .github/workflows/e2e_tests.yml
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/print.spec.js
> Tests - Improve debug when the length is not the same

- assets/src/components/FeatureToolbar.js
- assets/src/components/Geolocation.js
- assets/src/components/Snapping.js
- eslint.config.mjs
ESLint to 290 line length
Similar to #5420, just splitting lines.
> ESLint to 290 line length

- assets/src/components/Digitizing.js
> [Backport release_3_9] Refactoring - Review Digitizing.js to split attributes in HTML

- assets/src/components/FeatureToolbar.js
- assets/src/components/Geolocation.js
- assets/src/components/Snapping.js
- eslint.config.mjs
Totally manual backport of #5455, by splitting lines again
> [Backport] Max line length to 290 in JS

- assets/src/modules/Digitizing.js
> [Fix] Distance constraint in the measure tool is not correctly interpreted in the map

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/project_load_warning.spec.js
Tests - Skip Lizmap warning when loading the map about outdated CFG if needed in tests
> Tests - Skip Lizmap warning when loading the map about outdated CFG if needed in tests

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/project_load_warning.spec.js
> [Backport] Tests - Skip Lizmap warning when loading the map about outdated CFG if needed in tests

- package-lock.json
- package.json
Related to #5495 #5496 #5497 #5498
> Update some versions in package.json again

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- tests/end2end/playwright/axis_orientation.spec.js
- tests/units/classes/Form/QgisFormTest.php
> [Backport release_3_8] [Fix] QGIS constraint with geometry 

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
> Always log in the console in case of warnings, display a message for GIS for invalid layers in CFG

- lizmap/modules/lizmap/templates/user_menu.tpl
- tests/end2end/playwright/header.spec.js
- tests/qgis-projects/tests/set_tests_respository_rights.sql
> [Backport] Header - Add authenticated user organization in hidden fields

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
- tests/end2end/playwright/requests-metadata.spec.js
> Admin - Display if the installation is not complete according to versions in installed modules

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
Console - Add the number of warnings
> Console - Add the number of warnings

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/project_load_warning.spec.js
- tests/qgis-projects/tests/project_cfg_warnings.qgs
- tests/qgis-projects/tests/project_cfg_warnings.qgs.cfg
> Tests - Do not display a warning about outdated QGIS plugin version in tests when required, needed for checking warnings about layers

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/pages/drawpage.js
- tests/end2end/playwright/pages/project.js
Manual backport of https://github.com/3liz/lizmap-web-client/pull/5544
Funded by Etra
> [Backport release_3_8][Bugfix] Wrong measure when both angle and dimension constraints are set on drawing tool

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/pages/drawpage.js
- tests/end2end/playwright/pages/project.js
Manual backport of https://github.com/3liz/lizmap-web-client/pull/5544
Funded by Etra
> [Backport release_3_9][Bugfix] Wrong measure when both angle and dimension constraints are set on drawing tool

- lizmap/app/responses/myHtmlMapResponse.class.php
- lizmap/app/responses/myHtmlResponse.class.php
- lizmap/modules/admin/forms/config_services.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/config.tpl
- lizmap/modules/admin/templates/config_services.tpl
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/templates/main.tpl
- lizmap/modules/view/templates/map.tpl
Not tested, just a nearly a search and replace.
I have can see a POST request sent, but as I'm on `localhost:8130`, it fails on the Google side
Related to #2355 #2836
> feat: Support Google Tag instead of the old Analytics

- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
Fix a possible issue again from #5478 
A partial fix was done in #5536
> Admin - drop the last part of version when comparing to modules as well

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
> Fix typo in WMSRequest.php

- lizmap/modules/view/templates/map_edition.tpl
- lizmap/www/assets/js/dataviz/dataviz.js
> Update progress bar to Bootstrap 5

- assets/src/modules/state/MapLayer.js
- tests/end2end/playwright/lizmap-features-table.spec.js
- tests/end2end/playwright/pages/project.js
- tests/qgis-projects/tests/lizmap_features_table.qgs
There will be a follow up soon related to `lizmap-features-table` regarding https://github.com/3liz/qgis-lizmap-server-plugin/pull/109
> Tests - Quick review about E2E lizmap-features-table

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
> Admin - Move the drop commit ID into the modules checker class, because it is needed twice

- lizmap/www/assets/css/map.css
- lizmap/www/themes/default/css/map.css
Backport #5571 
from @mdouchin 
Funded by Destination Bretagne Sud Golfe du Morbihan
> [Backport master] Popup - Improve styling of drag-and-drop designed popups

- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/homepage.js
- tests/end2end/playwright/pages/project.js
Jelix provides a debugbar, which displays every error messages and their details,
and also many other informations: session data, sql queries etc. Each of these
informations are provided by plugins.
To learn more about the Jelix debug bar https://docs.jelix.org/en/manual/dev-tools/debugging#the-debug-bar
> Tests e2e Playwright: Add accessor to Jelix's DebugBar

- lizmap/app/system/api/auth.coord.ini.php
- lizmap/app/system/api/config.ini.php
- lizmap/app/system/mainconfig.ini.php
- lizmap/app/system/urls.xml
- lizmap/modules/admin/controllers/maps.classic.php
- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
- lizmap/modules/admin/lib/RepositoryRightsService.php
- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rest.classic.php
- lizmap/modules/admin_api/install/configure.php
- lizmap/modules/admin_api/install/install.php
- lizmap/modules/admin_api/lib/Credentials.php
- lizmap/modules/admin_api/lib/Error.php
- lizmap/modules/admin_api/lib/RestApiCtrl.php
- lizmap/modules/admin_api/lib/Utils.php
- lizmap/modules/admin_api/module.xml
- lizmap/modules/admin_api/urls.xml
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/App/Checker.php
- lizmap/www/api.php
- tests/Makefile
- tests/README.md
- tests/api/openapi.yaml
- tests/docker-compose.yml
- tests/docker-conf/nginx-default.conf
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-metadata.spec.js
Backport #5486
From @neo-garaix
> [Backport release_3_8] REST API for projects

- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/homepage.js
- tests/end2end/playwright/pages/project.js
> [Backport release_3_8] Tests e2e Playwright: Add accessor to Jelix's DebugBar

- tests/end2end/playwright/atlas.spec.js
- tests/end2end/playwright/pages/atlaspage.js
- tests/end2end/playwright/pages/project.js
- tests/qgis-projects/tests/atlas_2154.qgs
- tests/qgis-projects/tests/atlas_2154.qgs.cfg
Manually backport e2e tests from #5588
Funded by WPD Onshore France
> [Backport release_3_8] Tests e2e Playwright: Lizmap atlas feature

- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/embedded-relation.spec.js
- tests/end2end/playwright/n_to_m_relations.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/webdav-upload.spec.js
Backport #5610
**Authored by:** @mind84
> [Backport release_3_9] [Test] Refactoring e2e tests due to popup html changes

- docker/lizmapConfig.ini.php.dist
- lizmap/modules/lizmap/install/config/lizmapConfig.ini.php
- lizmap/var/config/lizmapConfig.ini.php.dist
- tests/docker-conf/phpfpm/lizmapConfig.ini.php
While I was reviewing https://github.com/3liz/lizmap-documentation/pull/272
> Docs - Update documentation about wmsServerURL

- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/controllers/searchFts.classic.php
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/location_search.spec.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-metadata.spec.js
> [backport release_3_8] Small refactoring about Lizmap search, return correct HTTP code

- assets/src/legacy/map.js
- assets/src/modules/config/Layer.js
- assets/src/modules/state/Layer.js
- tests/end2end/playwright/popup.spec.js
Linked to https://github.com/3liz/lizmap-plugin/pull/626
The lizmap publisher can choose how to display children in popup :
* as GetFeatureInfo content
* as lizmap-features-table element
> Feature: Enable lizmap-features-table for children in popup

- tests/end2end/playwright/popup.spec.js
Manually backporting tests e2e playwright enhancement from https://github.com/3liz/lizmap-web-client/pull/5640
> Tests e2e playwright: enhancing popups for release_3_8

- lizmap/modules/admin/forms/config_services.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
UX - Add tooltip on the project switcher
> UX - Add tooltip on the project switcher

- assets/src/legacy/map.js
- tests/end2end/playwright/popup.spec.js
> [Backport release_3_8] Fix UI regression: Clear popup geometry

- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/api/openapi.yaml
- tests/end2end/playwright/requests-api.spec.js
Follow up from previous PR https://github.com/3liz/lizmap-web-client/pull/5486
Original commit from @neo-garaix in #5589
Add more information in the GET request
If I'm not wrong, the backport will need to be updated in 3.8.
> API: GET info on project

- lizmap/modules/admin_api/controllers/repository_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rights_rest.classic.php
- lizmap/modules/admin_api/lib/Error.php
- lizmap/modules/admin_api/lib/Utils.php
- lizmap/modules/admin_api/urls.xml
- tests/api/openapi.yaml
* **Creation** of repositories with a **POST** request on `/admin/repositories/{repository_key}`
* Using a `label` _query_ parameter
* Using a `path` _query_ parameter
* **Edition** of groups rights on repositories with a **POST** request on `/admin/right/{method}/{repository_key}`
* Using a `method` _path_ parameter that stands for `add` or `remove`
* Using a `group` _query_ parameter for groups IDs
* Using a `right` _query_ parameter for rights (like `lizmap.tools.edition.use`)
* Multiple **Errors code** added
* Updated Swagger
Funded by 3Liz
> API: POST repository (create & edit)

- Makefile
- assets/src/components/FeaturesTable.js
- assets/src/modules/FeaturesTable.js
- docs/jsdoc.json
- docs/jsdoc.md
- package.json
> Docs - Review JSDoc about Lizmap-Features-Table, deprecated events

- Makefile
- assets/src/components/FeaturesTable.js
- assets/src/modules/FeaturesTable.js
- docs/jsdoc.json
- docs/jsdoc.md
> [Backport release-3_8] Docs - Review JSDoc about Lizmap-Features-Table

- assets/src/legacy/attributeTable.js
When attribute table has to format a big table, the interface can freeze. The freeze has been introduced by DOMPurify which format text as a XSS sanitizer.
Funded by Agence des 50 pas de Guadeloupe, Cartophyl, FM Projet
> [Release_3_8] JS Attribte Table: format big data

- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/lizmap/lib/App/VersionTools.php
- tests/api/openapi.yaml
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/print.spec.js
- tests/units/classes/App/VersionToolsTest.php
> [Backport release-3_9] Fix tests in print when the project has been updated

- assets/src/components/Digitizing.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/pages/drawpage.js
Some little changes in component Digitizing and Draw e2e tests enhancements.
> JS component digitizing and Draw e2e tests

- assets/src/components/Digitizing.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/pages/drawpage.js
- tests/end2end/playwright/popup.spec.js
> [Backport release_3_9] JS component digitizing and Draw e2e tests

- assets/src/modules/state/Map.js
Try to provide a right documentation for Lizmap events.
Linked to https://github.com/3liz/lizmap-web-client/pull/5689 https://github.com/3liz/lizmap-web-client/pull/5665
> Docs - Trying to improve jsdoc event for MapState

- assets/src/components/FeaturesTable.js
Enhancing https://github.com/3liz/lizmap-web-client/pull/5677 to keep event type.
> Docs - Trying to improve jsdoc event for lizmap-features-table without deprecation

- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- lizmap/modules/view/templates/view.tpl
> Remove BBOX and proj name from project info

- assets/src/components/ActionSelector.js
- assets/src/components/Digitizing.js
- assets/src/modules/Action.js
- assets/src/modules/Digitizing.js
- assets/src/modules/SelectionTool.js
- lizmap/modules/view/templates/map_draw.tpl
- tests/end2end/playwright/draw.spec.js
* Digitizing module: Is digitizing simple geometry ?
* JS Selection tool: digitizing simple geometry
* JS Digitizing component: simplify UI if only one tool available
> JS Digitizing - enhancing module, component and the way to use them

- assets/src/components/ActionSelector.js
- assets/src/components/Digitizing.js
- assets/src/modules/Action.js
- assets/src/modules/Digitizing.js
- assets/src/modules/SelectionTool.js
- lizmap/modules/view/templates/map_draw.tpl
- tests/end2end/playwright/draw.spec.js
> [Backport release_3_9] JS Digitizing - enhancing module, component and the way to use them

- assets/src/components/MousePosition.js
- assets/src/components/Treeview.js
- assets/src/dependencies/mgrs.js
- eslint.config.mjs
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/legend.spec.js
- tests/end2end/playwright/snap.spec.js
- tests/end2end/playwright/webdav-upload.spec.js
Follow up from #5455
Javascript - Set ESLint to max 250 characters
> Javascript - Set ESLint to max 250 characters

- assets/src/modules/Digitizing.js
> [Backport release_3_8] Fix Digitizing module: deactivate it when draw is closed

- tests/end2end/playwright/auth.setup.ts
- tests/end2end/playwright/information-panel.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/requests-metadata.spec.js
- tests/qgis-projects/tests/set_tests_respository_rights.sql
Follow up from #5305 
from @mdouchin 
It will be manually backported into #5741
> Tests - Add E2E for WFS export ACL

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMainData.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/view/classes/lizmapMainViewItem.class.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/templates/map_metadata.tpl
- lizmap/modules/view/templates/view.tpl
- lizmap/modules/view/zones/main_view.zone.php
- tests/end2end/playwright/auth.setup.ts
- tests/end2end/playwright/information-panel.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/requests-metadata.spec.js
- tests/qgis-projects/tests/set_tests_respository_rights.sql
Backport #5305
Author @mdouchin
> Metadata - Add WFS link if the user has enough rights

- .github/workflows/lint.yml
- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
- .gitlab-ci.yml
- CHANGELOG-3.10.md
- dev/Dockerfile
- docker/Dockerfile
- lizmap/composer.json
- tests/README.md
- tests/units/composer.json
PHP - Increase minimum version to 8.2
> PHP - Increase minimum version to 8.2

- lizmap/modules/admin/templates/server_information.tpl
Fix #5754
Admin - Check if repository key exists before accessing it
> Admin - Check if repository key exists before accessing it

- assets/src/modules/Action.js
The Action HTML message ha also to be reset, like other message.
Funded by WPD Onshore France
> Fix JS Action - reset HTML message

- lizmap/modules/lizmap/classes/lizmapFts.class.php
Funded by DVP SOLAR France paid support
> Optimize fts query to use the index

- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/api/openapi.yaml
- tests/end2end/playwright/requests-api.spec.js
_Backport #5596_
_Based on #5662_
Funded by 3Liz
> [Backport release_3_8] API: GET info on project

- assets/src/components/Print.js
- tests/end2end/playwright/print.spec.js
> [Backport release_3_9] Fix: Printing with text drawing/labels is broken

- assets/src/components/Print.js
- tests/end2end/playwright/pages/drawpage.js
- tests/end2end/playwright/print.spec.js
> [Backport release_3_8] Fix: Printing with text drawing/labels is broken

- assets/src/index.js
- assets/src/legacy/map.js
The Lizmap initialization was perform by the legacy code, but it now depends the mainLizmap singleton.
So to be sure that the mainLizmap is ready, it is more safe to perform Lizmap initialization after the mainLizmap singleton is ready.
> JS initialize Lizmap Application from not legacy code

- assets/src/index.js
- assets/src/legacy/map.js
> [Backport release_3_9] JS initialize Lizmap Application from not legacy code

- lizmap/modules/lizmap/lib/Request/Proxy.php
> [Backport release_3_8] Catching Guzzle client exceptions

- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/end2end/playwright/popup.spec.js
The test : Should display zoom and center buttons if "Add geometry to feature response" is checked ; has been moved and enhanced because the layer id can change.
Linked to https://github.com/3liz/lizmap-web-client/pull/5828
> Tests e2e: Move one test for Cypress to Playwright about feature toolbar in popup with geometry

- .github/workflows/e2e_tests.yml
Backport #5826
From @nboisteault
> [Backport release-3_9] Simplify test stack launch

- .github/workflows/e2e_tests.yml
Backport #5836 #5826
From @nboisteault
> Simplify test stack launch

- .github/workflows/e2e_tests.yml
Try to install composer packages
> GH Actions - Switch to PHP 8.2, remove fixed time sleep in action, curl is better

- package-lock.json
- package.json
Backport 2fe0ba5ae3f0814daf5e1a3d69178b09a598f565
Authored by: @nboisteault
> [Backport release_3_9] Update OL to 10.6.1

- package-lock.json
- package.json
- tests/docker-conf/phpfpm/Dockerfile
- tests/docker-conf/phpfpm/appctl.sh
> Use rspack instead of webpack

- .github/workflows/e2e_tests.yml
Linked to #5860 and recently broken XML #5887
> GH Action - Upgrade QGIS and PHP version for bleeding edge

- .github/workflows/e2e_tests.yml
> [Backport release-3_10] GH Action - Upgrade QGIS and PHP version for bleeding edge

- package-lock.json
Run `npm update @rspack/core` and @rspack/cli and eslint-plugin-jsdoc
> Follow up PR JavaScript - Update dependancies #5925

- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/ProjectMainData.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/rector.php
Enhancing code quality by applying rector SimplifyIfReturnBoolRector
> PHP: Apply simplify if return bool from Rector

- .pre-commit-config.yaml
Linked pre-commit and package.json
> Pre-commit: Update ESLint and StyleLint to have the same version as in package.json

- assets/src/components/FeaturesTable.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
> [Backport release_3_8] lizmap-features-table: Display a message when no features found

- tests/end2end/playwright/form_advanced.spec.js
- tests/end2end/playwright/pages/project.js
Adding waiting from request to be sure the UI is ready and to check the data provided by controllers
> Test e2e Playwright: enhancing group visibilities and filtered list

- lizmap/modules/admin/controllers/maps.classic.php
Validate the content of the form using `filter_var` php method (some values can lead to fatal error )
Additionnally, use the `Repository` class intead of old depracted `lizmapRepository`
Funded by 3Liz
> check URL when submitting AccessControlAllowOrigin in admin Form

- lizmap/modules/admin/controllers/maps.classic.php
Backport #5997
**Authored by:** @nworr
> [Backport release_3_8] check URL when submitting AccessControlAllowOrigin in admin Form

- tests/end2end/playwright/popup.spec.js
> [Backport release_3_10] Fix e2e playwright tests popup: default buffer length

- tests/end2end/playwright/popup.spec.js
> [Backport release_3_8] Fix e2e playwright tests popup: default buffer length

- tests/end2end/playwright/tooltip.spec.js
1. Check the response of the tooltips request
2. Add a test to checked if an error message is displayed in case of response error
> Tests e2e: enhancing tooltips tests

- tests/lizmap-ctl
- tests/qgis-projects/tests/tests_dataset.sql
> [Backport release_3_8] Tests: fix restrict key for dumping database

- .github/workflows/e2e_tests.yml
- .github/workflows/lint.yml
- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-wfs.spec.js
> [Backport release_3_10] GH Action tests: add setup-node to get npm cache

- .github/workflows/e2e_tests.yml
- .github/workflows/lint.yml
- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-wfs.spec.js
> [Backport release_3_9] GH Action tests: add setup-node to get npm cache

- .github/workflows/e2e_tests.yml
- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-wfs.spec.js
> [Backport release_3_8] GH Action tests: add setup-node to get npm cache

- lizmap/modules/lizmap/controllers/features.classic.php
- tests/end2end/playwright/tooltip.spec.js
- tests/qgis-projects/tests/tooltip.qgs
- tests/qgis-projects/tests/tooltip.qgs.cfg
Backport #6014
**Authored by:** @mdouchin
> [Backport release_3_8] Tooltip - Fix configured fields not used when HTML template is not defined

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/popup.spec.js
* Tests e2e Playwright checkJSON: explicite response not ok
* Tests e2e Playwright dataviz in popup as readonly
> Tests e2e Playwright checkJSON: explicite response not ok

- .github/workflows/tests.yml
- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Log/ConfigTest.php
- tests/units/classes/Log/ItemTest.php
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Request/ProxyTest.php
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/classes/lizmapRepositoryTest.php
- tests/units/classes/lizmapServicesTest.php
Superseed https://github.com/3liz/lizmap-web-client/pull/5860
> GH Action - Update PHP-Unit version for PHP 8.3 and 8.4

- .github/workflows/e2e_tests.yml
- tests/Makefile
- tests/README.md
- tests/add_server_plugins.sh
- tests/docker-conf/unstable-plugin-sources.list
Backport #6006
**Authored by:** @dmarteau
> [Backport release_3_9] Deprecate `run-docker`

- .github/workflows/tests.yml
- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Log/ConfigTest.php
- tests/units/classes/Log/ItemTest.php
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Request/ProxyTest.php
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/classes/lizmapRepositoryTest.php
- tests/units/classes/lizmapServicesTest.php
> [Backport release_3_9] GH Action - Update PHP-Unit version for PHP 8.3 and 8.4

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/overview.spec.js
- tests/end2end/playwright/treeview.spec.js
* Enhancing globals Wait for GetCapabilities request
* Enhancing Overview tests
* Enhancing Treeview tests
> Tests e2e playwright: enhancing Overview and Treeview tests

- lizmap/modules/admin_api/controllers/group_rest.classic.php
- lizmap/modules/admin_api/controllers/path_rest.classic.php
- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rights_rest.classic.php
- lizmap/modules/admin_api/controllers/rights_rest.classic.php
- lizmap/modules/admin_api/lib/Credentials.php
- lizmap/modules/dataviz/controllers/service.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/App/Checker.php
- lizmap/modules/view/controllers/media.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- tests/end2end/playwright/requests-api.spec.js
> Api - improve rights

- lizmap/modules/admin_api/controllers/group_rest.classic.php
- lizmap/modules/admin_api/controllers/path_rest.classic.php
- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rest.classic.php
- lizmap/modules/admin_api/controllers/repository_rights_rest.classic.php
- lizmap/modules/admin_api/controllers/rights_rest.classic.php
- lizmap/modules/admin_api/lib/Credentials.php
- lizmap/modules/dataviz/controllers/service.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/App/Checker.php
- lizmap/modules/view/controllers/media.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- tests/end2end/playwright/requests-api.spec.js
Backport #6049
**Authored by:** @mdouchin
> [Backport release_3_8] Api - improve rights

- lizmap/modules/lizmap/lib/Request/EchoMiddleWare.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
Use a dedicated class as a Guzzle MiddleWare to handle "echo request" feature
Ticket : #
Funded by 3Liz
> refacto : move proxy echo feature to as guzzle middleware

- .github/workflows/docs.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/labeler.yml
- .github/workflows/lint.yml
- .github/workflows/milestone.yml
- .github/workflows/php-stan.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
> [Backport release_3_9] Bump some Github Actions

- package-lock.json
- package.json
Backport #6121
**Authored by:** @dependabot[bot]
> [Backport release_3_9] Bump webpack from 5.101.3 to 5.102.0
