3liz/lizmap-web-client

- lizmap/modules/lizmap/controllers/service.classic.php
This only should to happen with PHP version < 5.5
see php doc: http://php.net/manual/en/function.empty.php#refsect1-function.empty-parameters
> Fixes PHP error: empty() function only supports variables

- lizmap/modules/lizmap/classes/lizmapCache.class.php
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/var/config/localconfig.ini.php.dist
- lizmap/var/config/profiles.ini.php.dist
Rights values should not be defined directly into the code
because these values may not be suitable for the server configuration
or for the needs of the user.
So let's used values defined in the Jelix configuration.
> Cache files should have rights defined in the configuration

- lizmap/modules/lizmap/classes/lizmapProxy.class.php
Since array_key_exists is used, the profile name should be the key in the array.
> Fix profile names cache into lizmapProxy

- lib/jelix-plugins/cache/file/file.cache.php
- lib/jelix/core/log/jSyslogLogger.class.php
- lib/jelix/utils/jCache.class.php
- lib/php5redis/README.md
- lib/php5redis/Redis.php
- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/classes/qgisMapLayer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/install/upgrade_qgisprojectcache.php
- lizmap/modules/lizmap/module.xml
- lizmap/modules/view/templates/map_projects.tpl
- lizmap/var/config/profiles.ini.php.dist
Reading the xml file of projects (*.qgs) takes many time (and many memory). And it is readed at each request, so for each tiles. 
Now the XML content is readed only one time, and needed data are put in a cache. Xml file is readed only if it has changed. And so, most of methods of LizmapProject don't read anymore the xml content, and just return data readed from the cache. Except some few methods that read the xml file everytime : getXmlLayers(), getXmlLayerByKeyword($key), getComposer( $title ), getXmlLayer()
> Put data from qgs files to a cache

- lizmap/var/themes/default/master_admin/zone_admin_menu.tpl
Clicking on the link corresponding to a parent page of a section is not possible.
For example, when we click on a link on "Lizmap configuration",
then we go to modify the config or a repository, the link
"Lizmap configuration" becomes inactive and has the bad URL.
We cannot back to the lizmap configuration with the menu.
> Fix issue in the admin menu: impossible to back to the parent page

- lizmap/modules/view/locales/pt_PT/dictionnary.UTF-8.properties
according commit https://github.com/3liz/lizmap-web-client/commit/fd4e6e84cf5f5fbf61201ac51024107eda2a8db0
popup.msg.no.result
also necessary for all other locales
> Popup - Warn user if no object has been found & dock not showed on small screen

- lizmap/modules/view/locales/de_DE/map.UTF-8.properties
- lizmap/modules/view/locales/el_GR/map.UTF-8.properties
- lizmap/modules/view/locales/en_US/map.UTF-8.properties
- lizmap/modules/view/locales/es_ES/map.UTF-8.properties
- lizmap/modules/view/locales/eu_ES/map.UTF-8.properties
- lizmap/modules/view/locales/fi_FI/map.UTF-8.properties
- lizmap/modules/view/locales/fr_FR/map.UTF-8.properties
- lizmap/modules/view/locales/gl_ES/map.UTF-8.properties
- lizmap/modules/view/locales/it_IT/map.UTF-8.properties
- lizmap/modules/view/locales/nl_NL/map.UTF-8.properties
- lizmap/modules/view/locales/pl_PL/map.UTF-8.properties
- lizmap/modules/view/locales/pt_BR/map.UTF-8.properties
- lizmap/modules/view/locales/pt_PT/map.UTF-8.properties
- lizmap/modules/view/locales/ru_RU/map.UTF-8.properties
- lizmap/modules/view/locales/sv_SE/map.UTF-8.properties
- lizmap/modules/view/templates/map_attributeLayers.tpl
the behavior is intuitive
i propose also this change to gain some space
or remove `<b>{@view~map.attributeLayers.options.title@}</b>`
>  attribute table - unnecessary help

- lizmap/www/js/map.js
You can choose to visualize the children of a layer. You have to choose the Qgis mode et at the very least add the class `lizmap_merged` to your table. You only need to create a normal table in HTML and you can manage it better with the use of classes `lizmapPopupHeader` and `lizmapPopupHidden`
> Popup - Improve the display of children popup in a more compact table

- lizmap/modules/view/controllers/embed.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/modules/view/locales/fr_FR/dictionnary.UTF-8.properties
- lizmap/www/css/map.css
- lizmap/www/js/dataviz/dataviz.js
- lizmap/www/js/map.js
There is now a way to open the complete map from an embedded map, it will give the possibility to the user to get a better view of the map if the embedded map is too small. 
It will not solve #815 problem but it can be helpful.
The part about dataviz is a feature we are working on who should be completed pretty soon, it will permit users to visualize the statistics of child layer if dataviz is configured for her.
When you click on the parent on the map, the charts who were configured will appear in the popup, but filtered for only the children of this parent. It will permit you to get statistics for each point and not only the global stats. (May not be too clear but we will explain it betters in the documentation when it's finished)
> Embed, Popup : open the complete map in the embedded maps and the map.js side of statistics in popups for layers with children

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/www/css/map.css
- lizmap/www/css/media.css
- lizmap/www/js/dataviz/dataviz.js
- lizmap/www/themes/default/css/map.css
If you have checked the checkbox in the plugin for your plot you can hide the parent plot.
It's useful if you only want to see the children and hide the parent if he contain too much information without being filtered.
> [Enhancement] Enable the possibility to hide the parent plot in Dataviz

- lizmap/modules/lizmap/controllers/edition.classic.php
The way that lizmap was verifying the value for text and boolean was too
simple and strict. If the value is Null or empty, NULL is stored. This test
excluded to store '0' and 0.0.
The fix adds more specific tests.
> [Edition] Be more permissive for text and less for boolean

- lizmap/www/js/attributeTable.js
A layer without geometry is not referenced in `lizMap.map` so `layer` variable is null and
`config.layers[featureType]['request_params']['filter'] = null;`
`config.layers[featureType]['request_params']['exp_filter'] = null;`
is not executed.
> [BUGFIX] disable filter on layer without geometry doesn't work

- lizmap/www/js/map.js
Actually with "Montpellier - Intranet map example" if we open permalink tool, permalink in input is hidden because the CSS selector hide all children not only direct children.
> [BUGFIX] CSS selector must only select direct children

- lizmap/modules/lizmap/install/sql/lizgeobookmark.pgsql.sql
- lizmap/modules/lizmap/install/sql/lizgeobookmark.sqlite.sql
- lizmap/modules/lizmap/install/sql/lizlog.pgsql.sql
- lizmap/modules/lizmap/install/sql/lizlog.sqlite.sql
Add in SQL scripts IF EXISTS for CREATE TABLE and DROP IF EXISTS before CREATE INDEX.
Fixed #879
> [BUGFIX] Install fails when the tables of Lizmap already exist

- lizmap/www/css/map.css
> [BUGFIX] The bottomdock will no longer hide a zoomed point

- lib/vendor-modules/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php
Fixed #926 ldapdao - add users to default "users" group, and do not remove them on group sync
Need to be backported to ldapdao jelix module.
> [BUGFIX] Add LDAP authenticated user to default groups even if not defined in LDAP

- lizmap/www/js/attributeTable.js
If a filter is launched and if no children found, the filter was deactivated for the children layer.
The fix provided creates a filter if the parent is filtered and the children layer has to be filtered.
> [BUGFIX] Filter children even if no children found after parent filtering

- lizmap/www/js/edition.js
To be homogeneous with naming events we should call this event lizmapeditionformclosed unless we want to remove all 'lizmap' string at the begin of events.
> lizmapeditionformclosed event not editionformclosed

- lizmap/plugins/formbuilder/htmlbootstrap/htmlbootstrap.formbuilder.php
No javascript involved. Checkbox need to be disabled to be readonly, note that value won't be sent by submit but it is not a problem as it is readonly. We might also disabled other readonly input, this way we don't send a value that we know has not changed, this is the same idea that for https://github.com/3liz/lizmap-web-client/issues/954.
Fix first point in https://github.com/3liz/lizmap-web-client/issues/958.
> [BUGFIX] Make readonly checkbox really readonly

- lizmap/modules/lizmap/classes/lizmapProxy.class.php
It is called statically by qgisServer class. And all other methods
of lizmapProxy are static.
> Fix: lizmapProxy::constructUrl() should be static

- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
The error is more friendly: "the layer is not editable".
Refs #980
> Fix: don't show a technical error when the layer to edit does not exist

- lib/jelix/plugins/tpl/html/block.ifctrl_value.php
- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/forms/config_services.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/config.tpl
- lizmap/modules/dynamicLayers/controllers/map.classic.php
- lizmap/modules/lizmap/classes/lizmapCache.class.php
- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
- lizmap/modules/lizmap/classes/qgisServer.class.php
- lizmap/modules/lizmap/controllers/ign.classic.php
- lizmap/modules/lizmap/controllers/osm.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/plugins/formbuilder/htmlbootstrap/htmlbootstrap.formbuilder.php
- lizmap/plugins/formwidget/group_htmlbootstrap/group_htmlbootstrap.formwidget.php
- lizmap/www/css/admin.css
There are new possible parameters into lizmapConfig.ini.php, allowing to configure a proxy for requests  to external services. These parameters can be changed in the configuration form of Lizmap.
Some refactorizations have been made in order to call external services only from a single method, `lizmapProxy::getRemoteData()`, instead of having curl calls in many places in the code.
Fixes #932
> Support of proxy parameters for http requests to external services

- vagrant/roles/qgis/tasks/qgis_server.yml
Execution failed with message gpg: cannot open '/dev/tty': No such device or address". With --no-tty it is ok now.
Environnement : ubuntu 18.04, virtualbox 6.0, vagrant 2.2.2
> Fix gpg: cannot open '/dev/tty': No such device or address"

- lizmap/modules/lizmap/controllers/service.classic.php
Currently Lizmap connected to a QGIS 3.x server always show popups in auto mode. This is a **regression** in lizmap because it didn't catchup with a change in QGIS GetFeatureInfo implementation.
QGIS 3.x fetches geometry and maptip in feature info only if they are requested by the client.
See [QGIS](https://github.com/qgis/QGIS/commit/5bd63b7e1789a72c2692d8d61fab267ec2258eb5
) for the commit and [QWC2](https://github.com/qgis/qwc2-demo-app/issues/55) for a discussion.
This patch restores the functionality of using QGIS' maptip as popup content
> fix popups that use QGIS maptip

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
qgisVectorLayer open a sqlite connection by indicating both mod_spatialite.so
and lib_spatialite.so, although only one is available obviously. And so it causes some
notices that pollute logs files. The connection should be open with the right
extension.
> Remove annoying logs about libspatialite.so

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
At some places, we should use the text version of featureId instead of the PHP version.
Else if featureId is an array, we have some PHP notices and bad values : "Array" instead of a string with integers separated by coma.
> Fix edition when featureId contains multiple id

- lizmap/modules/lizmap/controllers/service.classic.php
QGIS Server 3.4 use version 1.1.0 by default for WFS. Actually Lizmap expect 1.0.0 so we use this version as default.
Fix #1084
> Set WFS version to 1.0.0 as default

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
Layers have often the same datasource (same host/db/login/passwd). 
We could avoid to create a connection or a profile for each layer, by using the same profile/connection between layers having same datasource. 
And we could use persistent connection; so lizmap can reuse same connections between each requests.
The result may be less connections to the database, and less memory usage.
> Optimize db connection in layers

- lizmap/modules/lizmap/classes/qgisForm.class.php
After the submit, qgisform convert some empty values '' to 0 instead of null. it causes issues when the value represents a foreign key. In this case, most of time 0 is not valid...
> Fix qgisform null value

- .gitignore
- lib/jelix/events/jEvent.class.php
- lib/jelix/plugins/tpl/common/cfunction.fetchtpl.php
- lib/jelix/plugins/tpl/html/function.ctrl_label.php
- lizmap/modules/lizmap/classes/qgisAttributeEditorElement.class.php
- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
- lizmap/modules/lizmap/classes/qgisFormControlsInterface.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/module.xml
- lizmap/modules/view/templates/edition_form.tpl
- lizmap/modules/view/templates/edition_form_container.tpl
- tests/README.md
- tests/bootstrap.php
- tests/composer.json
- tests/edition/qgisAttributeFormTest.php
- tests/phpunit.xml
This set of patchs allows to customize forms generated by qgisForm, used to edit features.
It allows :
- to customize the html, by replacing the new template, by an other one in a theme
- to do things at different steps of the forms' life, by responding to new events, so a custom module can add data processing on edited data, or customize the final form.
> Qgisform hooks & template

- lizmap/www/js/atlas.js
- lizmap/www/js/attributeTable.js
It supposed to be an object, as the code in maps.js suggests, but some code in attributeTables.js create this property as an Array instead of an Object.
We fix the type as Object, as it is more efficient than an array, since feature id could be large numbers. 
We don't use a Map because of the support of IE10.
> Fix the type of the features property into layer objects of lizmap

- lizmap/www/js/attributeTable.js
Fix #1125 and probably a bug when users activate WFS for a layer and don't use it in attribute table.
> Fix bug WFS layers not in attribute table

- lizmap/www/js/map.js
We may need to know when the feature was not loaded, so this new
callback parameter.
Some time, a feature may appear into several layer. If it is modified
into a layer, and its WFS data already loaded for an other layer, this
data are not updated. An ugly solution is to force to load the data, by
the code which knows that the feature it processes may not be updated..
> map.js, getLayerFeature: aCallbackNotfound and forceToLoad parameters

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
qgisFormControl is expecting to receive a simpleXml object for the alias parameter, whereas it seems it receives a simple string.
Let's keep the process of the simpleXml object to not break custom modules, but check if it is a simple string to avoid warnings
> Fix process of the alias parameter to qgisFormControl

- lizmap/modules/lizmap/classes/lizmapProject.class.php
If we add some properties into a deep object that is in the cache, like a new property into the layer structure, it will be more and more difficult to add tests on the check of the cache validation.
Using a version number is easier to invalidate the cache. We only had to increase this number, instead of adding more and more properties checks.
> Improve cache invalidation for qgis projects

- lizmap/install/qgis/montpellier.qgs
- lizmap/www/js/map.js
Atlas compositions are available in the print template even if it has not been designed to be used as a simple print template
These changes remove atlas compositions from print template selector and update Montpellier project.
In Montpellier project, Atals configuration has been removed from Landscape A4 and District card composition has been added.
> [Bugfix] Remove atlas compositions from print template selector

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
Default values other than raw strings or number, are ignored.
Parameters of qgisFormControl constructor are changed:
- new parameter $defaultValue
- $prop parameter is put before parameters that have a default value,
else it is not a correct php syntax.
> Use Qgis default value to set default value on form controls

- lib/jelix/core/response/jResponseBinary.class.php
- lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- fix the name of the file to have a unique name per requests
- delete files after sending them to the browser to keep a clean /tmp
Refs #1185
> Fix issues with temporary files created by lizmapWFSRequests

- lizmap/www/js/switcher-layers-actions.js
the default behaviour is not changed
but in a custom script, one can do
```
lizMap.events.on({
uicreated: function(e) {
lizMap.config.options.layerOpacities = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1];
}
});
```
in future this could be added to the plugin config
Signed-off-by: Marco Bernasocchi <marco@opengis.ch>
> allow setting the layers opacity levels in custom JS

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/templates/map_menu.tpl
This will allow completely turning off the project switcher effectively allowing lizmap to be used in a single map mode.
The behavior is:
- Onlymaps ON, projectswitcher ON: show one house icon for the project switcher (usual LM behavior)
- Onlymaps ON, projectswitcher OFF: show one house icon to reload the current map
- Onlymaps OFF, projectswitcher ON: show two icons (house and folder) to either go to project listing or show the project switcher
- Onlymaps OFF, projectswitcher OFF: show one house icon to go to project listing
> Allow disabling project switcher completely

- lizmap/install/qgis/media/upload/.empty
to avoid error messages while running the the script `set_rights.sh www-data www-data` 
chown: cannot access 'lizmap/install/../install/qgis/media/upload': No such file or directory
chmod: cannot access 'lizmap/install/../install/qgis/media/upload': No such file or directory
> running set_rights.sh www-data www-data

- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/www/js/edition.js
We should not have an error "You cannot save this object without a geometry. Please draw the geometry on the map.", when creating a feature on a layer having the modifyGeometry capability set to false.
This is the case when the layer is based on an SQL view, so on which the geometry field is in read-only. The code that verify the value of the geometry field, should honor the modifyGeometry capability.
> Fix edit geometry

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/view/controllers/lizMap.classic.php
The data panel and its corresponding button should not be shown when
there is no attribute table set with the "hideLayer=False" into the
map configuration.
> Hide the "data" button when there is no displayed attribute tables

- lizmap/modules/view/controllers/lizMap.classic.php
We should avoid javascript to hide legend but I let it like it is because there might be some side effects I'm not aware of
> Force hidden legend only when active Fix #994

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
QGIS 3 set CheckedState/UncheckedState as empty, when field is a PgSQL bool. Fix #1261
> Force boolean value when CheckedState/UncheckedState are empty

- lizmap/www/js/filter.js
In filter forms, for unique values with splitter defined, use AND for fiter to find features with all selected values.
> [Fix] Filter: Use AND for unique values with splitter

- lizmap/www/js/attributeTable.js
- lizmap/www/js/edition.js
When we launch the edition of a child feature during the edition of a feature, the return to the edition of the parent is not well done in the case when the split tool was used (issue #1301).
To fix this issue, parts of the code of the editor has been refactorized, and will allow to improve it easier.
> Improve the edition of parent feature

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/www/js/map.js
The `GetPrint` request's `OPACITIES` parameter overrides the layer opacities define in QGIS Project.
To fix it, lizmap reads the layer opacities in QGIS project, provides it in config and use it in `GetPrint` url.
> [Bugfix] Print layer opacities

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The Layer schema has to be quote in the search_path parameter of the db connection to avoid problem with `-`, upper character, etc
> [Bugfix] Quote schema for search_path in dbParams for GetFeature

- lizmap/www/js/atlas.js
- lizmap/www/js/attributeTable.js
- lizmap/www/js/map.js
- lizmap/www/js/timemanager.js
OpenLayers GeoJSON format has an attribute to read 3-4D points : `ignoreExtraDims`
The commit adds `ignoreExtraDims: true` to all `new OpenLayers.Format.GeoJSON`
> [Bugfix] Support parsing GeoJSON of geometry with Z and/or M dimension

- lizmap/responses/myHtmlMapResponse.class.php
- lizmap/www/OpenLayers-2.13/lib/OpenLayers/Format/WKT.js
OpenLayers does not parse WKT of geometry with Z and/or M dimension.
The commit contains an enhance WKT parser based on a regEx.
The fix is needed to:
* display geometry provided by GetFeatureInfo
* display geometry provided by edit form to update it
* display geometry in locate by layer
> [Bugfix] Support parsing WKT of geometry with Z and/or M dimension

- lizmap/modules/lizmap/controllers/config.cmdline.php
- lizmap/modules/lizmap/controllers/database.cmdline.php
- lizmap/modules/lizmap/install/sql/lizlog.mysql.sql
- lizmap/modules/lizmap/lib/Logger/MigratorFromSqlite.php
- lizmap/modules/lizmap/lib/Users/MigratorFromSqlite.php
New commands allow to migrate all users/acl tables from sqlite to pgsql, as well as to migrate log table.
```
php lizmap/scripts/script.php lizmap~database:migratelog
php lizmap/scripts/script.php lizmap~database:migrateusers
```
`migrateusers` is experimental. 
`migratelog` has been well tested, and will be needed on our infrastructure.
> New commands to migrate lizmap data from a sqlite database to pgsql/mysql

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
I have many errors like this in some logs of a lizmap instance:
```
preg_match(): Compilation failed: unmatched parentheses at offset 5 
modules/lizmap/classes/qgisVectorLayer.class.php   453
```
It seems the geometryType may contains some parenthesis, and since these characters are reserved into a regexp, they should be quoted.
> Fix error in qgisVectorLayer when geometrytype contain parenthesis

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisProject.class.php
Cache backends don't support '\' in a key. When using a file path as a key under windows, we must replace this character by '/'
Refs #1380
> Fix project cache with windows

- lizmap/www/js/edition.js
Edition layers order was considered as string not integer when sorted. Fix #1442
> Fix edition layers order

- lizmap/www/js/filter.js
Firefox does not handle date string with Date() function when there are not minutes in timezone offset. Fix #1424.
> Handle missing minutes in timezone offset for filter

- lizmap/www/js/filter.js
Since backticks leads to troubles with MS Internet Explorer, what means that the filter function cannot be used in IE.
I don't really understand how this `var todo` is used, but anyway it should not be written using backticks.
> Replace backtick with concatinated string 

- lizmap/modules/view/controllers/app.classic.php
The request view/app/metadata returns a JSON with lizmap information.
The commite adds information about QGIS Server:
```
"qgis_server":{"test":"OK","mime_type":"text\/xml; charset=utf-8"}
```
Or
```
"qgis_server":{"test":"ERROR","mime_type":"text\/html; charset=iso-8859-1"}
```
If you are admin, you have extra info, like HTTP code and response.
> [Bugfix] Test QGIS Server in view/app/metatdata

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisFormControl.class.php
Some changes in QGIS 3 force required option even if the field is not editable.
> [Bugfix] Read only form control cannot be required

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
- lizmap/plugins/formbuilder/htmlbootstrap/htmlbootstrap.formbuilder.php
- lizmap/plugins/formwidget/checkbox_htmlbootstrap/checkbox_htmlbootstrap.formwidget.php
The right form control for boolean field is checkbox.
In QGIS the editing widget can be defined to be a menulist, but the control does not correctly check boolean value.
The commit force control to be a checkbox if the field is boolean. It defined labels for check and uncheck.
> [Bugfix] Form: Use checkbox for boolean field and display labels

- lizmap/www/assets/js/edition.js
It allows plugins to customize the style of the edition layers. Default colors of styles of features shown in the edit layer or split edit layer, may not be suitable, or maybe the same as colors of features displayed in the map. So it is difficult to use editing tools.
> Editor: new event lizmapeditionfeatureinit to customize edition layers

- lizmap/modules/lizmap/classes/lizmapProject.class.php
I know, it's less readable like this for now.
But as soon as we will move to Lizmap 4, the setting will move to the dataviz section:
```
"dataviz": {
"layers": []
"config": [
"theme":"light"
]
},
```
So just to be in the move to Lizmap 4 ;-)
> switch from datavizTheme to theme

- lizmap/modules/lizmap/controllers/service.classic.php
For WMS GetFeatureInfo Html request, lizmap requested XML and transform it to html.
If the XML is bad, the errors have to be logged and the method return empty html string.
If the XML does not contain Layer element, it means that no requestable element has been found. The method returns empty html string.
Fixed #1588
> [Bugfix] Return empty GetFeatureInfoHtml when bad xml or empty layer

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
The method `lizmapOGCRequest::process` execute the request parameter as a method. It was not checked that the request is an instance method.
> [Bugfix] lizmapOGCRequest::process check request is a method

- lizmap/modules/lizmap/controllers/service.classic.php
Some methods in the lizmap service controller has not to be directly requested. They are methods for OGC Request parameter.
> [Bugfix] Lizmap service controller: protect unpublic method

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
It fixes the check of the control values, as `minvalue` and `maxvalue` are not properties on jFormsControl. And it fixes notices reported in #1539
> Fix support of min/max value on qgis range control

- lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The dbname parameters is not mandatory in PostgreSQL service file.
QGIS vector datasource stores the dbname: we pass it to connection parameters
even if service is given, when dbname is not empty
Related ticket : #1722
> QGIS Vector Layer - Datasource: dbname can be given when service is used

- lizmap/modules/lizmap/classes/qgisAttributeEditorElement.class.php
The `qgisAttributeEditorElement::getFields` did not return fields' name but control ref and for upload control it is not the field name.
This commit fix it. The `qgisAttributeEditorElement::getFields` will return fields' name.
> Fix regression in upload files: file path loss

- lizmap/modules/admin/templates/maps.tpl
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
There was an error 500 on admin.php/admin/maps because Jelix doesn't allow :: in Tpl.
> fixing error 500

- lizmap/modules/lizmap/classes/jelixInfos.class.php
- lizmap/modules/lizmap/classes/lizmapAppContext.interface.php
- lizmap/modules/lizmap/module.xml
Adding the JelixInfos class that allows us not to use Jelix directly in class methods.
This class will also allows us to alter the Jelix methods in the tests so we can create scenarios that can happens in some situations without having to directly touch the tested class or Jelix utilities.
This class is currently only populated with the utilities I need to test and modify the lizmapProject class but I will populate it with other utilities when I will need them.
> adding JelixInfos class

- lizmap/modules/lizmap/classes/lizmapProject.class.php
There was a '-' missing in lizmapProject and the getLoginFilter method can crash.
> fixing syntax error

- lizmap/modules/lizmap/classes/lizmapProject.class.php
In the qgis project, the show feature count is describe as a custom property
```xml
<customproperties>
<property key="showFeatureCount" value="1"/>
</customproperties>
```
In old version the custom property was removed by QGIS when show feature count was deactivated. Now it seems that QGIS keep the custom property with 0 as value.
```xml
<customproperties>
<property key="showFeatureCount" value="0"/>
</customproperties>
```
Lizmap was looking that the custom property exists, the fix also check the value.
Funded by [Conseil Département du Calvados](https://www.calvados.fr)
> Fix: showFeatureCount reading

- lizmap/modules/lizmap/classes/lizmapProject.class.php
Fixing a bug in getXmlLayer2 with a xpath query that was not compatible with QGIS Versions > 3
> fixing getXmlLayer2

- docker/Dockerfile
- docker/README.md
The [WPS module](https://github.com/3liz/lizmap-wps-web-client-module) is still a work in progresse and should not be delivered with docker official lizmap image  since it may be cause of instability.
This PR remove installation of the wps module in the docker image. 
The wps configuration is kept atm since this is a conditional setup and not activated if there is no LIZMAP_WPS_URL defined.
> Remove wps module from docker image

- lizmap/modules/lizmap/classes/qgisForm.listener.php
The `qgisForm` listener does not check if the  provided form is a qgis one.
> Fix qgisForm listener

- lizmap/www/assets/js/edition.js
Fix the wrong detection of tabs visibility after recent additions in LWC:
* addition of tabs for separating digitization tools and form
* support of QGIS expression based group visibility
We move the `displayEditionForm` call after showing the tabs `.edition-tabs`
> Edition - Fix form field visibility test

- lizmap/modules/lizmap/classes/lizmapProject.class.php
* Ticket : #https://github.com/3liz/lizmap-plugin/issues/292
* CFG - Make group_visibility an array instead of a string
* Linked to https://github.com/3liz/lizmap-plugin/pull/293
> CFG - Make group_visibility an array instead of a string

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/controllers/project.cmdline.php
A command line to request project WMS GetCapabilities to put project in QGIS Server cache.
The command line `php /srv/lizmap-web-client/lizmap/scripts/script.php lizmap~project:load 5` can be used in cron to be sure that lizmap project has been loaded by QGIS Server in Cache.
Funded by WPD
> Command line to load QGIS project

- lizmap/modules/lizmap/classes/qgisAttributeEditorElement.class.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Form/QgisFormControlsInterface.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- tests/units/edition/qgisAttributeFormTest.php
Moving qgisForm * classes to namespace `Lizmap\Form` + changing some Jelix methods in appContext methods.
> QgisForm* namespace + Jelix uncontextualization

- .gitignore
- lizmap/modules/lizmap/classes/qgisForm.listener.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/module.xml
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/qgisProjectForTests.php
Modification of the Lizmap API with namesapce changes.
Modification of the QgisForm/Control constructor to read informations of the JSON (cf: #1842)
> Qgis form refactor

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/controllers/translate.classic.php
translate query is slow because it reads translations line by line.
It can be cached taking care of future invalidation with version and lang as URL parameters
> Optimization : cache translate query

- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Form/QgisFormControlForTests.php
- tests/units/classes/Form/QgisFormControlTest.php
- tests/units/classes/Form/QgisFormForTests.php
- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Form/QgisLayerForTests.php
- tests/units/classes/Form/forms/attributeEditorTest.qgs
- tests/units/classes/Form/forms/montpellier.line.form.json
- tests/units/classes/Form/forms/test.date.form.json
- tests/units/classes/Project/ProjectForTests.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/TestContext.php
Tests for Lizmap\Form\QgisFormControl.
It's not a lot but despite the refactorisation, most of the methods are either useless to test or still not testable.
> QgisFormControl tests

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
We have an issue in the way lizmap managed editable fields when the form is applied.
This commit try to indentified only modified fields even if the fields is hidden or not used in the drag and drop form.
Funded by Conseil Départemental des Pyrénées Atlantiques
> [Bugfix] Get form modified controls

- lizmap/modules/lizmap/controllers/edition.classic.php
In the Ajax saveNewFeature method, the form check was not used to return before saveToDb.
> [Bugfix] Use form check in Ajax Save new feature

- extra-modules/lizmapdemo/qgis-projects/demoqgis/montpellier.qgs
- lizmap/www/assets/js/edition.js
Fixing an issue introduced with https://github.com/3liz/lizmap-web-client/commit/8053456875252733598a5c5387487fb20cd3421c
It is also a manually merge of https://github.com/3liz/lizmap-web-client/pull/1894 with: 
* Do not activate combobox or autocomplete on disabled select
* Fix widget relation value for tram_stop_id in tram_stop_works
> Fix edition manage children value

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
Add a method to reset form controls data before tracking form controls changes for creation feature.
> Fix: Track fields changes for creation

- lizmap/modules/lizmap/classes/qgisForm.class.php
* fixes #1898
`qgisForm::processUploadedFile()` is called twice, once in `qgisForm::check()` and once in `qgisForm::saveToDb()`.
`qgisForm::processUploadedFile()` has not to be called in `qgisForm::check()`, it is called to get the value for checking constraints but it is not needed to process uploaded file.
> [Bugfix] Impossible to upload a file in edition mode

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
The lizmapOGCRequest does not check if the user has the right to override the login by filter.
If the user has the right to override the login by filter, lizmap has to send it to QGIS Server with an extra parameters `LIZMAP_OVERRIDE_FILTER`.
* Funded by Grand Narbonne
> [Bugfix] With lizmap plugin server side, override login by filter is not respected

- lib/jelix/forms/jFormsBase.class.php
Some values like `'0'` was not considered different from the empty value `''`.
> Fix comparison of modified values in qgis forms

- lizmap/modules/admin/controllers/logs.classic.php
If the lags table is too big, the controller does not build the output.
This commit fix it.
> [Bugfix] Admin export logs - No output with big logs table

- CHANGELOG-3.2.md
- lizmap/modules/lizmap/classes/lizmapProject.class.php
There are tons of logs about the code of `lizmapProject::hasAttributeLayers()`, because of the operator priority when $onlyDisplayedLayers is false, in this method.
> Fix notice project

- lizmap/modules/lizmap/classes/qgisForm.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
* Apply default value after initModifiedControlsList to be saved in database
* Fix when no fields modified
* If it's an insert return false and reopen the form
* If it's an update return true to close the form and do not execute an SQL UPDATE.
* Funded by Terre de Provence Agglomération
> Fix form init modified controls list management

- lizmap/modules/lizmap/classes/qgisForm.class.php
* In Lizmap 3.3.12-pre, there is a default relational value type field bug.
* This PR fix this bug
> FixBug: mandatory relational value by default

- lizmap/modules/lizmap/classes/qgisForm.class.php
Update to allow empty value or not  when multiple select is use
> Update required value

- lizmap/modules/admin/controllers/maps.classic.php
- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/dynamicLayers/controllers/map.classic.php
- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisServer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/ban.classic.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/osm.classic.php
- lizmap/modules/lizmap/controllers/project.cmdline.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/controllers/wmts.cmdline.php
- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
- lizmap/modules/lizmap/module.xml
- lizmap/modules/view/controllers/app.classic.php
- tests/units/classes/Project/TestContext.php
#1936 with the new files already moved.
> [Refactor] Proxy/Request namespace and context

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
This takes into account:
* layers with no `sql=` to make it compatible with QGIS >= 3.16
* layer with simple schema & table and with `sql=`. In the past, only complex layer with SQL inside the `table` property was covered by the tests.
> [BUGFIX] qgisVectorLayerDatasource: Improve parsing for layers with or without sql

- assets/src/components/Scaleline.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Map.js
Scales are those defined in Lizmap plugin when there is no EPSG:3857 base layers defined
Fix #1938
> Fix scale values to match those defined in plugin

- lizmap/modules/lizmap/classes/lizmapProject.class.php
Use the new properties stored in the `cfg` file to avoid parsing QGIS project XML file.
> Improve performance of QGIS project parsing for edition and attribute

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
Primary keys were not enclosed before used it in UPDATE RETURNING clause.
> [Bugfix] Enclose primary keys in UPDATE RETURNING

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The changes made to enclose primary keys in UPDATE RETURNING is not necessary in release_3_3 because it is done in `getPkWhereClause`
Fix regression introduced by #2014
> Revert [Bugfix] Enclose primary keys in UPDATE RETURNING

- docker/README.md
- docker/lizmap-entrypoint.sh
- docker/update-config.php
It is a backport of this feature from the main branch. 
It allows to setup the first account of lizmap with the login and email of our choice, and a password that can be generated randomly, or can be given into a file, or the  password recovery process can be triggered (an email is sent to the given email to reset the password).
> [docker] Setup of the admin password with environment variables

- lizmap/modules/lizmap/classes/lizmapProject.class.php
fixes #2032
fixes #2012
The test is described in #2032
> [Bugfix] The landing page shouldn't show project when not available for groups ACL

- lizmap/modules/lizmap/classes/qgisForm.class.php
To fix this issue, any fields not in QGIS Drag and Drop Form are deactivated.
Fixes #1994
> [Bugfix] Attribute edition sets to null unedited fields

- tests/run-docker
Add 'reset' command to tests/run-docker for resetting tests configuration:
Command:
```
./run-docker reset
```
Features:
* Stop and remove containers
* Remove postgres volume
* run './lizmap-ctl clean'
> [docker tests]: add 'reset' command

- lizmap/www/assets/js/edition.js
Fixes #2019 Tab content is not visible using Edition on Android (Lizmap 3.4.0)
The way lizmap checks the edition form tab visibility was not the right way. Lizmap checks visibility instead of checks if tab has not display:none
To test in a desktop browser:
> [Bugfix] Tab content is not visible on mobile screen

- lizmap/modules/lizmap/classes/qgisForm.class.php
* Ticket : #2046
* Fix bug concerning empty value in form with relational value configured with multiple choice and not null constraint
> [BugFix] Regression -  form with relationnal value

- lizmap/modules/lizmap/classes/qgisForm.class.php
The #2013 to fix #1994 has introduced a regression in form edition.
When submitted the form, the geometry is not retrieved and saved. The form isdisplayed with an error message about geometry not submitted.
> [Bugfix] Regression - Edition - Geometry is not retrieved and saved

- CHANGELOG-3.4.md
- lizmap/www/assets/css/map.css
* Fix #2061
@rldhont This can be easily tested editing CSS in this project : https://liz.lizmap.com/etrimaille/index.php/view/map/?repository=test&project=earthquake
> Fix visual blank line between map and right-dock

- lizmap/modules/lizmap/lib/Project/Project.php
* Ticket : fix #2080 
Just a typo error that was breaking dataviz plots.
> [Bugfix] Fix dataviz plots

- assets/src/modules/SelectionTool.js
> [Fix] Disable selection tool when mini-dock closed

- lizmap/modules/lizmap/install/sql/lizgeobookmark.pgsql.sql
The table geobookmark should not be created explicitly into the public schema.
All Lizmap tables must be installed in the same schema, e.g. in the
first schema indicated into the search_path of the connection.
> Fix geobookmark sql: remove explicit public schema

- CHANGELOG-3.5.md
- lizmap/modules/view/templates/popup.tpl
- lizmap/www/assets/js/map.js
Fetch all children popup instead of using jQuery post.
This allows having new `lizmappopupallchildrendisplayed` event launched when all children popup have been fetched.
* Funded by Grand Narbonne
> Popup children fetchall

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
Followup bf4ded5
Use array_key_exists instead of in_array for key identification in array.
For users the issue was that the Hidden Field defined in QGIS Form is not hidden in Lizmap form.
Use form_edition_all_field_type to check it.
> Fix regression in qgisFormControl constructor

- lizmap/modules/admin/classes/listProjectDatasource.class.php
- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/controllers/project.cmdline.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/lizmap/lib/Project/Repository.php
- lizmap/modules/view/zones/ajax_view.zone.php
- lizmap/modules/view/zones/main_view.zone.php
This will lower the memory usage when listing all projects information when building the landing page (or listing the projects of a repository). Fix #2191 
* Ticket : #2191
> [BUGFIX] Get only projects metadata for the landing page

- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
The WMTS GetTile request with TILEMATRIX=0&TILEROW=0&TILECOL=0 returned
```
<ows:ExceptionReport xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0" xml:lang="en">
<ows:Exception exceptionCode="MissingParameter">
<ows:ExceptionText>The parameter TileMatrixId is mandatory!</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```
Even if the tileMatrixId 0 is a valid value.
* Ticket : #
* Funded by
> Fix: WMTS GetTile request with 0 as parameter value

- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/lib/Logger/Item.php
The call of the dao method getDistinctCounter may fail if the sqlite database is locked or else. The exception was not catched and stopped the processing of the page.
> Fix logger: no more page processing interruption when it fails

- docker/Dockerfile
- docker/lizmap-entrypoint.sh
Strict alpine version is too restrictive: it prevents CI builds to take into accounts custom infrastructure choices. 
Change the name of the custom lizmap override config file dynamically created at startup from the PHP_INI env variable to follow convention.
> Docker: change base image tag

- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/classes/lizmapServicesTest.php
The debugMode parameter activates metrics, but also the logging of all
http requests to qgis. This is not what we would want. A new configuration
parameter `metricsEnabled` allow to enable only metrics, and
debugMode is not anymore used for metrics.
> New config parameter to enable metrics

- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
- tests/units/classes/Request/ClassesForTests.php
- tests/units/classes/Request/OGCRequestTest.php
Even if the request type name is checked into service.classic.php, when we used one of the OGC requests object independently, it could be processed with the name of any methods of the object.
Only methods corresponding to the request should be able to be executed. This is why I choose the solution to prefix these methods, so no other methods can be executed.
This naming allows too to identify easily methods of request types.
> Fix potential issues when calling OGC requests with unexpected method

- Makefile
- dev/Makefile
- docker/Dockerfile
- docker/README.md
- docker/lizmap-entrypoint.sh
- docker/update-config.php
This PR add the capability to use drop-in config files that will merge to the lizmap configuration files at startup. It allows for customized local  persistent configuration which will be available at startup without the risk to be removed on container restart.
It allows for the container to provide its own set of configuration independently of the custom local configuration (modules configuration is a good exemple): it simplifies the the deployment of module configuration without  having to tamper with the main configuration files.
It use environment variables for defiining the directories to load files from. If defined, all files ending in `*.php.ini` are merged to the appropriate config file
* Add `load_include_config` in `update-config.php`
* Use `LIZMAP_LOCALCONFIG_INCLUDE` env var …
> Add support for Drop-In lizmap configuration

- CHANGELOG-3.4.md
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
Fix and add test.
@mdouchin  I've added a test which currently fail with this kind of datasource occuring with QGIS >= 3.16. See attachment for Lizmap project, `end2end_form_edition` can't be edited with 3.16 datasource.
before 3.16 : 
`<datasource>service='lizmapdb' sslmode=disable key='id' estimatedmetadata=true checkPrimaryKeyUnicity='1' table="tests_projects"."end2end_form_edition" sql=</datasource>`
after 3.16 : 
`<datasource>service='lizmapdb' sslmode=disable key='id' estimatedmetadata=true checkPrimaryKeyUnicity='1' table="tests_projects"."end2end_form_edition"</datasource>`
Related to https://github.com/3liz/lizmap-web-client/commit/508318f490dd21c74a55c196a0fdbbc81f4eee81
[end2end_form_edition_3_16.zip](https://github.com/3liz/lizmap-web-client/files/6182768/end2end_form_edition_3 …
> [Fix] datasource w/o geom w/ service w/o sql (QGIS >= 3.16)

- lizmap/www/assets/js/dataviz/dataviz.js
Target version: LWC 3.4.4, LWC 3.5
If a dock with some plots is displayed, when another dock is opened the plots will be resized
> Dataviz resizePlot on docks opened or closed

- lizmap/www/assets/js/attributeTable.js
Target version: LWC 3.4.4, LWC 3.5
If bottom dock is opened, when UI size is changed, columns width of active table will be recomputed.
Without this patch if we press on button `Refresh`  the width of table columns is resetting to 0. 
This commit will fix this.
> Run refreshDatatableSize after button Refresh was pressed or when a dock is oppened or closed

- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
> Fix: Call to undefined method lizmapWMSRequest::parameters()

- dev/Makefile
- docker/update-config.php
If `LIZMAP_LOGMETRICS` env var is set then use the value as metrics logger and enable metric logging.
> Docker: configure log metrics

- CHANGELOG-3.5.md
- assets/src/components/MousePosition.js
- assets/src/modules/Layers.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Map.js
- assets/src/modules/interaction/Draw.js
This PR allows to put new OpenLayers Map on top of OL2 one. Both maps are in sync (zoom and extent).
This allows to use new OpenLayers features and remove legacy OL2 ones step by step.
This PR also add some draw features with new OpenLayers.
* Funded by [CRIGE PACA](https://www.crige-paca.org/) and 3Liz
> Allow new OpenLayers Map to be used on top of OL2 one

- lizmap/www/assets/js/filter.js
Fix the order of the fields in the filter form, in case of a postgis layer (before, was dependant to the SQL response order)
* Ticket : #2280
* Funded by gerald2545
> fix the order of the filter fields in the form

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/www/assets/js/map.js
* Funded by French Province Pyrénées-Atlantiques https://www.le64.fr/
* Based on Lizmap plugin changes https://github.com/3liz/lizmap-plugin/pull/341
A new popupSource is available in Lizmap Plugin: form
This configuration requested the Lizmap plugin server side to build the maptip HTML based on QGIS Form.
This configuration avoid to update the QGIS maptip with the QGIS Form.
So you can have a QGIS maptip and a Lizmap popup based on QGIS Form.
> [Feature] Get the GetFeatureInfo from QGIS Server with the QGIS Form

- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
In QGIS 3.16, the host in datasource can be wrote between single quote.
Fix #2332
> [Bugfix] Host in datasource between single quote

- lizmap/modules/lizmap/classes/qgisProject.class.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/readLayers_310.qgs
- tests/units/classes/Project/Ressources/readLayers_316.qgs
- tests/units/classes/Project/qgisProjectForTests.php
QGIS 3.16 introduce a new way to declare non-exposed fields in qgs
* Ticket : Fix #2304 
> Fix: get non-exposed fields via WFS w/ QGIS 3.16

- CHANGELOG-3.5.md
- lizmap/www/assets/js/action.js
* Remove useless JS code which sent the action `options` parameters (they are retrieved safely by the PHP back-end)
* When the result GeoJSON contains a field `message`, it is displayed in Lizmap message bar at the same time the received geometry is drawn
* A new action property `confirm` allows the editor to have a confirm message displayed with its text content before performing the action
* A new Lizmap event `actionResultReceived` is triggered when the action result is received with the action properties and the returned GeoJSON feature
* Documentation has been improved.
* Funded by SNCF Réseau Grand-Est
> Action - Improvements in Lizmap Web Client action module

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php
- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/module.xml
Some modules, like cadastre and wps client, need lizmapProxy and lizmapOGCRequest.
These classes has been removed and replaced by namespace classes. To keep compatibility,
These classes has been resurrected to extends the new classes.
> Resurrect lizmapProxy and lizmapOGCRequest classes for modules compatibility

- lizmap/modules/view/controllers/lizMap.classic.php
Add file modification time in custom assets querystring.
It busts cache and avoid user to force reload (ctrl + F5) to have fresh assets.
* Fix #2373 
> Fix: Add hash in custom assets querystring

- CHANGELOG-3.4.md
- lizmap/www/assets/js/dataTables/ro_RO.json
> Add Romanian translation for dataTables

- lizmap/modules/lizmap/lib/Project/Project.php
- tests/units/bootstrap.php
- tests/units/classes/App/XmlToolsTest.php
- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Log/ConfigTest.php
- tests/units/classes/Log/ItemTest.php
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Request/ProxyTest.php
- tests/units/classes/lizmapRepositoryTest.php
- tests/units/classes/lizmapServicesTest.php
- tests/units/classes/lizmapWktTest.php
- tests/units/classes/qgisExpressionUtilsTest.php
- tests/units/composer.json
- tests/units/edition/qgisAttributeFormTest.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
We have an old PHP Unit version compatible with PHP 5.6. As we won't support PHP 5.6, we can upgrade to PHP unit 9.5.7 which is compatible with PHP 7.3+
> [tests] upgrade PHPUnit to 9.5.7

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Form/QgisFormControlTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
The method fillCheckboxValues was not used, so CheckedState and UnCheckedState defined in the QGIS project was not used.
Fix #2399
> Fix: QGIS Form Control construct for Checkbox

- tests/units/classes/Form/QgisFormControlTest.php
A typo error is in the QgisFormControlTest file.
> [Tests] Fix norNull - replaced by notNull

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Form/QgisFormControlProperties.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/var/config/mainconfig.ini.php
- tests/docker-conf/phpfpm/localconfig.ini.php
- tests/units/classes/Form/QgisFormControlTest.php
- tests/units/classes/Form/QgisFormTest.php
- tests/units/classes/Form/forms/montpellier.line.form.json
- tests/units/classes/Form/forms/test.date.form.json
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/ContextForTests.php
- tests/units/testslib/ProjectForTests.php
- tests/units/testslib/QgisFormControlForTests.php
- tests/units/testslib/QgisProjectForTests.php
In 3.5, we put form properties into a cache, in order to avoid to load the qgis file when we need to edit a SIG feature.
However, there are some issues that causes some regressions and issues. This patch brings these improvements:
* the form properties are now stored into the same cache backend as  the one used to cache project properties, instead of storing into some JSON files somewhere into the lizmap directories. 
* So when flushing the main cache, forms caches will be also deleted.
* using the` jCache` backend allow to store PHP objects. So when loading the cache, we don't have an untyped object, but we could have objects having our own classes.
* refactor `QgisFormControl`, so it does not deal anymore with XML and `SimpleXml` objects. It is now the responsability to `QgisProject` to …
> Fix the form cache to avoid regression

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
Fix Undefined index: _text in /srv/lzm/lizmap/modules/lizmap/lib/Form/QgisFormControl.php 201
When jelix retrives PostgreSQL fields info, the jDbFieldProperties type value comes from pgtype.typname and can be _text for text.
Fixing https://paste.sh/wELXEssH#2sMuGK8X5c82wOu61oyv8Fbz
> [Bugfix] PostgreSQL typname can be _text

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
After refactoring, Lizmap was only able to return HTML for WMS GetFeatureInfo Request.
> [Bugfix] WMS GetFeatureInfo Request can return XML

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
The $appContext parameter was not described in the QgisForm and QgisFormControl constructor.
> Docsstring: Add appContext param to QgisForm and QgisFormControl construct

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
Fix Undefined index: _text in /srv/lzm/lizmap/modules/lizmap/lib/Form/QgisFormControl.php 201
When jelix retrives PostgreSQL fields info, the jDbFieldProperties type value comes from pgtype.typname and can be _text for text.
Mannually backport #2459
> [Backport release_3_5][Bugfix] PostgreSQL typname can be _text

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
Fix Undefined index: _text in /srv/lzm/lizmap/modules/lizmap/lib/Form/QgisFormControl.php 201
When jelix retrives PostgreSQL fields info, the jDbFieldProperties type value comes from pgtype.typname and can be _text for text.
Mannually backport #2459
> [Backport release_3_4][Bugfix] PostgreSQL typname can be _text

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
The $appContext parameter was not described in the QgisForm and QgisFormControl constructor.
Manually backport #2464
> [Backport release_3_5] Docsstring: Add appContext param to QgisForm and QgisFormControl construct

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/zones/map_menu.zone.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/testslib/QgisLayerForTests.php
The code to do some ACL checks for edition layers is duplicated at several place (including in at least the address module). This patch reorganize the code so we now have new methods on Project to manipulate edition layers. There is for example the method `canCurrentUserEdit` that could be used into the address module.
This patch improve also the memory usage of classes that have some properties like `cachedProperties` that could be `static`.
> API - Factorize ACL checks about edition layers

- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/zones/map_headermenu.zone.php
- lizmap/modules/view/zones/map_menu.zone.php
- phpstan.neon
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
There are duplicated content into ProjectConfig which makes its code complex: there is property having the raw content of the cfg file, and other properties that have also some content of this cfg file. 
Moreover, sometimes some code are retrieving the raw content (`getFullCfg`) to access to values, whereas there is a `getProperty` method for that. Using the raw content force the calling call to "know" the structure of the raw content. ProjectConfig should provide some methods to avoid this issue, and to abstract the structure of the cfg file.
So this patch remove the use of `getFullCfg()`, `getOptions` and `getProperties` (on Project or ProjectConfig), and replace them by getter methods that are ease the retrieval of desired values. There are not anymore duplicated content into …
> Refactor some Project and ProjectConfig usage, and fix some cache issues

- lizmap/modules/lizmap/controllers/edition.classic.php
* Fix bug checkbox in the form. On insertion when the checkbox is not checked, Lizmap considers it as unmodified. On this PR I modified the edit.classic.php file when saving in the database, if featureId is null we get all the controls else if not null we get only the modified controls.
> Fix bug of boolean checkbox when inserting

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/ProjectConfigTest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
After the refactoring, some properties of QgisProject or ProjectConfig were still duplicated into the Project class. The goal of this patch is to remove them, allowing to save bytes and to have a consistent code.
Improved also the ProjectConfig class, to accept only data in its constructor, instead of having a filename and optional data. It eases tests and this is the responsability to Project to load data from the cfg file if there is no cache.
> Cleanup of Project and ProjectConfig classes

- lizmap/modules/lizmap/classes/lizmapProxy.class.php
- lizmap/modules/lizmap/controllers/wmts.cmdline.php
Ths Lizmap WMTS command line only contains methods to create cache and nothing to clear it.
The commit add a new tool to clean cache.
Manually backport #2473
> [Backport release_3_4] Command wmts:cleaning - to clear cache with command line

- lizmap/modules/lizmap/lib/Project/Project.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/testslib/ProjectForOGCForTests.php
- tests/units/testslib/ProjectForTests.php
After the big refactorization of 2020, some properties were still duplicated between Project and QgisProject but not always with same values. It causes some unexpected results for some properties like when getting the title or the abstract.
This patch remove latest duplicated properties from Project to avoid confusion and to have lighter cache content.
* Ticket : #2490
> Fix Project: remove latest duplicated properties

- CHANGELOG-3.4.md
- lizmap/www/assets/js/attributeTable.js
lizMap.translateWfsFieldValues() change `data` type integer to string
so we return original `data` if its value has not changed or is null
it avoids wrong sorting in attribute table column
* Ticket : #2231
> Fix: integer key column sorted as text in attribute table

- CHANGELOG-3.4.md
- CHANGELOG-3.5.md
- lizmap/www/assets/js/edition.js
In case of more than one editable layers, when there is a filter by login (or by polygon) activated,
some of the popup items could miss the pencil button to open the editing form. Corrected by requesting
the editable features for all the editable layers of the displayed popup items, and not only the first.
> [BUGFIX] Fix editing buttons visibility in popup with several filtered layers

- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/wmts.cmdline.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
- tests/units/classes/Request/OGCRequestTest.php
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/classes/Request/WMTSRequestTest.php
Requests objects should rely on the same app context of the project object.
It is not consistent to have different appContext objects (and it could
brake some unit tests).
> Remove app context from OGCRequest constructor

- lizmap/modules/view/classes/popup.class.php
- phpstan.neon
The PHPStan error was #Undefined variable: `$address` in path /home/runner/work/lizmap-web-client/lizmap-web-client/lizmap/modules/view/classes/popup.class.php
Issue introduced 5 years ago by 18c0db388134bce68ebe9928cd6d95295e9b67d7 to try to fix #556
> [Bugfix] View Popup class: manually canonize path to authorize symlink

- lizmap/www/assets/js/map.js
The extent for printing has to be cloned before transform to do not change the printing geometry.
* Ticket : #2582
> [Bugfix] Printing twice the same extent does not provide the same

- CHANGELOG-3.5.md
- lizmap/www/assets/js/filter.js
If we want to use tools like [SumoSelect](https://hemantnegi.github.io/jquery.sumoselect/) to better display heavily populated combo-boxes, or allow multiple selection, we need to support multiple `<select>` values.
> Form filter - Prepare the possibility to select more than one combobox item

- tests/Makefile
- tests/run-docker
Use makefile for running tests stack:
- Better  separation of commands (separate env from docker commands)
- Easier use of direct docker-compose command (use project name as environment variable in env file)
- Better clean up (use `docker-compose down` for real clean up)
- Keep `run-tests` for compatibility
> Use Makefile to run test stack

- lizmap/www/assets/js/atlas.js
When i update a layer (Create or delete feature) configured as an atlas layer i have an error and the input list does not refresh
After checking the atlas script i found the problem [L150 in atlas.js](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/assets/js/atlas.js#L150).
you just have to put the `lizAtlasConfig` variable as a parameter
> fix atlas to refresh input list

- CHANGELOG-3.4.md
- CHANGELOG-3.5.md
- lizmap/www/assets/js/map.js
- tests/qgis-projects/tests/base_layers.qgs
- tests/qgis-projects/tests/base_layers.qgs.cfg
* Ticket : #2496 
* Tous les fonds de carte IGN proposés via le plugin Lizmap sont utilisables sans clé via les nouvelles URL a l’exception de un.
Il y a le nom de couche `GEOGRAPHICALGRIDSYSTEMS.MAPS` correspondant au fond de cartes `ign-scan` (Scan 25) qui n'est disponible qu'avec une clé à présent.
* Ensuite pour le fond `ign-cadastre` on proposait `CADASTRALPARCELS.PARCELLAIRE_EXPRESS` avec la clé gratuite et `CADASTRALPARCELS.PARCELS` avec une clé non gratuite or maintenant les 2 sont gratuits. Lequel propose-t-on ? ou alors on propose-t-on au utilisateur de choisir ?
> Change URL ign basemap

- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
- lizmap/www/assets/js/search.js
Backport to 3.5 and 3.4
Without this commit
With this commit
> Don't show search result if search query is empty

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/www/assets/js/map.js
- Selection: improve the export tool to allow bigger selections
- use the selection token instead of a list of feature identifiers
- internally use POST instead of GET requests to query data from QGIS Server
* Funded by 3liz & Faunalia
> [BUGIX] Selection & Export - Use the selectiontoken & POST to QGIS Server

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
This allows Lizmap Web Client modules to set their connection timeout
and avoid them to share the same PHP PostgreSQL connection.
At present, the connection sharing system is only determined
by the `host, user, service, port, dbname`
not by the `search_path`.
See: https://www.php.net/manual/fr/function.pg-connect.php
In some cases, when a `search_path` is needed, we need to avoid
the modules to reuse the same connection to the database.
> QGIS Vector Layer - New options timeout & setSearchPathFromLayer to set the PostgreSQL connection profile

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/var/config/mainconfig.ini.php
The search_path is not used for the connection, so layers
and modules can share the same connection although they want to use
a different search_path. A solution is to set a different timeout for
each different search_path.
> Fix postgresql connection share between modules

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisForm.listener.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/view/forms/edition.form.xml
The form does not have to be initialize each time we need to display it,
for example to show errors in the form. The form data can be initialize
during its creation. It simplify the code, save space in the session, and
avoid potential issues.
> [edition] rework the form management by using jForms features

- lizmap/modules/view/templates/view.tpl
- lizmap/www/assets/css/view.css
- lizmap/www/assets/js/view.js
CSS Grid avoid JS to have thumbnails with same height on every line and is easier to overload with custom CSS.
It also allows the use of img lazy loading which is buggy in Firefox with old code based on JS.
> Project thumbnails as grid

- lizmap/www/assets/js/search.js
The IGN services URL have been updated. The old ones expire the first february 2022.
* Funded by CD64 Pyrénnées-Atlantiques
> Update IGN URL search Adress

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/qgis-projects/tests/tests_dataset.sql
In the attribute table tool, when you select a feature in the parent layer, and one or several features in the child layers, Lizmap should update the child table the right way. This PR fixes a bug.
* Ticket : #2680
* Funded by Valabre
> Attribute table - Fix the link of selected features between a parent and a child layer

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
The refactoring in lizmap project classes introduced a regression in the way to parse the ValueMap widget config.
* Funded by: Valabre
> [Bugfix] ValueMap widget parsing config

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- tests/end2end/cypress/integration/form_edition_all_field_type-ghaction.js
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/form_edition_all_field_type.qgs.cfg
- tests/qgis-projects/tests/tests_dataset.sql
In the form widget, when:
* there is a `text` field configured with a "Value relation" widget, 
* with the option `allow multiple` activated
* using a `text` field in the referenced layer for the code checkbox
QGIS adds double quotes around the text values, such as `{"one_value", "second_value"}`.
We need to remove these double-quotes for setting correctly the corresponding checkboxes.
Cypress test added.
Funded by #3liz
> Editing - Fix the value relation widget with multiple text values on feature modification

- lizmap/modules/view/controllers/media.classic.php
We need to ensure the SVG files are sent with the correct mime type `image/svg+xml`
* Funded by Valabre
> Media - Fix the mime type for SVG files: should be image/svg+xml

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
The QGis XML Option contains a type attribute that contains the QVariant type name.
* QgsXmlUtils::writeVariant https://github.com/qgis/QGIS/blob/master/src/core/qgsxmlutils.cpp
* QMetaType::Type https://github.com/qt/qtbase/blob/5.6/src/corelib/kernel/qmetatype.cpp
Funded by 3liz
> Convert QGis XML Option value based on type attribute

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
The GetProjectConfig was send as plain/text instead of application/json.
This commit fixes it.
> GetprojectConfig as application/json instead of plain/text

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
For OGC Requests, VERSION parameter is mandatory except for GetCapabilities requests.
> OGC Requests: Check VERSION parameter

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/www/assets/jelix/js/jforms_jquery.js
- tests/end2end/cypress/integration/form_advanced-ghaction.js
- tests/qgis-projects/tests/form_advanced.qgs
Lizmap added an empty value to the value relation list if the field is required. This has been removed form QgisFormValueRelationDynamicDatasource.
> [Bugfix] For Value Relation, Empty value is added for required fields

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/App/AppContextInterface.php
- lizmap/modules/lizmap/lib/App/JelixContext.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- tests/units/testslib/ContextForTests.php
Lizmap provides user login and groups to QGIS Server through headers or parameters. The user private group was in the user group list.
> Fix Remove user private group from request to QGIS Server

- lizmap/modules/lizmap/lib/Request/Proxy.php
For OGC WXS, the version parameter is mandatory except for GetCapabilities request.
For OGC WXS, the request can be done with an XML Request. The root document contains a service attribute and can contain a version attribute.
The version has to be extracted from XML request to be checked before request processing.
* Linked to https://github.com/3liz/lizmap-web-client/pull/2769
> Fix: Extract Version from OGC XML Request

- lizmap/modules/lizmap/classes/qgisServer.class.php
The request to QGIS Server to get plugins data is not QGIS Project dependant.
The requests have not to be perform each time lizmap needs to get the plugins list.
> Fix: Use cache for QGIS Server plugins data

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
Implement a static method Proxy::getHttpStatusMsg to get the HTTP Status Message from code to provide the right HTTP Status Messages in lizmap service responses.
> Fix: HTTP Status Messages for lizmap servcie responses

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
if we run a compiled QGIS, it's nice to know which commit we are running from the LWC interface.
> QGIS - Display the server commit ID if available

- lizmap/www/assets/js/popupQgisAtlas.js
The goal is not be able to customize a label which will be overriden later by AtlasPrint anyway later :
> UX - Do not show custom label if some label IDs are protected and managed by LWC

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
* Ticket : fix #2755
UX - Review the error message about the HTTP code from QGIS Server
Before, we could have a 200 HTTP from QGIS Server, according to screenshots in #2755 which is misleading for users.
> UX - Review the error message about the HTTP code from QGIS Server

- lizmap/plugins/configcompiler/lizmapconfig/lizmapconfig.configcompiler.php
- lizmap/var/config/mainconfig.ini.php
The assetsRevision parameter was stored into the lizmap section, but was readed from the urlengine section. It is not consistent.
> Fix the assets revision mecanism

- lib/jelix-www/js/jforms/imageSelector.js
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/www/assets/css/map.css
- lizmap/www/assets/jelix/js/jforms/imageSelector.js
Support of the value `auto` for width or height of the dialog. The dialog then have the window size (with a maximum width/height value : 1024).
* Ticket : fix #2766
> Fix the image dialog size on tiny screens

- lizmap/modules/lizmap/controllers/edition.classic.php
The feature id can be equal to 0 and it is valid but the edition controller does not authorize edition in this case.
Also replace `and` by `&&` and `or` by `||`.
> [Bugfix] Edition: update and delete is not authorized for feature id 0

- lizmap/modules/lizmap/lib/Project/Project.php
- tests/units/classes/Project/ProjectTest.php
Remove the `strtolower` on `filterAttribute` because the field name can be upper case and it has to stay like it is defined in the database.
* Funded by Terre de Provence Agglomération
> Filter by attribute: the attribute can be upper case

- lizmap/modules/lizmap/classes/qgisFormControl.class.php
#2862 and cypress tests reveal a regression in the way boolean nullable is displayed.
> [Bugfix][Edition] Boolean nullable displayed as menulist in release_3_4

- lizmap/modules/lizmap/lib/Form/QgisForm.php
After #2856 merging, updated comments about ValueRelation empty value for menulist and checkboxes.
> [Edition] Update comments about ValueRelation EmptyValue

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
The Feature Bounding box was missing when lizmap building the GeoJSON from Postgres.
> [Bugfix] WFS GetFeature request from Postgres - add BBox

- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
- tests/qgis-projects/tests/form_edition_value_relation_field.md
* Using cy.log instead of cy.context
* Extend cypress filter by geometry
* Extend cypress initial form state to cover manually tests
* Update manually tests because of cypress overage
> [Tests] end2end and manually: coverage cypress form value relation tests

- lizmap/modules/admin/classes/config.listener.php
- lizmap/modules/admin/controllers/qgis_projects.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list.tpl
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/view/zones/ajax_view.zone.php
- lizmap/modules/view/zones/main_view.zone.php
- lizmap/www/assets/js/admin/activate_datatable.js
- tests/units/classes/Project/ProjectConfigTest.php
This PR add a new page in the admin panel showing the list of published projects in a dynamic table. 
* **visible properties**: repository, project name, modification date, projection, layer count, qgis desktop version, lizmap plugin version, acl groups
* Some colors have been used depending on the values to help the admin see what must be corrected:
* QGIS version: 
* lightyellow if the version is old compared to the QGIS Server (minor version difference > 6)
* lightcoral if the QGIS desktop version is above the installed QGIS Server version
* Layer count: 
* lightyellow if above 100, 
* lightcoral if above 200
* Projection: 
* lightcoral if it is a user defined projection
* **Tooltips** have been added to show more information on hover
* Repository: shows the label
* Project: shows the …
> Administration - New page showing a list of projects and their properties

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- phpstan-baseline.neon
- tests/units/classes/lizmapWktTest.php
- tests/units/classes/qgisExpressionUtilsTest.php
Multi geometries like multi point, multi linestring and multi polygon were not supported.
So expression based on layer with multi geometries does not work at all.
* Funded by Terre de Provence Agglomération
> [Bugfix] Lizmap WKT parser: support Multi 

- lizmap/www/assets/js/map.js
- tests/end2end/cypress/integration/print.js
Because some browser like Firefox opens PDF content in the internal PDF viewer, lizmap has to force to open GetPrint content in a blank window whixh is a new tab.
> [Bugfix] Force to open GetPrint in blank window

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/testslib/LayerWFSForTests.php
- tests/units/testslib/WFSRequestForTests.php
fixes #2770
In the WFS OGC standard FEATUREID and BBOX parameters cannot be mutually set
but in Lizmap, the user can do a selection, based on featureid, and can request
a download, a WFS GetFeature request, based on this selection with a restriction
to map extent, sofeatureid and bbox parameter can be set mutually and featureid
parameter needs to be transform in an expression filter.
A parameter `FORCE_QGIS` has been introduced for GetFeature to compare lizmap
postgres GetFeature response and QGIS Server GetFeature response.
> [Bugfix] attribute table - doesn't export when a selection is active

- lizmap/modules/dataviz/classes/datavizConfig.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/end2end/cypress/integration/requests-getprojectconfig-ghaction.js
The WPS module reuses the lizmap buildPlot method which need the locale from config.
Fixes https://github.com/3liz/lizmap-wps-web-client-module/issues/26
> [Bugfix] Dataviz: provide a minimu config with locale for WPS

- tests/end2end/cypress/integration/projects_homepage-ghaction.js
- tests/end2end/cypress/integration/requests-getprojectconfig-ghaction.js
- tests/end2end/cypress/integration/requests-service-ghaction.js
- tests/qgis-projects/tests/hide_project.qgs
- tests/qgis-projects/tests/hide_project.qgs.cfg
New tests to check the lizmap config options hide project.
The project is empty: no layers, no other config.
Funded by 3Liz
> [Tests] e2e: check config.options.hideProject: "True"

- lizmap/www/assets/js/map.js
On touch screen, the getFeatureInfo request is not send to the server because the pixel tolerance for click is too small.
Funded by 3Liz
> [Bugfix] GetFeatureInfo click pixel tolerance

- lizmap/www/assets/js/popupQgisAtlas.js
fixes #2995
When querying (GetFeatureInfo) from a different WMS server (in my case GeoFoncier), I've got a javascript error :
```
Uncaught TypeError: $(...).find(...).val() is undefined for the file PopupQgisAtlas. Line 16
```
Funded by 3Liz
> [BUGFIX] Atlas print link error when no feature id found

- assets/webpack.common.js
- lizmap/www/assets/js/edition.js
- lizmap/www/assets/js/map.js
Use terser in Webpack to minify our JS files.
That saves more than 400Ko!
before terser : 649,6 Ko
after terser : 246,7 Ko
Funded by 3Liz
> Minify JS files

- lizmap/modules/view/controllers/default.classic.php
fixes #3003
In case of OnlyMaps, the ACL was not check.
Funded by 3Liz
> [Bugfix] infinite redirections when no access to the default project in the 'onlyMap' mode

- CHANGELOG-3.6.md
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/OGCResponse.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
- tests/end2end/cypress/integration/requests-service-ghaction.js
- tests/units/classes/Request/WMSRequestTest.php
Add the [ETag HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) for some service responses with `Cache-Control: no-cache` header.
The responses for GetProjectConfig, GetCapabilities and GetProj4 have an Etag HTTP header
> Lizmap service etag

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/end2end/cypress/integration/key_value_mapping-ghaction.js
Do not build the attribute table when refreshing attribute table
* The dataTable has been already build so, the data has only to be refreshed.
* Also no need to refetch describefeaturetype and key/values.
Speed up emptyLayerFilter and refreshing the tables.
Funded by 3Liz
> [Bugfix] Attribute table refreshing

- lizmap/modules/lizmap/lib/Project/Project.php
If there is no edition layers for the user, the `editionLayers` of the `$configJson` is `unset`.
So when lizmap removed layers from config to provide only available configuration for user, the code does not check if the `editionLayers` of `$configJson` is still here.
Funded by 3Liz
> fix: The `editionLayers` of `$configJson` in `Project::getUpdatedConfig` can be `unset`

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/forms/config_services.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/config.tpl
- lizmap/modules/admin/templates/config_services.tpl
- lizmap/modules/lizmap/classes/lizmapServices.class.php
In order to help to fill fields related to email, this patch adds some explainations for the user.. The explainations are differents, depending if we show sensitive informations or not, or if there is a SMTP configuration or not.
Funded by 3Liz
> Email configuration: add more explainations to fill correctly data

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/forms/config_services.form.xml
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
Linked to #2972 @mdouchin
It would be nice to hardcode as well the QGIS version, so we don't need to translate in Transifex everytime we change the QGIS version (and Lizmap server plugin version as well)
> UI - Update to Lizmap server plugin and its version

- CHANGELOG-3.6.md
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
* Before opening a QGIS project, Lizmap is now checking that :
* Lizmap QGIS server plugin is running with a minimum required version
* QGIS server version is running with at least 3.10
* These two versions are hardcoded in the source code and updated when a new version of Lizmap is released
Fix #2972 and linked to #2058
Funded by 3Liz
> ACL - Check that QGIS server is OK before opening a project

- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
Master is broken with cypress
Related to comment https://github.com/3liz/lizmap-web-client/pull/3162#issuecomment-1210993700
> Server info - always fetch metadata from qgis server even if we are not an admin

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/cypress/integration/requests-getcapabilities-ghaction.js
- tests/end2end/cypress/integration/requests-service-ghaction.js
* Use version for OGC GetCapabilities cache key
* OnelineResource links in WMS GetCapabilities
* Version required for GetSchemaExtension
Fixes #3128
Funded by 3Liz
> fix(request): OGC GetCapabilities with tests

- lizmap/modules/dataviz/controllers/service.classic.php
Ticket :  fix #3186 
This PR is related to the open issue https://github.com/3liz/lizmap-web-client/issues/3186 and fix a syntax error in the service.classic.php file of the dataviz module.
> fixed syntax error in in dataviz module

- lizmap/modules/admin/controllers/maps.classic.php
The PHP method `realpath` returns canonicalized absolute pathname. realpath() expands
all symbolic links and resolves references to /./, /../ and extra / characters in the
input path and returns the canonicalized absolute pathname.
The `\Jelix\FileUtilities\Path::normalizePath` resolves references to /./, /../ and
extra / characters in the input path.
In Lizmap, the rootRepositories config parameter could be a symbolic link, in which find
Lizmap repositorires. So Lizmap does not need to expand symbolic link in the admin maps
controller, it only needs to normalize path.
Funded by Ingerop
> fix(admin): Use normalizedPath instead of realpath to check rootRepositories

- lizmap/modules/admin/controllers/maps.classic.php
Backport #3202
The PHP method `realpath` returns canonicalized absolute pathname. realpath() expands
all symbolic links and resolves references to /./, /../ and extra / characters in the
input path and returns the canonicalized absolute pathname.
The `\Jelix\FileUtilities\Path::normalizePath` resolves references to /./, /../ and
extra / characters in the input path.
In Lizmap, the rootRepositories config parameter could be a symbolic link, in which find
Lizmap repositorires. So Lizmap does not need to expand symbolic link in the admin maps
controller, it only needs to normalize path.
Funded by Ingerop
> [Backport release_3_5] fix(admin): Use normalizedPath instead of realpath to check rootRepositories

- CHANGELOG-3.7.md
- assets/src/legacy/filter.js
It was already possible for dates in the previous versions.
Now a second field can also be used for the numeric form widget.
It is useful when the layer features contain two fields describing
a minimum and maximum value of the same property (ex: age, width, depth, etc.)
Funded by Terre de Provence Agglomération https://www.terredeprovence-agglo.com/
Linked to https://github.com/3liz/lizmap-plugin/pull/442
> Form filter - Allow to use a second field for the numeric type

- CHANGELOG-3.6.md
- assets/src/legacy/map.js
Also each button only toggle its own children popup group
This feature has been lost by mistake in https://github.com/3liz/lizmap-web-client/commit/b2e248be79154446a7d0742760ba6ecad5118cf7
Fix #2759
Fix #2435
Funded by 3Liz
> Fix: button to toggle compact/explode table view in popups

- lizmap/modules/lizmap/lib/Project/Project.php
quick & dirt fix to prevent php error (force object cast)
must be related to a php8 behavior change in property_exists
fix https://github.com/3liz/lizmap-web-client/issues/3171
not sure of labels ...
> fix Unknown group id leads to php error while loading project

- tests/Makefile
- tests/add_server_plugins.sh
Use qgis-plugin-manager to install plugins
Drawback for now, it's only downloading plugin released version, based on a tag.
> Tests - Use qgis-plugin-manager to install all plugins

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
Use primary key value instead of id column which could not exist
Funded by 3Liz
> Fix: Filter by user edition in popup

- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/end2end/cypress/integration/filter_layer_data_by_polygon_for_groups-ghaction.js
- tests/end2end/cypress/integration/form_advanced-ghaction.js
- tests/end2end/cypress/integration/form_edition-ghaction.js
- tests/end2end/cypress/integration/form_edition_reverse_geom-ghaction.js
- tests/end2end/cypress/integration/form_edition_value_relation_field-ghaction.js
- tests/end2end/cypress/integration/form_edition_without_creation-ghaction.js
- tests/end2end/cypress/integration/popup-ghaction.js
Replace `cy.get('#map').click` to `cy.mapClick`
Funded by 3liz
> [Tests] e2e cypress: Switch to `mapClick` helper

- lizmap/modules/view/controllers/media.classic.php
- phpstan-baseline.neon
PHP `pathinfo` returns an associative array containing the following elements is returned: dirname, basename, extension (if any), and filename. https://www.php.net/manual/en/function.pathinfo.php
If the basename of the path starts with a dot, the following characters are interpreted as extension, and the filename is empty
Funded by 3Liz
> Tests: PHPSTan - pathinfo always returns filename

- .github/workflows/e2e_tests_cypress.yml
I guess to remove all warnings and deprecation notices on GH Action, CF https://github.com/3liz/lizmap-web-client/actions/runs/3386817243
I'm curious why dependabot didn't detect this action... We were on a old version.
@nboisteault I took the opportunity to look for cypress as well, ok for you ?
> GH Action - Upgrade cypress action to 4.2.0

- lizmap/modules/lizmap/classes/lizmapLog.listener.php
When Lizmap is behind a reverse proxy (this is often the case when running nginx + php-fpm), REMOTE_ADDR does not contain the user IP but the server IP.
We should use the method `jRequest::getIP()` which returns the real ip of the user.
Funded by 3Liz
> Fix: Ip into logs is not the real ip

- lizmap/modules/lizmap/lib/Form/QgisFormControlProperties.php
- tests/units/classes/Form/QgisFormControlPropertiesTest.php
- tests/units/classes/Project/QgisProjectTest.php
[Bugfix] The QGIS Form Control Propertie names can change
For exemple the `AllowNull` option in QGIS `RelationReference` widget can be:
* `AllowNull`
* `allowNull`
* `AllowNULL`
We try to quickly fix it and add unit tests.
Funded by Cartophyl https://cartophyl.com/
> Fix form control properties allow null

- docker/README.md
- docker/update-config.php
During the startup, especially for the first start when the installer is launched for the first time and SQL table should be created, the container should wait after the Postgresql server, before launching the installer.
If the profiles.ini.php is configured to use a Postgresql database, the container tries to connect to the database 10 times before returning an error.
Funded by 3Liz
> [docker] wait after the Postgresql server before installing lizmap

- .github/workflows/cron_e2e.yml
- .github/workflows/e2e_tests.yml
Before, we could only run E2E on the default branch of GH, aka master.
Now, we are able to run E2E on master, release 3.6 and release 3.5.
Funded by 3Liz
@nboisteault Ok for you ?
> GH Action - Experiment cron for all release branches

- assets/src/legacy/action.js
- lizmap/modules/action/classes/actionConfig.class.php
- lizmap/modules/action/controllers/service.classic.php
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
- tests/qgis-projects/tests/feature_toolbar.qgs.action
* It allows to easily use the same action for a list of layers
* It prepares the possibility to define action `scope`: project, layer or feature
* The old configurations will be automatically converted into the new one
* It removes completely the dependany to jQuery
The expected JSON was an object of layerID => action.
It will now be an array of action objects:
```json
[
{
"name": "buffer_500",
"title": "Buffer 500m around this object",
"scope": "feature",
"layers" : [
"parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111",
"tramway_lines_4215fd0b_5136_4c19_b3ee_d1617f8df8ea"
],
"confirm": "Do you really want to show the buffer ?",
"icon": "icon-leaf",
"options": {
"buffer_size": 500,
"other_param": "yes"
},
"style": {
"graphicName": "circle",
"pointRadius": 6,
"fill": true,
"fillColor": …
```
> Module Action - Change the format of the JSON configuration file

- assets/src/legacy/map.js
- lizmap/www/assets/css/map.css
@rldhont I have set `45vh` for the content height. Using `calc()` we could have the mini-dock with a max-width of 50% the map's height but I don't think we need that much precision.
Funded by 3Liz
> Update mini-dock size with CSS

- assets/src/legacy/map.js
The clean name layer was used for children getFeatureInfo instead of a WMS Layer name which is shortName or name.
Funded by Terre de Provence Agglomération https://www.terredeprovence-agglo.com/
> [Bugfix] Use wmsName and not clean name for Children GetFeatureInfo

- docker/Dockerfile
- docker/lizmap-entrypoint.sh
This is an attempt to fix #3370 
Updating to 3.6.0 when using a non-standard (not 1000) UID and GID, the container does not start.
I also tried this on a clean stack.
The first error I'm getting is:
`/bin/lizmap-entrypoint.sh: line 29: groupmod: not found`
lizmap-entrypoint.sh is calling, in some cases, for `groupmod` and `usermod`, which are not installed in the base image used. Those can be installed with the package `shadow`.
Once they are installed, I'm getting a different error:
`groupmod: invalid group ID 'groupphp'`
I assume, and this is a long shot, that this is due to a typo in the entrypoint, which refers to APP_GROUP_ID and APP_USER_ID instead of LIZMAP_GROUP_ID and LIZMAP_USER_ID
Those two variables should be empty, and as such the command that runs is `groupmod -g groupphp`, …
> Container does not start with non-standard UID/GID - attempt to fix #3370

- lizmap/modules/dataviz/classes/datavizConfig.class.php
- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/dataviz/controllers/service.classic.php
- lizmap/modules/dataviz/locales/en_US/dataviz.UTF-8.properties
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Server/Server.php
- tests/end2end/cypress/integration/dataviz-ghaction.js
When you configure a plot in QGIS Lizmap plugin, you cannot yet test how the plot will be rendered. 
This modification allows any client, like a Python script, to use the Lizmap Web Client `dataviz` service as an API.
This API is only available for authenticated users. You can at present only use **Basic authentication**.
The client is able to request Lizmap Web Client and get the plot data ready to be directly used with the Plotly JavaScript or Python library.
If LWC main URL is `http://lizmap.local:8130/` The **URL** of the dataviz API is : `http://lizmap.local:8130/index.php/dataviz/service?`
The preferred request method is **POST**, and the data should be sent in the body as a JSON object, 
with the keys `repository` (Lizmap repository code), `project` (the Lizmap project code) 
and …
> Dataviz - Allow to post a JSON plot config to get the plot

- lizmap/modules/admin/templates/project_list_zone.tpl
The QGIS projects table displayed in the administration panel could be broken depending on the QGIS projects data.
This modifications fix this issue by escaping the project data used in the table: 
layer datasource, project description, QGIS Server logs, etc.
Funded by 3liz
> Admin - QGIS projects: escape the project data used in the HTML table

- assets/src/components/Digitizing.js
- lizmap/modules/view/templates/map_draw.tpl
- lizmap/www/assets/css/map.css
* Bootstrap `hide` CSS class are overwrite by digitizing specific CSS
* Save button was not hidable
Funded by 3Liz
> [Bugfix] Hiding some digitizing buttons

- CHANGELOG-3.7.md
- lizmap/modules/view/classes/view.listener.php
- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- lizmap/modules/view/templates/main.tpl
- lizmap/modules/view/templates/map_menu.tpl
Fixes #1073
* Let the application name alone in the landing page
* Add a new string to translate: Landing page
* Put the page title in the second title in the header
Old landing page
New landing page
Funded by 3Liz
> Update the lizmap landing page title

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
The LWC WFSRequest class did not take into account the parameter [SRSNAME](https://docs.qgis.org/3.22/en/docs/server_manual/services/wfs.html#wfs-getfeature-srsname) for the WFS GETFEATURE query when it has to build the SQL request.
fixes #3194
> [Bugfix] WFS: No PostGIS features returned if map projection != layer.projection

- lizmap/modules/lizmap/templates/wmts_capabilities.tpl
This PR add the mandatory xml head `<?xml .. ` to the generated WMTS Capabilities response  (assuming UTF-8 encoding) 
it prevent browser to detect error as above
Funded by 3liz
> add XML header to WMTS capabilities

- assets/src/legacy/attributeTable.js
- assets/src/legacy/filter.js
In some unknown contexts, the `layerName` option is not present any more in the QGIS XML project file in the definition of the `ValueRelation` configuration for a form field.
When Lizmap Web Client displays the form filter or an attribute table, it tries to get the labels for the columns using a Value relation form field. This causes Lizmap to fail to open the attribute table. 
This PR uses the layer ID instead of the `layerName`, which is always present and is by the way a more robust method to get the QGIS layer.
Funded by 3liz
> Attribute table - Fix no display of table with value relation fields with no layer name

- lizmap/www/assets/css/admin.css
The anchor color in the projects table is the same as the background selected line.
Old UI
New UI
Funded by 3liz
> UI admin: Change anchor color for selected line in projects table

- tests/end2end/cypress/integration/legend-ghaction.js
- tests/end2end/cypress/integration/print-ghaction.js
- tests/end2end/cypress/integration/treeview-ghaction.js
- tests/end2end/cypress/plugins/index.js
- tests/end2end/cypress/support/function.js
- tests/end2end/package.json
Cypress - Fix tests for QGIS 3.28
The differences with QGIS 3.28 are : 
* Some text shifting in the PNG
* New `~` characters from https://github.com/qgis/QGIS/pull/50256
* Text in now polygonized in a SVG export
> Cypress - Fix tests for QGIS 3.28

- lizmap/modules/lizmap/commands.php
- lizmap/modules/lizmap/controllers/database.cmdline.php
- lizmap/modules/lizmap/lib/Commands/DbMigrateLog.php
- lizmap/modules/lizmap/lib/Commands/DbMigrateUsers.php
`database:migratelog` and `database:migrateuser` jelixcommand alternative for `console.php`
Funded by 3liz https://www.3liz.com/
> database migrate commands in console.php

- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/www/assets/js/admin/activate_datatable.js
Convert lizmap plugin  Version to unified string sortable (0X.0Y.0Z) , datatables render as human readable  
From 
Funded by 3liz
> Admin : Projects Panel convert lizmap plugin version from int to sortable string

- assets/src/legacy/map.js
When you click on the zoom to feature button before a WFS GetFeature request has been performed on the layer, the zoom goes to far away.
Funded by Conseil Départemental du Calvados https://www.calvados.fr
> [Bugfix] Zoom to feature (from popup) goes to far away

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
Fix #3486
From 
To 
having a kind of checklist help the end user.
@nworr Maybe I'm missing a tiny thing ?
As soon as I switch from 
```
<li>{jlocale "admin.server.information.qgis.error.fetching.information.qgis.version", array($minimumQgisVersion)}</li>
```
to
```
<li>{jlocale "admin.server.information.qgis.error.fetching.information.qgis.version.html", array($minimumQgisVersion)}</li>
```
I got
it looks like a copy/paste from https://github.com/3liz/lizmap-web-client/blob/450bf0bbe2551e76734e32c31ca3fc65f1ccee39/lizmap/modules/admin/templates/project_list_zone.tpl#L241
> UX - Improve debug messages about the QGIS server installation

- assets/src/legacy/map.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
To speed up WFS getFeature request to get selected features, the geometry bounds is provided by the BBOX parameter to restrict the request to this bounding box. But if the bounding box is empty, the request returns no features.
So to get feature in intersection with a Point the bounding box has to be extend to not be empty.
> [Bugfix] Selection by Point - The bbox is empty

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- tests/units/classes/lizmapWktTest.php
PHPStan - PHP Static Analysis Tool 1.10.1 provides an error message on lizmapWkt class:
```bash
Error: Negated boolean expression is always false.
------ --------------------------------------------------------------------
Line   lizmap/classes/lizmapWkt.class.php
------ --------------------------------------------------------------------
135    Negated boolean expression is always false.
💡 Because the type is coming from a PHPDoc, you can turn off this
check by setting treatPhpDocTypesAsCertain: false in your
../phpstan.neon.
------ --------------------------------------------------------------------
```
The error is due to a double `is_numeric` check on the same value. lizmapWkt::parsePoint was checking twice if the first coordinates is a numeric and not if the two coordinates are …
> [Bugfix] lizmapWkt class does not well check point as numeric values

- tests/end2end/cypress/integration/requests-service-ghaction.js
The test about the proj4 string provided by lizmap was to strict.
> [Tests] e2e: Enhancing the way to check proj4 string

- lizmap/composer.json
- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/OGCResponse.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/ProxyResponse.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- phpstan-baseline.neon
QGIS Server send WFS GetFeature response by chunck.
Lizmap performs WFS GetFeature request on PostGIS layers whitout sending request to QGIS Server.
To speedup WFS GetFeature request and reducing its memory footprint, we decide to stream response to client and to use Guzzle Stream to transfer the response from QGIS Server
> Using Guzzle Stream to speed up WFS GetFeature

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/var/config/lizmapConfig.ini.php.dist
This property should not be considered as a sensitive parameter. We show also the email used to send emails, even if we keep as a non editable value in sensitive mode.
Funded by 3liz
> Admin: allow to edit the name for the sender email

- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/lizmapServicesTest.php
The https://github.com/3liz/lizmap-web-client/pull/3502 Admin: allow to edit the name for the sender email introduces a regression in PHP unit tests.
Replace assertObjectNotHasAttributebecause it is deprecated and will be removed in PHPUnit 10.
> [Tests] Fix PHP unit and replace deprecated assert

- assets/src/legacy/map.js
The QGIS Server WMS Filter parameter has to start with the wms layername to identify the layer to apply filter. The layername has to be the same the one for LAYERS and QUERY_LAYERS parameters.
Funded by Terre de Provence Agglomération https://www.terredeprovence-agglo.com/
> [Bugfix] WMS GetFeatureInfo Filter: the layer name has to be the same

- lizmap/modules/view/controllers/media.classic.php
Reset the fileName jResponseBinary property because Lizmap update the CSS content to replace url link.
Funded by AUDELOR
> [Bugfix] Regression in view/media/getCssFile

- lizmap/modules/admin/zones/project_list.zone.php
* It seems running QGIS server 3.22, we need project with 3.14 to see them in yellow 
* Only QGIS dev are used to see odd number about QGIS version
> Fix version number when displaying strings about the project table

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
In the Lizmap plugin, Spatialite layers for edition capabilities has been disabled for a long time.
So I think this code can be removed ?
Or am I missing something ?
If correct, this can be backported to LWC 3.5.
> Remove code about spatialite and edition of layer, not supported for a long time in the plugin

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The user filter based on geometry can be configure to be applied on centroid. The geometry checking for edition was not applying centroid.
> [Bugfix] Edition: Apply centroid is config for checking geometry

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
The login and polygon filters can be applied only for edition. The editing context was not set for requests coming from edition form.
The polygon filter was not provided by `qgisExpressionUtils::getExpressionByUser`, so it was not applied for value relation with expression.
When checking the submitted feature, filter by login has to be tested without filter by polygon which was check by `checkFeatureAgainstPolygonFilter` method.
Funded by Conseil Départemental du Calvados https://www.calvados.fr/
> [Bugfix] Apply editing context for requests in edition form

- assets/src/components/Print.js
The shortname is now building by the QGIS Desktop lizmap plugin. The Print module was not check the shortname for baselayers.
Funded by CA du Grand Narbonne https://www.legrandnarbonne.com/
> [Bugfix] GetPrint: Use baselayer shortname

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/config_theme.tpl
It would be convenient to have color pickers instead of text input where people don't always know what to put in.
It is just a quick draft to discuss.
By default color pickers have their default value to `#000000` (black) so if someone saves the form without changing any colors this color will apply to all fields. So we need to display default values when opening the form.
We could use CSS custom properties. It would also allow to use them in custom themes defined in `media`.
Funded by 3Liz
> Add color picker to theme edition in admin

- assets/src/modules/Digitizing.js
Manually backport 78871e3
Authored by: @nboisteault
> [Backport release_3_6] Fix: erase draw in localstorage 

- assets/src/modules/Digitizing.js
Manually backport https://github.com/3liz/lizmap-web-client/commit/78871e37f2e94bd15c88b2207876da30f8237077
Authored by: @nboisteault
> [Backport release_3_5] Fix: erase draw in localstorage

- assets/src/legacy/map.js
Removing all occurrences of `lizmapExternalBaselayers` which was the key in the CFG file.
This will allow me to remove quite a few code as well in the plugin soon.
This feature is deprecated since 2019 in the QGIS desktop plugin with a warning : 
* Ticket https://github.com/3liz/lizmap-plugin/issues/121
* Commit https://github.com/3liz/lizmap-plugin/commit/a69b46ef399be7696b4dc36b64bcaedc73ce7183 marking as deprecated as in the screenshot above : https://github.com/3liz/lizmap-plugin/issues/121#issuecomment-618914308
> Remove code about external base layer which has been deprecated since 2019

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
Follow up from PR #3483 and commit a813bd6bb23a6c840f395217625d91652965c33c
* Do not display "Atlasprint : not found" if it's wasn't installed
* Invite the user to remove it ? The only drawback of this is if the user really wants it, using some direct call to QGIS server to the AtlasPrint API ? But I think we really want to not maintain it anymore, so it should be fine according to me.
Before merging this, snap and prod server mustn't install the plugin. Let's wait before removing.
> UX - Do not display atlasprint anymore if it is not installed

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
The parameters sent to QGIS Server were not well formated which prevented the filter from beeing applied on the related layers
* Add spaces between the values in the SQL "IN" clause
* Remove the unneeded layer name as a prefix for the EXP_FILTER parameter
Ticket : # 
Funded by 3Liz
> Data filtering - Fix the filter not applied to the children layers

- lizmap/modules/lizmap/classes/lizmapProject.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisServer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Project/Project.php
Since LWC 3.6, we know that the plugin is installed and updated before we open a map, so we can remove some code...
The idea is to remove the GET request to QGIS server : `SERVICE=LIZMAP&REQUEST=GetServerSettings`
It's handled by the JSON metadata.
> Remove deprecated call to the Lizmap server plugin

- assets/src/modules/config/BaseLayer.js
- assets/src/modules/config/Layer.js
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/js-units/data/montpellier-config.json
- tests/js-units/node/config/baselayer.test.js
- tests/js-units/node/config/layer.test.js
The external access property of layer config can contain XYZ and WMTS 3857 parameters, extracted dynamically from QGIS XML.
layerType is also added to layer config information.
> Config: Add layerType and extract xyz and WMTS 3857 datasource parameters

- assets/src/modules/Config.js
- assets/src/modules/config/LayersOrder.js
- tests/js-units/node/config.test.js
- tests/js-units/node/config/layersOrder.test.js
Continuing to build the JavaScript API by defining a way to access layers order.
The `Config.layersOrder` provides the layer names displaying order like in QGIS:
* The first one in this list is the top one in the map
* The last one in this list is the bottom one in the map
> [JavaScript] Extract layers order from config and WMS Capabilities

- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- lizmap/plugins/formwidget/input_htmlbootstrap/input_htmlbootstrap.formwidget.php
- tests/end2end/cypress/integration/form_edition_all_field_type-ghaction.js
- tests/end2end/playwright/edition-form.spec.js
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
Overload the input_htmlbootstrapFormWidget : outputContol method
Check if datatype is integer and use input type : number
by default, input type is text
browser will perform live validation and add spin button
Ticket : #2992
> input type number in edition form when datatype is number

- assets/src/modules/WMS.js
- assets/src/modules/action/Symbology.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/Symbology.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/symbology.test.js
* Defined a new module state Symbology to defined classes fro describing layer tree symbologies and method to build default icon or layer tree symbology
* Defined a new property for tree layer to get an icon source
* Defined a new updatable property to get and define tree layer symbology
* Defined new properties to get symbology children
* Defined new methods to find layers from tree group
* Defined a new module action symbology to update tree layers symbology
> [JavaScript] Symbology and update LayerTree 

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
In OGC WMS standard the request `GetLegendGraphics` and `GetLegendGraphics` are the same, but the right name is `GetLegendGraphic` without an `s`.
> [Bugfix] WMS GetLegendGraphic is the right request name not GetLegendGraphics

- CHANGELOG-3.7.md
- assets/src/components/FeatureToolbar.js
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
When a "parent" layer is in relationship with "child" layers, and when new objects can be created for these child layers with the editing tool, a new button is added in the popup toolbar of each parent object. This button will allow to select the child layer and then create a new item related to the popup parent object. 
Ticket : #1958 
Funded by [Valabre](https://www.valabre.com) & [SDEC Energie](https://www.sdec-energie.fr/)
> Popup/Editing - Add a combobox in the popup to allow creating a new child feature

- assets/src/legacy/map.js
In desktop view, the locate by layer feature use layername as a placeholder for the autocomplete .
In mobile mode : no autocomplete, only select/options
this PR add the layer name as an option label for the 1st option (value=-1, unselected) to behave like a placholder
fix #3725 
fix #3209
From this :
Funded by 3Liz
To :
> use layer name as option label for locate-by-layer selector in mobile

- assets/src/modules/state/Layer.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/MapLayer.js
- tests/js-units/node/state/layer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
For all instances of `LayerVectorState`, `MapLayerState` and `LayerTreeLayerState`, the properties `hasSelectedFeatures` and `isFiltered` provides a quick access to the status of the layer.
> [JavaScript] Layer Property to know if the layer has selected features and is filtered

- assets/src/modules/State.js
- assets/src/modules/state/BaseLayer.js
- assets/src/modules/state/Layer.js
- assets/src/utils/EventDispatcher.js
- tests/js-units/node/state.test.js
- tests/js-units/node/state/baselayer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
A new Module State BaseLayer has been provided to manage selected baselayer.
The `lizMap.mainLizmap.state` dispatches the events:
* `map.state.changed`
* `baselayers.selection.changed`
* `group.visibility.changed`
* `layer.visibility.changed`
* `layer.style.changed`
* `layer.symbol.checked.changed`
* `layer.selection.changed`
* `layer.selection.token.changed`
* `layer.filter.changed`
* `layer.filter.token.changed`
> [JavaScript] Module State BaseLayer and Class state extends EventDispatcher

- assets/src/modules/state/Layer.js
- assets/src/modules/state/Symbology.js
- tests/js-units/data/quickosm-road-legend.json
- tests/js-units/node/state/layer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
- tests/js-units/node/state/symbology.test.js
* The parentRuleKey is used to build the rule based symbology tree
* The layer visibility changed when all the rules are disabled
* the symbology directly build the legend ON/OFF WMS parameters
> [JavaScript] Managed Rule based Symbology like QGIS

- assets/src/legacy/map.js
- assets/src/modules/SelectionTool.js
- tests/end2end/cypress/integration/selectionTool-ghaction.js
The OpenLayers 7 GML3 writer inverses axis if the SRS defined but it is not supported by QGIS `geom_from_gml` expression method.
To speed up WFS getFeature request to get selected features, the geometry bounds is provided by the BBOX parameter to restrict the
request to this bounding box. But if the bounding box is empty, the request returns no features.
Funded by 3Liz https://3liz.com/
> [Bugfix] Selection by Geometry

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
This PR fixes two bugs
* The request made by LWC to lizmap server plugin was sent  using GET instead of POST. This triggered issues for heavy polygon filters
* The method `isFeatureEditable` of the `qgisVectorLayer` class, which detected that a feature was editable or not for the authenticated user, did not take into account the new behaviour of the method `qgisExpressionUtils::getExpressionByUser` which now combines the attribute and the spatial filter
Funded by [Valabre](https://www.valabre.com)
> Editing & Filter - Fix editing right access from popup

- assets/src/components/Treeview.js
- assets/src/modules/BaseLayersMap.js
- assets/src/modules/state/BaseLayer.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/MapLayer.js
- tests/js-units/node/state/baselayer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
To correctly support map layer state, we replace the loading boolean by an Enum for map layer load status.
> [JavaScript] Replace loading boolean by an Enum for map layer load status

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/install/upgrade_replyto.php
- tests/units/classes/lizmapServicesTest.php
Set it with the adminContactEmail value only if the new parameter `setAdminContactEmailAsReplyTo` is true.
It allows for jCommunity and Jelix to send emails with a default `Reply-To` header that could be different from the "webmaster" email.
Funded by 3Liz
> Mailer: set the replyTo parameter

- lizmap/modules/lizmap/classes/lizmapTiler.class.php
When the user set the projects min scale to 0, it leads to a fatal "Division by zero" error : 
see https://github.com/3liz/lizmap-web-client/blob/68ab4107642a9cb7baf106891faf108e9e2220e6/lizmap/modules/lizmap/classes/lizmapTiler.class.php#L256
scaledenomiator will be divided  until having out of bound value : 0
Fix is done on the plugin side https://github.com/3liz/lizmap-plugin/commit/392299aa54875c4e409ef5b7e31f39371d4f6292, but old projects conf may still have the 0 value
Funded by 3Liz
> check project scales and replace scale 0 with scale 1

- lizmap/modules/admin/controllers/logs.classic.php
The log controller must use the `logPath()` method instead of assuming log are in `var/ `
Usefull when the `jApp::initPath` set a specific folder for logs (when creating multiple instances for example). 
Funded by 3Liz
> use logPath instead of varPath()./log

- CHANGELOG-3.5.md
- lizmap/modules/lizmap/controllers/ban.classic.php
Sometimes api-adresse.data.gouv.fr doesn't return a "features" array and it causes PHP errors. The JSON content should be checked before processing list of features.
Funded by 3Liz
> Fix address search when results are empty

- lizmap/modules/lizmap/classes/lizmapServices.class.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/plugins/configcompiler/lizmapconfig/lizmapconfig.configcompiler.php
- tests/units/bootstrap.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/lizmapServicesTest.php
- tests/units/testslib/QgisProjectForTests.php
Proxy Request currently use "Lizmap" as user-agent in request header, that can be usefull for OGC service
the PR add the current lizmap Version
Fix : #2044
Funded by 3liz
> add lizmap version to proxy request

- lizmap/www/assets/js/dataviz/dataviz.js
- tests/end2end/cypress/integration/dataviz-ghaction.js
When displaying the popup of an object containing child plots, if the layer has no child data associated with a specific plot,  the loading bar must not be displayed but the plot should be hidden.
Ticket : fix #3799 
Funded by Faunalia (https://www.faunalia.eu)
> Dataviz - Do not display child plot in Popup when there is no data

- .github/workflows/e2e_tests.yml
There is a bug w/ Cypress and Chrome 117 : https://github.com/cypress-io/cypress/issues/19122
Let's use electron until we totally migrate to Playwright.
Funded by 3Liz
> e2e: Cypress executed w/ electron

- lizmap/app/themes/default/master_admin/index_login.tpl
The login template uses `view~default.repository.list.title` and will be repaced by `view~default.home.title`
Funded by [Conseil Départemental du Calavdos](https://www.calvados.fr/accueil.html) & [SDEC Energie](https://www.sdec-energie.fr/)
> [PHP] Using home page title in the login template

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The qgisVectorLayer::editableFeatures was able to return every feature of the layer when the layer is not editable.
Funded by [Conseil Départemental du Calvados](https://www.calvados.fr)
> [Bugfix] The qgisVectorLayer::editableFeatures did not check edition capabilities

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
The qgisVectorLayer::isFeatureEditable has to return false when the layer is not editable.
Funded by [Conseil Départemental du Calvados](https://www.calvados.fr/)
> [Bugfix] The qgisVectorLayer::isFeatureEditable did not check edition capabilities

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3909
> [Backport release_3_5] [Bugfix] The qgisVectorLayer::isFeatureEditable did not check edition capabilities

- assets/src/legacy/attributeTable.js
- assets/src/legacy/map.js
- assets/src/legacy/switcher-layers-actions.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
Ticket : support 2512 
Funded by CD84
https://github.com/3liz/lizmap-web-client/assets/2145040/8a8701f8-5112-481a-94b7-3cba156e27a5
> Add export started message when importing data

- assets/src/legacy/map.js
lizUrls.Service has been introduced in Lizmap Web Client 3.7
2 requests are concren by this:
* GetFeatreuInfo
* GetFilterToken
Funded by WPD France
> [Bugfix] lizUrls.service does not exist

- assets/src/legacy/attributeTable.js
To fix #3675 with #3868 a regression has been introduced in cascade filter.
The cascade layer's filter use the parent WMS name instead of the layer name. 
So the filter is not applied on cascade layer.
Funded by WPD France
> [Bugfix] Casacade layer WMS Name

- lizmap/app/system/mainconfig.ini.php
Raise QGIS minimum version to 3.22 for the server.
It doesn't impact versions in projects for being visible.
It means we jumped from QGIS 3.10 to 3.22 for LWC 3.7
> Raise QGIS minimum version to 3.22

- assets/src/modules/state/Layer.js
- tests/end2end/playwright/permalink.spec.ts
- tests/js-units/node/state/layer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
```js
TypeError: Cannot assign an unknown WMS style name! `` is not in the layer `Subdivisions fiscales` WMS styles!
at set wmsSelectedStyleName [as wmsSelectedStyleName] (Layer.js:673:19)
```
> JS: WMS Style `''` generates an error even though it is the default style

- assets/src/legacy/edition.js
Change the configurations of the Lizmap editing form fields published with autocompletion
* add a delay of 300ms to lessen the number of requests sent to the server
* add a minimum of 3 characters to trigger the autocompletion
* the search is now accent-insensitive : You can type `forets` and it will find `Forêts`
Funded by Ville d'Avignon https://www.avignon.fr/
> Editing - autocompletion fields: add minlength, delay & accent-insensitive

- assets/src/legacy/filter.js
In Lizmap form filter, we should add a day in the max date when requesting the data to be able to get the features with the same date as the max date. Since we use a date picker and there is no way to set the time, using only the max date as the filter will exclude all features of that day but with a defined hour. E.g `<= '2023-10-25'` will exclude features with a field date containing the time such as `2023-10-25 10:34:49`
This PR replaces for example `<= '2023-10-25'` by  `< '2023-10-26'` 
Ticket : #3571
Funded by 3liz
> Form filter - Date range: add a day to the max values when requesting data

- assets/src/legacy/edition.js
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/view/templates/edition_close_feature_data.tpl
This will allow the JS custom scripts to request the feature data after the form has been successfully saved.
The events `lizmapeditionfeaturecreated` and `lizmapeditionfeaturemodified` will now have a new property `primaryKeys` containing an object of the created/modified feature primary key(s) values, e.g. `{ id: "99" }`
Funded by [Parc naturel régional du Haut-Jura](http://www.parc-haut-jura.fr/)
> Editing - JS events now return the feature primary key(s) value(s) after save

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
Fixed a typo that prevented projects with embedded layers from being read correctly from the `ProjectCache`
> [Bugfix] fixed typo qsgmtime

- assets/src/modules/Popup.js
Round to integer `I` and `J` parameters of WMS `GetFeatureInfo` service accordingly to [OGC Documentation](https://portal.ogc.org/files/?artifact_id=14416) (see section 7.4.3.7) 
Ticket : #3971 
> [Fix] round the 'I' and 'J' paramters of WMS GetFeatureInfo service

- .github/workflows/e2e_tests.yml
The order was not logical, according to `make env`
> GH Action - Review order of steps

- assets/src/modules/BaseLayersMap.js
- lizmap/modules/lizmap/lib/Request/WMTSRequest.php
By default the maximum Lizmap WMS GetMap Size is 3000x3000. To avoid a blank map for large screen, the OL layer has to be a tile layer with tile WMS source instead of an image layer with image WMS source.
Funded by 3Liz
> Fix: Respect maximum WMS GetMap size

- assets/src/legacy/map.js
- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Popup.js
- assets/src/modules/SelectionTool.js
- lizmap/modules/view/templates/map.tpl
- lizmap/www/assets/css/map.css
This a preliminary work before having OpenLayers 8 map on top by default.
It can be tested putting OL8 map on top via `lizMap.mainLizmap.newOlMap = true`.
Here is the result:
Fix https://github.com/3liz/lizmap-web-client/issues/3765
Funded by 3Liz
> Handle map popups w/ OL8

- lizmap/www/assets/jelix/js/jacl2db_admin.js
I guess, it's a follow up from 8562649e2b42062cef32c36098ef0a7abdd7e2ca
Backport to 3.7 and 3.6
> Update files from Jelix

- assets/src/modules/config/Layer.js
- tests/js-units/node/config/layer.test.js
Funded By Atmo Normandie https://www.atmonormandie.fr/
> [Bugfix] JS: Layer ID can be used as WMS Name

- assets/src/legacy/map.js
When a user filters a feature from `pupup`, LWC tries to loop through each layer to check if any filter expression is set on it and tries to get the corresponding `FILTERTOKEN` to update the map accordingly.
Since the ajax call for the filter token is placed inside a loop, the layer configuration used in the ajax callback to set the value of the `filtertoken` on the current `lName-layer` always matches with the last occurrence of the `for loop`.
As side effect, in most cases the `mainLizmap.state.layersAndGroupsCollection.getLayerByName` method called in the callback generates an error in the console because the last occurrence of the layer often matches a `baselayer`, which is not included in the `layerAndGroupsCollection` object.
see …
> [Fix] uncaught exception on layerFilterParamChanged event

- tests/end2end/playwright/print.spec.ts
Linked to https://changelog.qgis.org/en/qgis/version/3.32/#layout-insure-hyperlinks-within-html-enabled-label
I would prefer to check the QGIS desktop version used, but I'm not sure how to do it in Playwright.
This PR is solving running the stack with QGIS desktop 3.34 : https://github.com/Gustry/lizmap-web-client/pull/83
Funded by 3Liz
> CI - Remove assert, failing due to new version of QGIS 3.32

- assets/src/modules/SelectionTool.js
The featureType is not necessarily the typeName for WFS getFeature request
> [Bugfix] SelectionTool: Use typeName instead of featureType

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/maps.tpl
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/view/zones/main_view.zone.php
Add a method for poject to check is path is valid
in view check path is valid before performing scan_dir
in admin view : add a badge for bad path
Ticket : #4076
Funded by 3Liz
> check if repository has a valid path

- lizmap/www/assets/js/dataviz/dataviz.js
> Fix: `display_when_layer_visible` only useful for layers w/ geometry

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControl.php
- phpstan-baseline.neon
- tests/qgis-projects/tests/form_edition_all_field_type.qgs
- tests/qgis-projects/tests/form_edition_all_field_type.qgs.cfg
In QGIS editing form configuration, a file-based field (image or generic file) can be set up with an expression to calculate the target directory where the file must be stored. For example:
```sql
-- Here the target directory is calculated based on the value of the field "feature_code" in the form
concat(
'media/some_target_folder/',
CASE
WHEN lower(trim(to_string(current_value('feature_code')))) IN ('', 'null') OR current_value('feature_code') IS NULL 
THEN 'no_code'
ELSE trim(to_string(current_value('feature_code')))
END,
'/'
)
```
This piece of code adds the same capability in Lizmap Web Client.
Funded by Cartophyl https://www.cartophyl.com/
> Editing form - Upload fields: allow to use an expression to set up the storage path

- assets/src/legacy/map.js
The layer name is not always the WMS Name.
> [Bugfix] JS Attribute Table: using wmsName for getFeaturePopupContent

- assets/src/legacy/map.js
Backport https://github.com/3liz/lizmap-web-client/pull/4102
> [Backport release_3_6] [Bugfix] JS Attribute Table: using wmsName for getFeaturePopupContent

- assets/src/modules/map.js
- tests/js-units/data/tiled_baselayers-capabilities.json
- tests/js-units/data/tiled_baselayers-config.json
- tests/js-units/node/state/baselayer.test.js
Reading the `cached` property on baselayers from Lizmap configuration to enable WMTS on baselayers.
> Enable WMTS requests for Lizmap baselayers

- assets/src/legacy/attributeTable.js
The table selector uses layer clean name and not the layer name
> [Bugfix] Child Attribute table: get parent layer name

- assets/src/components/FeatureToolbar.js
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/add_server_plugins.sh
- tests/end2end/playwright/print.spec.ts
QGIS Server does not work atlas print does.
> Fix regrssion : keep atlasprint plugin

- assets/src/modules/Utils.js
The filename was extracted only for attachement (force download response). The filename could be provided even in inline case.
> JS: Extract filename from Content-Disposition header

- assets/src/legacy/map.js
- tests/end2end/playwright/overview.spec.ts
To keep the same display as lizmap web client 3.6, if the contains old baselayers, the map will be displayed with EPSG:3857
> Force EPSG:3857 if old baselayers in config

- assets/src/modules/map.js
It is possible to define a map with only one resolution. In this case the `resolutions` is undefined.
> [Bugfix] Map creation with only one resolution

- assets/src/legacy/edition.js
- assets/src/modules/map.js
Child layer could be attribute table without display in map.
Funded by Ville d'Avignon
> [Bugfix] JS: do not refresh child layer not displayed in map

- assets/src/modules/map.js
The resolutions from OL2 map can contain duplicated values. It is needed to remove duplicated values and to be sur they are sorted by descending order.
> [Bugfix] Resolutions from OL2 map

- assets/src/modules/map.js
The WMTS options could be null if the layer has not be found in WMTS Capabilities
Funded by Agence de l'eau Rhône Méditerranée Corse
> [Bugfix] Build WMTS options return null

- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- tests/end2end/playwright/wmts.spec.js
- tests/qgis-projects/tests/wmts_test.qgs
- tests/qgis-projects/tests/wmts_test.qgs.cfg
* Fixing WMTS capabilities for cached layers with shortname defined
* Adding WMTS end2end tests with a cached layer which has a different shortname from name.
Funding by [Agence de l'eau Rhône Méditerranée Corse](https://www.eaurmc.fr/)
> Bugfix: WMTS for layers with shortname 

- assets/src/legacy/attributeTable.js
It is necessary to check that the layername is available before buidling the attribute table. Layer in a restricted group could be not available.
Funded by Entente Valabre
> [Bugfix] JS - layer in a restricted group is not available

- assets/src/legacy/switcher-layers-actions.js
- tests/end2end/playwright/theme.spec.ts
When clicking on a theme overwrite the hash with an empty one.
> [Bugfix] Choose a theme drop permalink hash

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/controllers/media.classic.php
This allows to load JS files as modules. Files need to have a `mjs` to automatically be loaded in the map this way:
```html
<script type="module" src="/index.php/view/media/getMedia?repository=testsrepository&amp;project=atlas&amp;mtime=1706777478&amp;path=media%2Fjs%2Fatlas%2Fconfetti.mjs"></script>
```
A `confetti.mjs` example file:
```js
import confetti from 'https://cdn.skypack.dev/canvas-confetti';
confetti();
```
Result :)
https://github.com/3liz/lizmap-web-client/assets/2145040/2e717c83-d1da-44ea-bc7c-092b6e248f22
This will help to add OpenLayers part as modules.
Ref: https://github.com/3liz/lizmap-web-client/issues/4091
Funded by 3Liz
> Load custom JS as module

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
There are cases where a project might embed several layers from another project. 
In this scenario Lizmap [loads](https://github.com/3liz/lizmap-web-client/blob/1b302d40f667706f05f4f4b0e8882720a779449f/lizmap/modules/lizmap/lib/Project/QgisProject.php#L1494) the same project (embedded project) multiple times for each of these layers and this behavior could cause php to hit `max_execution_time` if there are many embedded layers.
To fix that I've grouped the embedded layers and load the related QGIS embedded project once.
**Test note**
I haven't add php unit tests since seems to me that the current tests already covers this changes. Of course, if you think that more tests are needed, I'll add them.
> [Bugfix] Too many embedded layers cause php to hit max_execution_time 

- assets/src/modules/map.js
- tests/end2end/playwright/viewport.spec.js
If the devicePixelratio is not 1, OL change the DPI parameter and the tile size. Lizmap has to take it into account to calculate tileSize.
Funded by FMProjet
> [Bugfix] devicePixelRatio is used by OL to defined tile size

- assets/src/modules/BaseLayersMap.js
- tests/end2end/playwright/viewport.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4167
> [Backport release_3_7] [Bugfix] devicePixelRatio is used by OL to defined tile size

- assets/src/components/Print.js
- tests/qgis-projects/tests/layer_order.qgs
- tests/qgis-projects/tests/layer_order.qgs.cfg
> Fix print layer custom order

- assets/src/modules/config/BaseLayer.js
- tests/end2end/playwright/bing-basemap.spec.ts
- tests/js-units/data/bing_basemap-capabilities.json
- tests/js-units/data/bing_basemap-config.json
- tests/js-units/node/state/baselayer.test.js
- tests/qgis-projects/tests/bing_basemap.qgs
- tests/qgis-projects/tests/bing_basemap.qgs.cfg
**TL;DR**
Enabling Bing Maps to be loaded as baselayers in LWC through OpenLayers dedicated implementation by importing Bing Maps in QGIS project from [QuickMapServices QGIS Plugin](https://plugins.qgis.org/plugins/quick_map_services/)
**DETAILS**
In previous versions of LWC (i.e. 3.6) it was possible to add a defined set of external layers (including Bing) by flagging the corresponding option in the plugin's `base-layer` panel and without adding any layer to the project. Then the plugin updates the `cfg` accordingly by setting the corresponding properties in the option section of the cfg:
```json
"options": {
"osmMapnik": "True",
"openTopoMap": true,
"bingKey": "some___key",
"bingStreets": "True",
"bingSatellite": "True",
}
```
Now, since the direction is to rely on the QGIS project, in …
> [Feature] Add QMS Bing Maps

- lizmap/www/themes/default/css/view.css
Since https://github.com/3liz/lizmap-web-client/pull/4055 the project description if full css (no more js event to display it). 
The project description is also used in "project panel" (when  enabled) but  the description should not be displayed.
Quick fix add `display:none` in panel
Funded by 3Liz
> hide project description on projets panel

- assets/src/modules/Lizmap.js
- assets/src/modules/Permalink.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
- assets/src/utils/EventDispatcher.js
- tests/end2end/playwright/permalink.spec.ts
- tests/end2end/playwright/theme.spec.ts
* Extent in permalink use precision 6
* target has been added to the event object
* MapState and map are synchronizing
*  MapState fires map.state.ready
> JS: Enhancing the way Map is managed

- assets/src/modules/map.js
- tests/end2end/playwright/viewport.spec.js
OpenLayers supports High DPI rendering. For WMS layers, it requested to the server images with Higher DPI that depends on device pixel ratio. With High DPI enabled, more images are requested and the rendering of QGIS label is too small. We prefer to disble High DPI support.
Funded by Valabre
> [Bugfix] Disable High DPI support

- lizmap/modules/action/classes/action.listener.php
While doing #4226, I think it looks better @mdouchin according to the group "Publisher".
> Allow publisher to see an outdated action syntax

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_help.tpl
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- tests/units/classes/Project/ProjectConfigTest.php
_Since the screenshot, it's now possible to close the dialog warning on the map_
Maybe it would be nice to cross info with "Administration panel → QGIS projects" ?
Funded by 3Liz
> Display a warning box when the CFG contains warnings

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/lizmap/lib/Server/Server.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
> Provide a QGIS desktop version in metadata

- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
After #4226 and #4242, the warning message can generate the error `Uncaught SyntaxError: missing ) after argument list`
and `Uncaught ReferenceError: lizUrls is not defined`. These error messages are generated by a quote in the warning message.
To fix it, we use the Lizmap dictionnary which is a JSON version of the Dictionnary local.
> Fix Display a warning box when the CFG contains warnings

- lizmap/plugins/formwidget/htmlbootstrap/htmlbootstrap.formwidget.php
backport https://github.com/3liz/lizmap-web-client/commit/a115c70e2f1149f0a4fd55f89bf20f19dc4bcbcb
on 3.6
Funded by 3Liz
> add deprecatedDeclareFormBeforeControls to builderOptions

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/end2end/playwright/embedded-form.spec.ts
- tests/qgis-projects/tests/edition_embed.qgs
- tests/qgis-projects/tests/edition_embed.qgs.cfg
- tests/qgis-projects/tests/edition_embed_parent.qgs
- tests/qgis-projects/tests/edition_embed_parent.qgs.cfg
- tests/qgis-projects/tests/tests_dataset.sql
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/edition_embed.qgs
- tests/units/classes/Project/Ressources/edition_embed.qgs.cfg
- tests/units/classes/Project/Ressources/edition_embed_parent.qgs
- tests/units/classes/Project/Ressources/edition_embed_parent.qgs.cfg
- tests/units/testslib/QgisProjectForTests.php
**Drag and drop** form configuration is not taken into account for the embedded layers. 
This is due to the fact that in the `readEditionForms` [method](https://github.com/3liz/lizmap-web-client/blob/4a63151845de41156ad7256d5c80d4536ac5dad7/lizmap/modules/lizmap/lib/Project/QgisProject.php#L890), the layer configuration is read from the "current" project and not from the embedded project.
To fix this, I did something similar to what I did for this [PR](https://github.com/3liz/lizmap-web-client/pull/4093). 
This time I've also add  a `cache check`. I don't know if it's worth it, since in most cases the modified methods are called before the project cache is set. However, if you think the cache-checking is fine, I could add it to the other methods modified in the previous PR.
I've added …
> [Bugfix] Drag and drop form for embedded layers

- assets/src/modules/Digitizing.js
- assets/src/modules/SelectionTool.js
If the measure is activated with selection tool, the measure overlays is not removed when a feature of the digitizing module is removed.
> Bugfix selection with measure - overlay is not removed

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_help.tpl
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- tests/units/classes/Project/ProjectConfigTest.php
Manual backport from #4226 for the **administration** panel only
It's easier to debug projects on the administration page : 
* display number of warnings
* display Lizmap plugin version used in the tooltip
The display of the warning when opening the map has not been backported
> UX - Update the QGIS project table in the admin panel

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
I don't want the absolute path of the repository, but only the path set in the other admin panel.
~I didn't the find the correct property to use @nworr ?~
Just to be quicker to debug from the QGIS project panel
> UX - Display the path name of the repository in the tooltip

- assets/src/modules/Lizmap.js
- assets/src/modules/Utils.js
- tests/js-units/node/utils.test.js
- tests/js-units/node/wfs.test.js
- tests/js-units/node/wms.test.js
- tests/js-units/package-lock.json
- tests/js-units/package.json
* JS Utils: expose a fetch method that provide a successful response
* JS main Lizmap: fixing the JS Docs
> JS: expose a fetch method that provide a successful response and enhance docs

- assets/package-lock.json
- assets/package.json
> Update OL to 9.0

- lizmap/modules/lizmap/lib/Form/QgisForm.php
Added `form` context to webdav path expression evaluation to also correctly evaluate expressions that contain references to feature fields
> [Bugifx] Webdav failing evaluating expressions that uses feature fields 

- lizmap/modules/lizmap/lib/Form/QgisForm.php
This prevent the message "Feature not editable" for this case
* the filter by login is based on an attribute and on the user name (login), not on groups
* the authenticated user has the right `loginFilteredOverride` which means he can view and edit any filtered feature
Funded by PNR Haut-Jura https://www.parc-haut-jura.fr/
> Editing - Allow the authenticated user to save form if loginFilteredOverride is True

- lizmap/modules/lizmap/controllers/service.classic.php
The `getACAOHeaderValue` is a `Repository` method.
On service exception, for example Authorization needed, CORS Headers could be set on the response.
> [Bugfix] Service controller getACAOHeaderValue() on null

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/units/README.md
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
Alternative approach for #4269 : not using xpath, but the date in the file metadata.
But for developers, Git is not making dates correct. We can come back later for another approach (reading the first X lines in the QGS file or using xpath carefully like in #4269)
For recently edited QGS file (edited after the release date of  LWC), we check against an hardcoded plugin version.
For now, the warning is only displayed for admin (when connected) on the map, like #4270
> Check plugin version for recently edited QGS file

- assets/src/components/Print.js
- assets/src/modules/Config.js
- assets/src/modules/config/BaseLayer.js
- tests/end2end/playwright/print.spec.js
- tests/qgis-projects/tests/base_layers.qgs
- tests/qgis-projects/tests/base_layers.qgs.cfg
To keep compatibility with lizmap base layers config for version before 3.7, the hidden group can provide config for external baselayers.
> [Bugfix] Printing base layers withlayer in hidden group

- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
The PR #4287 is not perfect, in case of bulk upload of files.
We can notice on our test server right now. I updated all tests files on the server by doing a "big" copy/paste of all files and now LWC thinks I have touched all QGS files, which is not true.
I assume we should find `saveDateTime` in the first 5 lines of XML.
```xml
<qgis projectname="" saveDateTime="2023-09-07T13:56:00" saveUser="XXXXX" saveUserFull="XXXXXX" version="3.22.16-Białowieża">
```
Backport will be done manually in #4296 and #4297. No backport label on purpose.
Keen to have feedbacks from @mdouchin (and @nworr )
> Use the date stored in the QGS file instead of the file creation date

- lizmap/modules/admin/controllers/landing_page_content.classic.php
- lizmap/modules/admin/forms/landing_page_content.form.xml
- lizmap/modules/admin/lib/LandingContent.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/module.xml
- lizmap/modules/admin/templates/landing_page_content.tpl
- lizmap/modules/view/controllers/default.classic.php
- tests/end2end/playwright/landing_page_config.spec.ts
the administrator can now define content at the top and bottom of the landing page that will only be displayed to authenticated users, with an option to display unauthenticated content or not 
Ticket : # 
Funded by JPEE
> Landing page content for authentified users

- assets/src/index.js
- assets/src/legacy/map.js
- assets/src/modules/ExecuteJSFromServer.js
- lizmap/app/responses/myHtmlMapResponse.class.php
- lizmap/app/system/mainconfig.ini.php
- lizmap/app/themes/default/master_admin/index_login.tpl
- lizmap/modules/admin/templates/config_section.tpl
- lizmap/modules/admin/templates/config_services.tpl
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/admin/templates/theme.tpl
- lizmap/modules/lizmap/lib/Form/WidgetTrait.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/view/controllers/embed.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/plugins/formbuilder/htmlbootstrap/htmlbootstrap.formbuilder.php
- lizmap/plugins/formwidget/htmlbootstrap/htmlbootstrap.formwidget.php
- lizmap/plugins/formwidget/password_htmlbootstrap/password_htmlbootstrap.formwidget.php
- lizmap/plugins/formwidget/passwordeditor_htmlbootstrap/passwordeditor_htmlbootstrap.formwidget.php
- lizmap/www/assets/css/main.css
- lizmap/www/assets/css/map.css
- lizmap/www/themes/default/css/main.css
Speed up FCP (first contentful paint). This PR allows JavaScript scripts to be loaded after the HTML is loaded and parsed thanks to `defer` attribute. It is interesting for users with a slow connection, this way they will not wait too long with a blank page.
Funded by 3Liz
TODO:
> Speed up FCP (first contentful paint)

- assets/src/modules/map.js
After #3947 [Feature] Load layers as single WMS layer has been merged, the #4278 [Bugfix] Apply min and max resolutions to base layers has been partially loose.
> [Bugfix] Apply min and max resolutions to base layers removed by single WMS Layer

- lizmap/modules/lizmap/lib/Commands/WMTSSeed.php
- tests/end2end/cypress/integration/cmdline-wmts-ghaction.js
refs #3696 ( https://github.com/3liz/lizmap-web-client/issues/3696#issuecomment-1571809121)
When 0 is used as arg in command line for `tileMatrixMin`/`tileMatrixMax`, the filter_input_var validate as int but returned value (0) is interpreted as false.
I add a strong type comparison 
Funded by 3Liz
> Cache seed cli accept 0 as argument value

- assets/src/modules/map.js
- tests/end2end/cypress/integration/external_wms_layer-ghaction.js
With the transition to OpenLayers 8+, Lizmap loose the use of external WMS.
Thanks to @guenterw to provide projects in different lizmap version.
Fixes #4379 
Fix #4318
> [Bugfix] Use external WMS when activated

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/get_feature_info_style.qgs
- tests/qgis-projects/tests/get_feature_info_style.qgs.cfg
When a `GetFeatureInfo` request is issued to the server and no `STYLE` parameter is passed, QGIS Server
uses the style of the layer that was active when the `QGIS` project was saved.
If a layer has multiple style, Lizmap allows to switch between styles on client side and this could lead to inconsistencies as the server always uses the same style when processing the response.
Take for example this test project:
[get_feature_info_style.zip](https://github.com/3liz/lizmap-web-client/files/14987788/get_feature_info_style.zip)
The `natural_areas` layer has 3 feature and is configured with 2 rule based styles: `default` and `ids`. The project is saved with the `default` style active.
With the `default` style, the feature with **id = 3 is not shown** on the map while with the `ids` style all …
> add STYLE parameter to GetFeatureInfo request

- tests/docker-compose.yml
We have a warning when launching the stack
> Tests - Remove docker compose version

- assets/src/legacy/map.js
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/view/controllers/lizMap.classic.php
The popup dock is build client side by the JS and depends on `lizDict`. Since https://github.com/3liz/lizmap-web-client/pull/4329 the popup dock could be created before the `lizDict` is available.
> [Fix] Add Popup dock server side

- assets/src/legacy/attributeTable.js
- tests/end2end/cypress/integration/attribute_table-ghaction.js
- tests/qgis-projects/tests/attribute_table.qgs
Ticket : #4396 
more precision in [comment](https://github.com/3liz/lizmap-web-client/issues/4396#issuecomment-2093118247)
I completed  the cypress test with a check that inline js is cleaned (whole attributes is removed)
Funded by 3Liz
> Content sanitisation in attributes table

- assets/src/legacy/map.js
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/view/controllers/lizMap.classic.php
Backport https://github.com/3liz/lizmap-web-client/pull/4398
> [Backport release_3_7] [Fix] Add Popup dock server side

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
Not the best, because the link is neither clickable or selectable.
But at least, the user has a clue what to look for in the internet about this setting.
> UX - Rephrase tooltip about CORS settings

- assets/src/modules/config/BaseLayer.js
- tests/js-units/node/config/baselayer.test.js
Since QGIS Server 3.34, empty groups are not available in WMS GetCapabilities. project-background-color is an empty group placed in baselayers group to provide no baselayer in Lizmap Web Client User Interface.
Since Lizmap Desktop Plugin 4.3.0, an option default_background_color_index provides the index to add project-background-color in the list of baselayers.
If the configuration has not been updated, but the QGIS Server has been, Lizmap Web CLient will not provide a no baselayer to the user.
This changes wil provide a no baselayer capability, if the project-background-color is found in the Lizmap config at the right place.
Funded by 3liz
>  Fix: Add project-background-color even if the default_background_color_index is not defined

- assets/src/legacy/attributeTable.js
- tests/end2end/playwright/attribute-table.spec.js
Since inline js is forbidden the [documentation tips to create thumbnail in data table](https://docs.lizmap.com/next/en/publish/lizmap_plugin/attribute_table.html#tips) need to be refactored.
I use a dom class and a data attribute that is used to overwrite the src attribute, once datatable has been rendered.
refs #4396
Funded by 3Liz
> check tag with thumbnail class and generate thumbnail

- assets/src/components/Treeview.js
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/legend.spec.js
- tests/end2end/playwright/permalink.spec.ts
- tests/qgis-projects/tests/layer_legends.qgs
- tests/qgis-projects/tests/layer_legends.qgs.cfg
A class is added to the symbol li if the symbol is out of scope and the category is italic and greyed.
Funded by EPF Haut De France
> [Bugfix] Treeeview symbols not in scale

- assets/src/components/Treeview.js
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/legend.spec.js
> [Bugfix] Treeview: italic and greyscaled uncheked symbols and their children

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
It's look more important to me to : 
* first warn the user about outdated plugin version (and given the hardcoded version is at least something like 2 months old)
* then warn the user about warnings in the plugin
An up to date version might give him more updates in the plugin and errors.
I consider the plugin update easy to do, so we can keep the dialog "not closable" ?
I know the backport on 3.6 will fail, but I will propose this small update
> For admin, check plugin version first, before checking for warnings

- assets/src/modules/map.js
- tests/end2end/playwright/singleWMS.spec.ts
- tests/qgis-projects/tests/single_wms_image.qgs
- tests/qgis-projects/tests/single_wms_image.qgs.cfg
When a layer is included in the `single WMS image` it is not refreshed after updating/inserting a new feature.
> [Bugfix] SingleWMSLayer - refresh layer after editing

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_help.tpl
In the admin project page, a `%s` was missing.
> Admin - Add missing variable in locale in the project page

- tests/end2end/cypress/integration/requests-service-ghaction.js
- tests/end2end/playwright/permalink.spec.js
I saw the permalink hash failure often, like in #4357 @nboisteault and @rldhont 
For the other one, I'm seeing it in #4367
> Tests - Two lines seem to be strict or flaky for E2E tests

- assets/src/modules/config/BaseLayer.js
- assets/src/modules/config/LayerTree.js
- assets/src/modules/map.js
- assets/src/modules/state/BaseLayer.js
- tests/end2end/playwright/google-basemap.spec.js
- tests/qgis-projects/tests/google_apikey_basemap.qgs
- tests/qgis-projects/tests/google_apikey_basemap.qgs.cfg
- tests/qgis-projects/tests/google_basemap.qgs
- tests/qgis-projects/tests/google_basemap.qgs.cfg
Since release 9.0, OpenLayers has introduced support form Google Maps Tiles.
This PR relies basically on the same logic of this one https://github.com/3liz/lizmap-web-client/pull/4150
If a valid `Google Api Key` is provided in the Lizmap plugin, then the application uses the OL dedicated class to get tiles from the Google endpoint and the API key is used to issue requests.
If no key is provided, then these tiles are treated as a `generic WMTS external layer` and the application get the tiles directly from the default URI set by QMS QGIS plugin. In this case it is not guaranteed that the tiles will work.
Maps supported:
- Satellite
- Roads
**TEST NOTES**
For now testing is manually. In the test repository there is a `google_basemap.qgs` project. You can configure the Lizmap plugin by …
> [Feature] Add QMS Google Maps Tiles

- tests/end2end/cypress/integration/external_wms_layer-ghaction.js
Correctly wait for GetMap requests
> Test e2e Cypress: Enhancing external WMS layer

- assets/src/components/Treeview.js
- assets/src/modules/state/LayerTree.js
- assets/src/modules/state/MapLayer.js
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/treeview.spec.js
When double clicking on a group label or checkbox, the new checked state of the group will be propagated through the tree to all the children.
With this capability, the user will be able to check all the layers contained in a group whatever the depth.
> UI: Double clicking on group propagating the checked state

- assets/src/components/FeatureToolbar.js
- assets/src/legacy/attributeTable.js
* make sure to quote textual IDs in order to generate valid filter expressions
* when printing an atlas (related to 3liz/qgis-atlasprint/#71)
* when filtering features
* respect layout `default_format`  when printing an altas
* fixes #4534
> Improve  support for layer with string PKs

- assets/src/legacy/switcher-layers-actions.js
- assets/src/modules/Config.js
- assets/src/modules/config/Options.js
- assets/src/modules/config/Theme.js
- lizmap/modules/view/controllers/map.classic.php
- tests/end2end/playwright/theme.spec.js
- tests/js-units/node/config.test.js
- tests/js-units/node/config/options.test.js
- tests/js-units/node/config/theme.test.js
Fixing JS classes around map themes
Funded by Karum
> [Bugfix] JS config themes

- assets/src/legacy/map.js
- assets/src/modules/Permalink.js
- lizmap/modules/view/templates/map_projects.tpl
- lizmap/modules/view/templates/view.tpl
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/permalink.spec.js
`bbox` and `crs` parameter was removed in favor of hash permalink.
Funded by Karum, Conseil Départemental du Calvados, Terre de Provence Agglomération
> [Bugfix] Still support bbox parameter

- assets/src/modules/Permalink.js
- assets/src/modules/config/Options.js
- tests/end2end/playwright/permalink.spec.js
In the main section of the JSON, add a new option to enable the automatic permalink : automatic_permalink.
It will be enabled by default.
Linked to https://github.com/3liz/lizmap-plugin/pull/590
> New option to disable the automatic permalink

- lizmap/www/assets/js/dataviz/dataviz.js
- tests/end2end/playwright/embed.spec.js
In embed mode the error is generated because the dataviz elements are not available.
```
TypeError: elem is null
isInViewport dataviz.js:23
getPlots dataviz.js:146
uicreated dataviz.js:774
triggerEvent OpenLayers.js:246
init map.js:5034
map.js:5039:28
init map.js:5039
```
> Fix JS Dataviz: When dataviz is not available

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
If measure is activated in selection tool, the overlay was not removed when you open print or draw.
Funded by Terre de Provence Agglo
> JS Digitizing: fixing measure not removed from selection to draw

- lizmap/modules/lizmap/classes/lizmapFts.class.php
This can be tested with the location_search projet by searching for `a`.
Without this patch:
With this patch, three last items are ordered by `item_label` :
Funded By Valabre
> FTS: order first by `similarity` then by `item_label`

- tests/end2end/playwright/embedded-form.spec.js
- tests/end2end/playwright/embedded-relation.spec.js
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/n_to_m_relations.spec.js
- tests/end2end/playwright/overview.spec.js
- tests/end2end/playwright/singleWMS.spec.js
- tests/end2end/playwright/snap.spec.js
- tests/end2end/playwright/treeview.spec.js
- tests/end2end/playwright/webdav-upload.spec.js
Enhancing tests e2e playwright by using gotoMap instead of networkidle
> Tests e2e playwright: using gotoMap instead of networkidle

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/attributions.spec.js
- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/base-layers.spec.js
- tests/end2end/playwright/custom-javascript-api.spec.js
- tests/end2end/playwright/display_in_layer_tree.spec.js
- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/embed.spec.js
- tests/end2end/playwright/error-occurred.spec.js
- tests/end2end/playwright/exposed_dependencies.spec.js
- tests/end2end/playwright/form_relational_value.spec.js
- tests/end2end/playwright/google-basemap.spec.js
- tests/end2end/playwright/legend.spec.js
- tests/end2end/playwright/permalink.spec.js
- tests/end2end/playwright/popup.spec.js
- tests/end2end/playwright/print.spec.js
- tests/end2end/playwright/print_in_project_projection.spec.js
- tests/end2end/playwright/project_load_warning.spec.js
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/startup.spec.js
- tests/end2end/playwright/theme.spec.js
- tests/end2end/playwright/timemanage.spec.js
- tests/end2end/playwright/viewport.spec.js
- tests/end2end/playwright/wmts.spec.js
- tests/end2end/playwright/xss.spec.js
To homogenize tests e2e playwright `require` is replaced by `import ... from`
> Tests e2e playwright: replace require par import ... from

- tests/end2end/playwright/embedded-form.spec.js
- tests/end2end/playwright/embedded-relation.spec.js
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/overview.spec.js
- tests/end2end/playwright/treeview.spec.js
- tests/end2end/playwright/webdav-upload.spec.js
Backport https://github.com/3liz/lizmap-web-client/pull/4602
> [Backport release_3_7] Tests e2e playwright: using gotoMap instead of networkidle

- assets/src/legacy/switcher-layers-actions.js
groupAsLayer stays a group in QGIS theme but is view as a layer in lizmap layer tree.
> [Bugfix] groupAsLayer checked by theme

- assets/src/modules/config/BaseLayer.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
- tests/end2end/playwright/base-layers.spec.js
- tests/js-units/node/config/baselayer.test.js
- tests/js-units/node/state/map.test.js
fixes #4332
Currently, if the map allows you to go beyond the min/zoom resolution of a WMTS or XYZ source, Lizmap won't display anything beyond this min/zoom resolution.
OpenLayers is able to do resampling. This can be seen when you zoom in progressively. OpenLayers must be forced to use the max zoom of the grid even when the user goes beyond it.
The solution is described on stackoverflow https://stackoverflow.com/questions/43538345/how-to-force-load-tiles-for-lower-resolution and is based on `TileGrid`'s `getZForResolution` method https://github.com/openlayers/openlayers/blob/main/src/ol/tilegrid/TileGrid.js#L634
```js
getZForResolution(resolution, opt_direction) {
const z = linearFindNearest(
this.resolutions_,
resolution,
opt_direction || 0,
);
return clamp(z, this.minZoom, …
```
> Fixing tiles resolutions

- assets/src/modules/BaseLayersMap.js
- assets/src/modules/config/BaseLayer.js
- tests/end2end/playwright/axis_orientation.spec.js
- tests/end2end/playwright/base-layers.spec.js
- tests/js-units/node/config/baselayer.test.js
> [Backport release_3_7] Fixing tiles resolutions

- assets/src/modules/Lizmap.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
- assets/src/modules/utils/Extent.js
- tests/js-units/node/state/map.test.js
- tests/js-units/node/utils/extent.test.js
The old OL 2 map is now out of sync with the new OL map, especially the center. So the main Lizmap center attribute has to be provided by the map state.
> JS: mainLizmap.center has to be provided by map state

- assets/src/modules/Popup.js
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs.cfg
The popup was disabled when selection tool or draw are displayed. The popup has to be disabled when the digitizing is enabled not just because it is available.
> Fix: Enable popup when digitizing is disabled

- assets/src/components/Treeview.js
- assets/src/legacy/map.js
Starting from versions 3.7 the `treecreated` event is raised before the `lizmap-treeview` component is properly initialized.
To fix that, the `treecreated` event must be fired after `uicreated` event is fired since `Treeview` component is updated in the `uicreated` listener (see [index.js](https://github.com/3liz/lizmap-web-client/blob/05dded203440cfecda5d98a2eb81f6c89a74573c/assets/src/index.js#L41))
This behavior might be confusing, as you might think that the `uicreated` event fires when all UI components are correctly initialized, which is not the case.
As a proposal, it might be useful to reconsider name of the uicreated event (e.g. `uiinitialized` or whatever) and fire the uicreated event when components initialization is completed (see index.js above)
**NOTE:** 
`treecreated` event …
> [Bugfix] Fire treecreated event at proper time

- Makefile
- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/templates/server_information.tpl
As a draft for now, I would have prefered to use the `project.xml` file https://github.com/3liz/lizmap-web-client/blob/master/lizmap/project.xml but it's triggering a warning in the Jelix toolbar 
> [Creation of dynamic property Jelix\Core\Infos\AppInfos::$commitId is deprecated](http://lizmap.local:8130/admin.php/admin/server_information#)
> [Creation of dynamic property Jelix\Core\Infos\AppInfos::$commit is deprecated](http://lizmap.local:8130/admin.php/admin/server_information#)
So I used the mainconfig.ini file. But it doesn't seem the perfect place. Anyway, feel free to let me know what you think.
We need to remove one of the "wrong" `sed` before merging
> Add link to the commit SHA on GitHub if possible

- phpstan-baseline.neon
Remove phpstan errors from `phpstan-basliene.neon` that are no more detected since php stan 1.11.10
Funded by 3Liz
> remove phpstan ignored errors no more existing

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/maps-management.spec.js
- tests/qgis-projects/tests/filter_layer_by_user.qgs
- tests/qgis-projects/tests/filter_layer_by_user.qgs.cfg
- tests/qgis-projects/tests/set_tests_respository_rights.sql
- tests/qgis-projects/tests/tests_dataset.sql
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/Ressources/edition_embed_parent_filtered.qgs.cfg
- tests/units/classes/Request/WFSRequestTest.php
- tests/units/testslib/ContextForTests.php
- tests/units/testslib/jDbConnectionForTests.php
Lizmap Web Client allows **filtering the content of vector layers** depending on the authenticated user. Before version 3.8, for the attribute filter, every layer to filter must have a field which value must be **only one group identifier (or one user login)**, such as:
|id | name  | filter_field |
|----|----------|--------------|
| 1  | one    | group_a  |
| 2  | two    | group_b  |
| 3  | three | group_b  |
| 4  | four   | all             |
This modification allows using **a list of groups (or a list of users) separated with a comma** (with no spaces) inside the field used as the source of filtering. This will ease showing some features for more than one group (or user). For example, the filtered layer could contain:
|id | name  | filter_field              | …
> Improve user/group filter to allow multiple users/groups

- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/composer.json
The 1.12  version of phpstan improve `preg_match  / preg_match_all` detection, some new errors appears.
Since preg_match_all always fill `$matches` with 2 item, phpstan consider `count($matches)  ` comparison  useless.
Refactoring use return value from preg_match_all instead of `count($matches) `
> Fix phpstan error detected sinc phpstan 1.11

- .github/workflows/e2e_tests.yml
Some tests are failing in headless mode without any reason.
Let's use head mode
> Headed chrome for Cypress

- assets/src/components/Digitizing.js
- assets/src/components/SelectionTool.js
- assets/src/images/svg/text.svg
- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- lizmap/modules/view/templates/map_draw.tpl
- lizmap/www/assets/css/map.css
- tests/end2end/cypress/integration/selectionTool-ghaction.js
Digitizing element provides user interface for digitizing shapes and text
The available Attributes are:
*  context - The digitizing context to linked element to Digitizing module context
*  selected-tool - Start selected drawing tools one of DigitizingAvailableTools or available-tools
*  available-tools - List of available drawing tools based on DigitizingAvailableTools
*  save - Enable save capability
*  measure - Enable measure capability
*  import-export - Enable import / export capabilities
By default
```html
<lizmap-digitizing context="draw" save import-export measure></lizmap-digitizing>
```
For selection tool
```html
<lizmap-digitizing context="selectiontool" selected-tool="box" available-tools="point,line,polygon,box,freehand" import-export></lizmap-digitizing>
```
For editing …
> JS Web Component Digitizing: define attributes to config the element

- assets/package-lock.json
- assets/package.json
- assets/src/dependencies/ol.js
- assets/src/index.js
- assets/src/legacy/attributeTable.js
- assets/src/legacy/filter.js
- assets/src/legacy/map.js
- assets/src/legacy/switcher-layers-actions.js
- assets/src/modules/Config.js
- assets/src/modules/Lizmap.js
- assets/src/modules/SelectionTool.js
- tests/js-units/data/montpellier-capabilities-wfs.json
- tests/js-units/node/config.test.js
Adding Open Layers format for reading WFS capabilities data provided by [ol-wfs-capabilities](https://github.com/GastonZalba/ol-wfs-capabilities) package.
> [Feature] JS: Addinig Open Layers format for reading WFS capabilities data

- assets/src/legacy/edition.js
When popup is displayed in the right dock and edition is launched, we have to synchronize OL maps only when right dock is closed as it changes the map size Fix #4729
Funded by 3Liz
> Fix: Shifted geometry during editing

- assets/src/modules/Popup.js
> Fix: Target "_blank" disapeared on hyperlinks in popups

- assets/src/modules/Action.js
OL2 is now just used with edition so we should not rely on it elsewhere.
Funded by 3Liz
> Use OL10 map instead of OL2 for actions

- assets/src/modules/Permalink.js
- tests/end2end/playwright/permalink.spec.js
When a layer is checked, all his parents are checked. So unchecked groups provided by permalink has to be unchecked after the layers and from leaf to root.
> Bugfix Permalink: checked groups are not respected when hash is applied

- tests/end2end/playwright/timemanage.spec.js
When the request has not been logged by echo proxy, the response is `unfound`
> Tests e2e: Check unfound for echo request

- lizmap/modules/lizmap/lib/Project/ProjectCache.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/testslib/QgisProjectForTests.php
Updating PHP QgisProject class to easily remove access to XML QGIS Project.
> PHP: Using getXml instead of direct acces to xml protected attribute

- lizmap/modules/lizmap/lib/Project/Project.php
Try to use a specific connection object for quoting fields by `encloseName` function
Ticket : fix #4745
> Get specific connection object for fields quoting

- lizmap/modules/admin/templates/server_information.tpl
On the current docker stack, on master, the version of Py-QGIS-Server is `n/a`, which was leading to a 404 on the GitHub repository.
@dmarteau There is an issue while packaging ?
> Do not provide a link to Py-QGIS-Server repository if n/a

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
No tested, no idea.
Just to think about https://github.com/3liz/lizmap-plugin/pull/604 and https://github.com/3liz/qgis-lizmap-server-plugin/pull/87 about the migration from BootStrap 2 to BootStrap 5 in #4455
CC @mdouchin @nboisteault and @mind84
> Request GetFeatureInfo with Bootstrap5

- tests/end2end/playwright/n_to_m_relations.spec.js
I found it difficult to make the popup and attribute table tests independent of each other without resetting db after each test, mainly because the core of the development is the update/insert/delete/unlink features functionality, and those functionalities must be tested both in the popup and in the attribute table
After thinking about it, maybe merging the two tests in one could be a solution, for now. 
I don't see any drawbacks doing so, as the functionality to be tested are basically the same. This way the tests are running in sequence, avoiding the case of a possible parallel/inverse execution.
> Test e2e : n to m relations tests rendered in sequence

- lizmap/composer.json
Follow up from #4676 
`gettext` is not used in the source code since LWC 3.2
> Remove PHP gettext from composer.json

- assets/src/legacy/switcher-layers-actions.js
Fix to open layer group information window in lizmap web client 3.8.1
Ticket : https://github.com/3liz/lizmap-web-client/issues/4779
Funded by sponsored development
> fix opening layer group information window

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/maps.tpl
- lizmap/modules/admin/templates/server_information.tpl
* Fix a BS2 badge
* Use a badge instead of adding a new column "Action" in the table.
* Remove the plugin name, it was redundant with the row already
It will be manually backported to 3.8 only.
> Fix BS5 badge, use a badge for Lizmap server update instead of adding a new column

- assets/src/modules/state/Map.js
- assets/src/modules/utils/Extent.js
- tests/js-units/node/state/map.test.js
- tests/js-units/node/utils/extent.test.js
If the map projection is not the same as the project projection, the initial extent stored by Map State has to be transform.
This fix the move to bad extent when you click on zoom to initial extent when the map projection is not the same as the project projection. Map projection and project projection could be different if the config still contains external base layers.
> JS Map State: transform initial extent on projection changes

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
> UX - Provide a HTTP link about the main plugin homepage/help

- lizmap/modules/admin/controllers/config.classic.php
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/lib/ModulesInfo/ModuleMetaData.php
- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/config.tpl
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- tests/end2end/cypress/integration/requests-metadata-ghaction.js
- tests/end2end/playwright/server-information.spec.js
> Show Lizmap modules infos

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormControlProperties.php
The orderByValue Relation reference property has been removed from XML since QGIS 3.32
Fixed #4419
Superseed #4764
> Fix Relation Reference Form control OrderByValue default value to true

- assets/src/modules/Search.js
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
This can be tested here: https://data.geopf.fr/geocodage/completion/?text=fo&type=StreetAddress&maximumResponses=10&bbox=3.875336983791886,43.61120191129432,3.8782264085648497,43.613350750790985
Funded by 3Liz
> IGN search string length must be between 3 and 200 chars

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Request/WFSRequestTest.php
Currently client filters and login filters are merged 'as is' before system sends WMS/WFS request to the server.
This could lead to unexpected behavior.
Take, for instance, the case where you have set some login filters in a layer and this layer is displayed as child of another one in the feature popup.
Suppose you want to limit the visibility of `child_layer` only to users belonging to `group1` and use a `lizmap_group` column on `child_layer` to achieve this.
So, if a user belonging to `group1` logs into the project and requests a `parent_layer` popup, the desired behavior is:
```
show only children related to the parent
AND
show only children that current user can see according to login filters
```
Current filter is issued like this:
```
"lizmap_group" = 'group1' OR "lizmap_group" = …
```
> [Bug] Enclose wms/wfs filters in brackets to guarantee filters logic

- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/classes/Project/ProjectTest.php
- tests/units/classes/Request/WFSRequestTest.php
Backport #4836
**Authored by:** @mind84
> [Backport release_3_7] [Bug] Enclose wms/wfs filters in brackets to guarantee filters logic

- assets/src/components/FeaturesTable.js
Improve the style of `lizmap-features-table` child item tables
Before
After
Funded by 3liz
> lizmap-features-table - improve popup table style

- .gitignore
- tests/docker-conf/phpfpm/lizmapConfig.ini.php
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/location_search.spec.js
> [Backport release_3_7] Tests e2e Playwright: Added Location seach

- assets/src/modules/Permalink.js
Plain comparison between `window.location.hash` and hash stored in `Permalink` `_hash` property 
https://github.com/3liz/lizmap-web-client/blob/7bb076d4811fbf4f60c68213dcc1e95116f00f02/assets/src/modules/Permalink.js#L42C21-L42C55
does not work if a layer style contains spaces or other "special" chars. 
If the hash comparison fails, the hash change could be triggered over and over again. This could also be enforced by the fact that the `extension` permalink parameter is converted in `EPSG:4326` from project CRS and converted again to project CRS to set the map extension. In this conversion process, the original coordinates stored in the permalink may be transformed due to rounding
Backport to 3.8
> [Bug] Permalink: encode layers style before hash comparison

- assets/src/components/FeaturesTable.js
- tests/end2end/playwright/lizmap-features-table.spec.js
* Fix **sortingOrder** value in **FeaturesTable**
* Fix the **end2end playwright test**
Funded by 3liz
> Fixing sorting order of the FeaturesTable component

- tests/docker-compose.yml
The latest version of Redis 5 is EOL since April 2020 :/
We need to update a few docker compose file when we find it. I was hesitating to use `latest`.
CC @rldhont @mdouchin @nboisteault @nworr 
@rldhont I haven't tested it, related to our discussion last week, and mainly about environment variables you were talking last week.
> Tests - Update redis version from 5 to 7.4

- assets/src/components/ActionSelector.js
- assets/src/modules/Action.js
- lizmap/www/assets/css/action.css
- tests/qgis-projects/tests/feature_toolbar.qgs.action
- tests/qgis-projects/tests/set_tests_module_action.sql
Funded by WPD
https://github.com/user-attachments/assets/b439917d-55b0-46c8-8ed7-1a4d3ac48e87
> Action: allow geometry drawn by user

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/end2end/playwright/print.spec.js
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/opacity.qgs
- tests/units/classes/Project/Ressources/simpleLayer.qgs.cfg
`Opacity` property is not taken into account on `raster` layers.
**QUESTION REGARDING UNIT TESTS:**
I replaced the php `clone` method used in `QgisProjectTest.php` inside `testSetLayerOpacity` function with `unserialize/serialize`.
It seems to me that the `clone` method doesn't work here since `layers` property is a `StdClass` instance and cannot be cloned this way (?). Basically the test always passes because:
https://github.com/3liz/lizmap-web-client/blob/fc239c68428074326f7cacb983f9fc4f1b50707e/tests/units/classes/Project/QgisProjectTest.php#L394-L396
on line `396` the `$cfg` object is constructed with the `opacity` property already set (added in previous line).
Can you confirm this behavior?
Backport to 3.8, if possible.
> [Bug]: Add layer opacity information to rasters

- assets/src/modules/Popup.js
- tests/qgis-projects/tests/tests_dataset.sql
- tests/qgis-projects/tests/xss.qgs
- tests/qgis-projects/tests/xss.qgs.cfg
Allow iframe in popups but add `sandbox="allow-scripts allow-forms"` to avoid XSS
Funded by Valabre
> XSS: allow `iframe` in popups

- assets/src/modules/map.js
To keep the highlight layer upper the map layers, it will be added in the tools layer group.
* Fixed #4893 
* Fixed #4961
Funded by 3Liz
> [Bugfix] Put highlight layer in tools layer group.

- lizmap/app/system/mainconfig.ini.php
Because of all JavaScripts are `defer` and Lizmap using Bootstrap, the default jForms builder has to be HTML Boostrap.
> Default jForms builder set to HTML Bootstrap

- assets/src/components/FeaturesTable.js
The sortingOrder and draggable attribute values has not to be case sensitive.
Funded Haute-Saone Numérique
> [Bugfix] <lizmap-features-table>: lower case sortingOrder and draggable attribute values

- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/units/classes/Project/QgisProjectTest.php
- tests/units/classes/Project/Ressources/opacity.qgs
- tests/units/classes/Project/Ressources/opacity_embed.qgs
- tests/units/classes/Project/Ressources/opacity_embed.qgs.cfg
- tests/units/classes/Project/Ressources/opacity_source.qgs
- tests/units/classes/Project/Ressources/opacity_source.qgs.cfg
Follows #4925
Here I am again with "embedded" stuff :smile:
I didn't notice that the opacity for embedded rasters wasn't being taken into account, so I tried to fix this.
Thanks
> [Bug] Include layer opacity info for embedded layers

- assets/src/modules/Action.js
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- lizmap/modules/view/templates/popup.tpl
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/rasters.qgs
- tests/qgis-projects/tests/rasters.qgs.cfg
According to what I understood, using data-attributes looks is better ? 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
I see in many places, that in the code, this hidden input value is used.
And then this value need to be split with `.` to separate layer ID and feature ID :
```html
<input class="lizmap-popup-layer-feature-id" value="polygons_1e227060_6105_4a4a_92f2_11863ebe65f1.0" type="hidden">
```
I'm proposing
```javascript
lizMap.events.on({
lizmappopupdisplayed: function (popup) {
// It should be #popupcontent
let popupContainer = document.getElementById(popup.containerId);
if (!popupContainer) return false;
Array.from(popupContainer.querySelectorAll('div.lizmapPopupContent .lizmapPopupSingleFeature')).map(element => { …
```
> Popup - Add layer ID and feature ID as data attributes

- assets/src/modules/state/Symbology.js
- tests/js-units/node/state/symbology.test.js
Enhancing the docstring of JS State Symbology to correctly checking parameters and avoid some issue. Adding test with a special GetLegendGraphics JSON.
Funded by Keolis Rennes
> [Bugfix] JS State Symbology : checking ruleKey for wmsParameters

- lizmap/www/assets/css/map.css
https://github.com/3liz/lizmap-web-client/issues/5023#issuecomment-2508151247
Ticket : fix #5023
Funded by Erwan Vinot
> fix(css): hide only adjacent non-popup-displayed table items

- assets/src/modules/GeolocationSurvey.js
- assets/src/modules/Lizmap.js
> Reduce mainLizmap dependencies in GeolocationSurvey module

- tests/end2end/playwright/filter-layer-by-user.spec.js
@rldhont A follow up from the PR #5053
* Lines are way shorter, no need to have horizontal scrolling
* Parameters are automatically escaped, like `EXP_Filter: '"gid" = 3'`
* Better with Git, easier to see which parameter is updated later
> Tests - Use URLSearchParams constructor to build querystrings

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
Follow up from #4960
Superseeds #5004
> Admin - Log OGC request if error

- assets/src/components/Print.js
- tests/end2end/playwright/print.spec.js
Backport #5069
**Authored by:** @neo-garaix
> [Backport release_3_9] Fixing bug about the print overlay stacking

- assets/src/modules/Action.js
- assets/src/modules/Lizmap.js
> Reduce mainLizmap dependencies in Action module

- assets/src/modules/Lizmap.js
- assets/src/modules/Search.js
> Reduce mainLizmap dependencies in Search module

- assets/src/components/FeaturesTable.js
- assets/src/modules/FeaturesTable.js
- lizmap/modules/lizmap/controllers/features.classic.php
- lizmap/www/assets/css/map.css
- tests/end2end/playwright/lizmap-features-table.spec.js
* Replace the items `<div>` by an HTML `<table>` to prepare the addition of columns
* Allow to add columns from the layer fields : now we can add several columns by adding some `<lizmap-field ... > ... </lizmap-field>` children inside the `<lizmap-features-table>` element
* Add labels of columns in the table
* Add a regular expression verification for the used QGIS expressions in child fields. At present, we only accept expressions requesting fields like `"libsquart"` and not expressions like `rand(10,34)`.
* If fields have the same expression or aliases (except empty ones), only the first one is used.
Example code:
```html
<lizmap-features-table 
layertitle="child sub-districts" 
layerid="sousquartiers_24ceec66_e7fe_46a2_b57a_af5c50389649" 
uniquefield="id" 
expressionfilter="quartmno = …
```
> FeaturesTable structure & columns improvements 

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
**ADDED FEATURES:**
- Add measure tooltip on circles with radius and area measurement
- Initialize measure tooltips on features loaded from `local storage`
**NOTES:**
- Circles area is calculated using the `fromCirlce` method of Openlayers Polygon [class](https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html).
There is another (more verbose) way to do it that involves `circular` method but requires to convert center and "last" coordinates in EPSG:4326.
Given the same polygonal approximation (128 sides), the two methods return the same output so I decided to use the less verbose one.
- For circles, the "segment" tooltip (radius) is no longer displayed near mouse pointer but it's displayed in the interior point of the feature, along with the area measure.  
Feature preview: …
> [Feature] Circular geometry measurement on draw

- assets/src/legacy/attributeTable.js
Backport #5101  backport #5100
**Authored by:** @mdouchin
> [Backport release_3_7] Attribute table - Fix some misbehaviours

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
`jDbConnection::exec()` returns the number of affected rows or False if the query has failed.
In some cases, for exemple a `DELETE` on a view or a `DELETE` catched by a trigger, this method can return no affected rows. So Lizmap has to `rollback()` executed requests only if a query has failed.
Funded by Conseil Départemental du Calvados and Ville d'Avignon
> [Bugfix] Edition : exec a DELETE can return 0 in some cases

- lizmap/modules/action/controllers/service.classic.php
When **not** connected on the instance @mdouchin 
Does the action writer is using `raise` to show error to the end user ?
> Display a generic error in case of action failure to the end-user

- assets/src/legacy/edition.js
- tests/end2end/cypress/integration/feature_toolbar-ghaction.js
Fix edition form when lauchind children creation from attriute table button : 
if there's a relation between parent id (in a select) and an other control, the value weren't updated.
the `select` is now not set as `disabled` but hidden and a disabled input is added ( look alike a select)
Also mini fix on attribute table : the children table didn't work in some case.
Ticket : #4898
Funded by 3Liz
> Fix edition form child with relation

- assets/src/modules/Digitizing.js
The print output of a text label added with the `Digitizing` tool includes the point point symbol associated with the label:
Since this point is only used to place the text label on the map, it should be hidden in the print output. 
The solution proposed (the simplest I guess) is to set `fill` and `stroke` opacity symbol parameter to 0 for `textonly` feature only:
Backport to 3.8
> [Bugfix] Digitizing: hide text feature point geometry on print output

- lizmap/modules/lizmap/controllers/edition.classic.php
Ticket #3084
It seems there is already some log in the function `saveToDb`, to have some better details.
Quite linked to #5105 and #5066, we should a have static method from PR #5066 to format a string according to the given PHP array with ordered list of expected keys first.
> Add a log if saving the feature has failed

- assets/src/legacy/edition.js
When an editing form is opened in Lizmap, and the user tries to open a new editing form, a confirmation message is shown asking to confirm the cancellation of the current editing.
Sometimes, the current active form is not visible, for example when the user has displayed the layer tree instead of the editing form in the left dock.
This PR ensures that the editing form is shown back to the user before displaying the confirmation dialogue.
Funded by Métropole Aix-Marseille-Provence https://ampmetropole.fr/
> Editing - Make sure the dock with the form is visible before opening the cancelation confirmation dialog

- assets/src/components/FeaturesTable.js
- tests/end2end/playwright/lizmap-features-table.spec.js
Improvements on the `<lizmap-features-table>` web component:
* The `expressionFilter` attribute change is now listened, and any change triggers a reload of `<lizmap-features-table>`.
* The end-to-end test file `lizmap-features-table.spec.js` has been improved to test the modification of the `expressionFilter` attribute.
Funded by Andromède Océanologie https://www.andromede-ocean.com/
Ticket : #5146
> Features Table : listen for change of the attribute `expressionfilter` and reload table

- assets/src/components/FeaturesTable.js
Improvements for the `<lizmap-features-table>` web component:
* Now, when an item is highlighted, an event `features.table.item.highlighted` is sent with the item's `feature_id`.
Funded by Andromède Océanologie https://www.andromede-ocean.com/
Ticket : #5146
> Features Table : add an event when an item is highlighted

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- tests/end2end/playwright/server-information.spec.js
As now, it's not only Py-QGIS-Server which can be used, it can also be QJazz : 
CF work started in https://github.com/3liz/qgis-lizmap-server-plugin/pull/100
I also moved the commit ID next to the version number, same as for LWC main version and plugins.
PS : I have changed the name, **temporary**, in source code itself for the screenshot, for trying for now, waiting on https://github.com/3liz/qgis-lizmap-server-plugin/pull/102 and https://github.com/3liz/lizmap-web-client/pull/4991
> Use correct online help and Git repository according to the correct QGIS Server wrapper used

- .github/workflows/php-stan.yml
Defined Github Action PHPStan Matrix with PHP version:
* 7.4
* 8.0
* 8.1
* 8.2
* 8.3
Instead of only 8.2
> Github Action PHPStan Matrix

- .github/workflows/php-stan.yml
- .github/workflows/tests.yml
- CHANGELOG-3.9.md
- lizmap/composer.json
- tests/units/composer.json
Following the PHP roadmap : https://www.php.net/supported-versions.php
But the issue is about Debian bulleyes, for which it will not be compatible.
~We talked about targeting LWC 3.9 for this change, but I was wondering if we keep this for LWC 3.10 which already include a "breaking" change with the migration from Bootstrap 2 to Bootstrap 5 #4861. (we can check if LWC should switch to 4.0 ?)~
CC @laurentj @mdouchin @mind84 @guenter
> Raise PHP minimum version to 8.1

- .github/workflows/e2e_tests.yml
> Tests - Better log output in case of error

- .github/workflows/e2e_tests.yml
> GH Action - Check for QGIS Server status and git diff

- assets/src/components/FeaturesTable.js
Improve the way the web component `<lizmap-features-table>` displays the popup of a feature when the user clicks on its title.
This adds a new way to load the component with a highlighted feature at startup, 
by adding a new optional attribute `data-active-item-feature-id`. 
If this attribute is set to a valid feature ID, the table will be hidden and the corresponding feature popup visible.
For example:
* By setting the attribute in the HTML element definition:
```html
<lizmap-features-table
sortingorder="asc" sortingfield="libsquart" 
withgeometry="1" 
expressionfilter="quartmno = 'MC'" 
uniquefield="id" 
data-center-to-highlighted-feature-geometry="true" 
data-show-highlighted-feature-geometry="true" 
layerid="sousquartiers_24ceec66_e7fe_46a2_b57a_af5c50389649" 
layertitle="child …
```
> lizmap-features-table - Improve the logic of the feature detail opening

- lizmap/modules/lizmap/lib/Project/QgisProject.php
Follow #5193 
It seems xpath queries are time consumming, so : 
- improvement to use objet info instead of xpath to search for embedded layers (prevent as many xpath queries as layers).
- xpath query in source project for embedded layer search the right layer directly
Ticket : #
Funded by 3Liz
> don't use xpath to search embedded layers, but layer objet info

- lizmap/composer.json
- lizmap/modules/dataviz/classes/datavizPlot.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/controllers/edition.classic.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Form/QgisFormValueRelationDynamicDatasource.php
- phpstan-baseline.neon
JSON-Machine is a very easy to use and memory efficient drop-in replacement for inefficient iteration of big JSON files or streams for PHP https://github.com/halaxa/json-machine
In some part of Lizmap PHP code, GetFeature GeoJSON are read in an inefficient way.
> PHP: reading GetFeature GeoJSON as a stream with JSON-Machine

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
The WFS service is needed by the lizmap web user interface, but the direct access is managed by 'Allow export of vector layers' right.
Funded by Andromède Océanologie
> OGC Service WFS: Forbidden direct access without rights

- lizmap/modules/admin/controllers/logs.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/logs_view.tpl
- lizmap/www/assets/js/admin/scroll_to_bottom_textarea.js
Logs are important, this panel should be more advertised and used. Some upgrades should be done, in this PR and later.
Some review on the log panel :
* Increase from 50 to 200 lines, can we increase more ? Or we should a way to scroll more up if necessary, later.
* Rename "Log" to "Admin log", following #3831
* Adding a text area for the "error log", https://github.com/3liz/lizmap-web-client/issues/5106#issuecomment-2536554681. I didn't add the "Erase button" for this log.
* The new text area is hidden or not according to the flag "sensitive data flag".
> Add error log panel in admin

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/media.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/pages/project.ts
- tests/end2end/playwright/project_load_warning.spec.js
- tests/end2end/playwright/snap.spec.js
Adding POM : https://playwright.dev/docs/pom
Superseeds #5167
> Tests - Start Page Object Model for Playwright

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/ProxyResponse.php
- tests/end2end/cypress/integration/requests-wfs-ghaction.js
- tests/units/classes/Request/ProxyResponseTest.php
- tests/units/classes/Request/ProxyTest.php
`X-Request-Id` correlates HTTP requests between a client and server. It will help to correlate logs between Lizmap Web client and QGIS Server. `X-Request-Id` is supported by Py-QGIS-Server.
> Add X-Request-Id in request to QGIS Server headers

- lizmap/modules/lizmap/lib/Request/Proxy.php
Remove deprecated code about sending requests.
> [PHP] Only use Guzzle to send requests

- tests/end2end/playwright/bad-repository.spec.js
- tests/end2end/playwright/landing_page_config.spec.js
- tests/end2end/playwright/maps-management.spec.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/homepage.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/server-information.spec.js
Follow up from #5204
Add some base classes to test the admin side, or the landing page. I have checked a little bit with Cypress tests as well, for later.
I will stop here about Playrwight Object Model, it was to start to use this, for better maintenance.
I'm just not sure why we need a "new" object, in the test itself.
> Tests - Extends base class for testing admin pages and landing page

- tests/end2end/playwright/bad-repository.spec.js
- tests/end2end/playwright/maps-management.spec.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/server-information.spec.js
Backport #5225 
There isn't any tests about the landing page on this 3.7 branch.
> [Backport 3.7] Tests - Extends base class for testing admin pages

- tests/end2end/playwright/form-filter.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/timemanage.spec.js
Method to re-send the request with additionnal echo param to retrieve the OGC Request parameters
> Tests e2e Playwright: Defined global getEchoRequestParams

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/timemanage.spec.js
> [Backport release_3_8] Tests e2e Playwright: Defined global getEchoRequestParams

- assets/src/modules/Digitizing.js
- assets/src/modules/Lizmap.js
- assets/src/modules/Snapping.js
- assets/src/modules/Tooltip.js
- assets/src/modules/map.js
- assets/src/modules/state/Map.js
Remove dependencies of Globals mainLizmap singleton
> [JavaScript] reduce mainLizmap dependencies

- lizmap/modules/lizmap/lib/Request/Proxy.php
Follow up from #4998 
```
2025-01-27 16:09:19	172.18.0.1	error	The HTTP request ended with an error. HTTP code 422. → http://map:8080/ows/?map=tests%2Frasters%2Eqgs&request=getcapabilities&service=WFS&version=1%2E0%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=admins&Lizmap%5FOverride%5FFilter=1
[2]	Undefined array key 0
/srv/lzm/lizmap/modules/lizmap/lib/Request/Proxy.php	470
```
I haven't really checked what to add instead...
https://stackoverflow.com/questions/1176022/unknown-file-type-mime
> Guzzle - Content-Type is not always provided

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- tests/units/edition/qgisVectorLayerDatasourceTest.php
Fix to authente layers against qGIS auth config when applying a filter in lizmap web client 3.8.1
Fixes #4470
Extend #4794
Funded by sponsored development
> fix authenticating layers against qGIS auth config

- lizmap/modules/view/controllers/translate.classic.php
New PR like #5139 or #5131 adding new strings in `lizDict` are missing translations when using LWC in another language than English, until we do the update with [Lizmap locales process](https://github.com/3liz/lizmap-locales).
I'm clearly not sure if it's the purpose in this file to add the fallback, or if it must be done elsewhere, upstream etc.
> Merge fallback locales in lizDict

- tests/end2end/playwright/attribute-table.spec.js
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/pages/admin.js
- tests/end2end/playwright/pages/base.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/requests-metadata.spec.js
> [Backport release_3_7] Tests e2e playwright : Lint tests and POM

- tests/end2end/playwright/cors.spec.js
- tests/end2end/playwright/custom-javascript-api.spec.js
E2E - Add some tags on CORS tests and flaky OpenLayers
`@flaky` and `@localonly`
https://playwright.dev/docs/test-annotations#skip-a-test
> E2E - Add some tags on CORS tests and flaky OpenLayers

- lizmap/composer.json
- lizmap/modules/lizmap/install/upgrade_requestscache.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
- lizmap/modules/lizmap/lib/Request/QgisServerMetadataRequestMatcher.php
- lizmap/modules/lizmap/lib/Request/RequestCacheStorage.php
- lizmap/var/config/profiles.ini.php.dist
- tests/docker-conf/phpfpm/profiles.ini.php
- tests/units/classes/Request/QgisServerMetadataRequestMatcherTest.php
Adding [Kevinrob/guzzle-cache-middleware](https://github.com/Kevinrob/guzzle-cache-middleware), to defined cache strategy for caching QGIS Server metadata.
The main goal is to reduce the number of request to QGIS Server to get it's metadata. The QGIS Server metadata request's result will be stored during 60 seconds. During this time, no more QGIS Server metadata request will be performed.
Adding a new `jCache` profile : `requests`.
> PHP: caching QGIS Server metadata

- tests/end2end/playwright/print.spec.js
Refactoring print end2end playwright tests.
> Tests e2e  playwright print refactoring

- tests/README.md
- tests/end2end/playwright/overview.spec.js
- tests/end2end/playwright/permalink.spec.js
- tests/end2end/playwright/project_load_warning.spec.js
- tests/end2end/playwright/qgis-request.spec.js
- tests/end2end/playwright/viewport.spec.js
Tests - Migrate overview tests : 
* POM
* expectParametersToContain
* TRANSPARENT regexp
> Tests - Migrate overview tests

- phpstan-baseline.neon
Remove some PHPStan ignore errors
> Removed some PHPStan ignoreErrors

- lizmap/modules/lizmap/classes/lizmapWkt.class.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/units/classes/lizmapWktTest.php
The WKT geometry provided by QGIS Server in GetFeatureInfo does not contain a space between the geometry type and the dimension.
Funded by Syslor https://syslor.net
> Fix WKT geometry string provided by QGIS Server in GetFeatureInfo

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/map-projects-switcher.spec.js
- tests/end2end/playwright/print.spec.js
- tests/end2end/playwright/print_in_project_projection.spec.js
- tests/end2end/playwright/timemanage.spec.js
Before, it was a "poor" debug info : 
```
Error: expect(received).toBe(expected) // Object.is equality
Expected: 15
Received: 14
522 |         })
523 |         let getPrintParams = await expectParametersToContain('Print requests 1', getPrintRequest.postData() ?? '', expectedParameters1)
> 524 |         await expect(getPrintParams.size).toBe(15)
```
Which is not meaning ful, because we don't know what was in the list before. I expect `toHaveLength` to show the list content ?
Otherwise, we will add a flag in `expectParametersToContain` to check the size of parameters and to display them nicely if faulty
> Tests - Use toHaveLength

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/project_list_zone.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/classes/lizmapRepository.class.php
- lizmap/modules/lizmap/lib/Project/Repository.php
- tests/end2end/playwright/admin-qgis-projects.spec.js
- tests/end2end/playwright/pages/admin.js
Due to #5399, the `admin` in the Lizmap docker test stack couldn't see a QGIS project, limited to sub set of group (but not `admin` group)
I'm not sure if we should backport to 3.8 ? (let's say no)
> Avoid an admin to NOT see some projects in the administration panel

- .github/workflows/lint.yml
- lizmap/modules/lizmap/classes/lizmap.class.php
- lizmap/modules/lizmap/classes/lizmapTiler.class.php
- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php
- lizmap/modules/lizmap/classes/tools.class.php
- lizmap/modules/lizmap/lib/CliHelpers/WMTSCache.php
- lizmap/modules/lizmap/lib/Commands/ProjectLoad.php
- lizmap/modules/lizmap/lib/Commands/WMTSCacheClean.php
- lizmap/modules/lizmap/lib/Commands/WMTSCapabilities.php
- lizmap/modules/lizmap/lib/Commands/WMTSSeed.php
- lizmap/modules/lizmap/lib/Form/QgisForm.php
- lizmap/modules/lizmap/lib/Logger/Config.php
- lizmap/modules/lizmap/lib/Project/Project.php
- lizmap/modules/lizmap/lib/Project/ProjectConfig.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- lizmap/modules/lizmap/lib/Request/WFSRequest.php
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/classes/lizmapMapDockItem.class.php
- tests/README.md
- tests/units/composer.json
- tests/units/listRules.php
- tests/units/rector.php
- tests/units/testslib/ContextForTests.php
_Improvement of #5352_
[Rector](https://github.com/rectorphp/rector) instantly upgrades and refactors the PHP code of your application. It can help you in 2 major areas:
* Instant Upgrades
* Automated Refactoring
Rector can help us to upgrades and refactors Lizmap step by step with levels https://getrector.com/documentation/levels
* Now we can execute `composer rector` in order to upgrade/refactor PHP code
* Added a `listRules.php` that is executed before `rector` work. It is done to summarize which rule is applied depending on which level we put in `rector.php` for each set of rules.
_I put this in another file because `rector.php` is called multiple times when we launch it so it would have sent the summarize multiple times_
* Added it in the `lint` workflow
Example : 
Funded by 3Liz
> Rector - PHP instant Upgrades and Automated Refactoring

- .github/workflows/cron_e2e.yml
- .github/workflows/docs.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- tests/README.md
GH Action - Refactor versions used about PHP and Node, remove 3.7 from cron
> GH Action - Refactor versions used about PHP and Node, remove 3.7 from cron

- lizmap/modules/admin/controllers/maps.classic.php
- lizmap/modules/admin/templates/config_section.tpl
- lizmap/modules/admin/templates/maps.tpl
- lizmap/www/assets/css/admin.css
- tests/end2end/playwright/maps-management.spec.js
To easily come back to the right position in the repositories page, anchors has been added.
> [Admin] Add anchors to repositories page

- assets/src/modules/Config.js
- assets/src/modules/State.js
- assets/src/modules/config/LayerTree.js
- tests/js-units/node/config/baselayer.test.js
- tests/js-units/node/config/layerTree.test.js
- tests/js-units/node/config/layersOrder.test.js
- tests/js-units/node/state/baselayer.test.js
- tests/js-units/node/state/externallayertree.test.js
- tests/js-units/node/state/externalmaplayer.test.js
- tests/js-units/node/state/layer.test.js
- tests/js-units/node/state/layerTree.test.js
- tests/js-units/node/state/maplayer.test.js
I'm keen to have some feedbacks here.
For now, globally in Lizmap, if an error occurs, there is nothing displayed in the user interface. The only way is to open the developer tools, which is not a good advice, our admin end-users shouldn't open the web developer tools.
It would be nice, at the end of loading a map, a UI box is displayed if there were any "error" during loading the map ?
Just to keen to have ideas
> API - Retrieve invalid layers between GetCapabilities en CFG file

- Makefile
If I'm not wrong, nobody run `php-cs-fixer` from the OS, but I think always in Docker instead ?
CC @mind84 @rldhont @nboisteault @mdouchin @nworr @laurentj  Put your emoji if we can remove this ;-)
> Makefile - remove PHP-CS-Fixer command installed on the local machine

- tests/end2end/playwright/globals.js
- tests/end2end/playwright/pages/project.js
Helper for fixing tests related to QGIS Desktop 3.40
> Tests - Add helper to retrieve the QGS file path on the file system

- .github/workflows/e2e_tests.yml
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/print.spec.js
Tests - Improve debug when the length is not the same
I'm not fond of this function, but it helps on current failing tests on 3.40 (and for later).
We could argue that we can check members instead of length...
> Tests - Improve debug when the length is not the same

- assets/src/components/Digitizing.js
Linked to #5375, nothing interesting here, just splitting HTML attributes on multiple lines
> Refactoring - Review Digitizing.js to split attributes in HTML

- lizmap/modules/dataviz/classes/datavizPlot.class.php
Fix regression from #5434 
The **body** contains a HTML string about a PHP warning sometimes :(
```html
Error while parsing to JSON : 
SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
<br />
<b>Warning</b>:  The use statement with non-compound name 'JsonMachine' has no effect in <b>/srv/lzm/lizmap/modules/dataviz/classes/datavizPlot.class.php</b> on line <b>13</b><br />
{"title":"Municipalities","data":[{"type":"bar","name":"id","y":[0,1,2,3,4,5,6,7,8,9],"x":["Grabels","Clapiers","Montferrier-sur-Lez","Saint-Jean-de-
```
instead of plain JSON.
I think there is a misconfiguration issue from the PHP side as well.
> Change the PHP namespace for JSON Machine

- assets/src/legacy/edition.js
Linked to TDPA issue in 20/02/25 email
> Fix: JS error if `pivotAttributeLayerConf` is undefined

- assets/src/legacy/map.js
PR related to https://github.com/3liz/lizmap-web-client/pull/4768
Probably situational, the PR covers the case where the `Popup` includes more than one relation that involves the same layer as a child. In this case it is safer to rely on the `relation id` to correctly position the children rather than the `layer id`. 
Backport to 3.8 and 3.9, if possible
> [Refactoring] Rely on relation id for children popup positioning

- assets/src/legacy/map.js
mainLizmap may not be ready when configs are loaded, so we have to wait until it is ready to listen to `configsloaded` event.
Fixes https://github.com/3liz/lizmap-web-client/issues/5452
> [Fix JS] mainLizmap may not be ready when configs are loaded

- lizmap/modules/lizmap/classes/qgisVectorLayer.class.php
- lizmap/modules/lizmap/lib/Request/WMSRequest.php
When a popup is displayed the system checks first whether the user can edit the feature or not, so as to configure the `lizmap-feature-toolbar` HTML element correctly.
At time being, if the layer is `filtered by user` (`Attribute filtering` tab in Lizmap plugin), the system queries all the features of the layers and then filters the entire list by feature id to perform the check.
https://github.com/3liz/lizmap-web-client/blob/25ba42bac31e7fc60df93a1fbd4785c8749e7529/lizmap/modules/lizmap/lib/Request/WMSRequest.php#L785
This operation is executed for every feature on popup, even if features belonging to same layer.
If the layer has a lot of feature then this operation easily leads to php exceptions (`max_execution_time` on master branch with `jsonmachine`, memory error for Lizmap <= 3.8 ) …
> [Bugfix] Multiple calls of editableFeatures method breaks php

- package-lock.json
- package.json
I do not find any occurences about `pixelmatch`, CF #5489
We could see PixelMatch in some PR, like https://github.com/3liz/lizmap-web-client/pull/3029
https://github.com/search?q=repo%3A3liz%2Flizmap-web-client%20pixelmatch&type=code
Even in 3.8 branch.
> Drop pixelmatch from package.json

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
Follow up from #5304, it displays a message for admins about layers which are not found in the CFG file (but present in the WMS GetCapabilities)
Related to #5424 about how we want to manage admin/not admins in LWC, and also how to report "broken" project to the GIS administrator about errors reported on the "client" side.
Another change : we always log in the console in case of warning about the QGIS project, even if the user is not an GIS administrator
> Show not found layers in the CFG for admins

- lizmap/modules/lizmap/lib/Form/QgisForm.php
- tests/end2end/playwright/axis_orientation.spec.js
- tests/units/classes/Form/QgisFormTest.php
The form feature's geometry was not provided for QGIS expression constraint.
Funded by Syslor
> [Fix] QGIS constraint with geometry

- assets/src/modules/config/BaseLayer.js
- tests/end2end/playwright/google-basemap.spec.js
- tests/qgis-projects/tests/google_apikey_basemap.qgs
- tests/qgis-projects/tests/google_apikey_basemap.qgs.cfg
- tests/qgis-projects/tests/google_basemap.qgs
- tests/qgis-projects/tests/google_basemap.qgs.cfg
Google tile layers `roadmap` and `satellite` have been added in #4357 .
This PR adds the `terrain` layer in the list.
Funded by Qair https://www.qair.energy/
> Google maptile add Terrain layer

- lizmap/modules/lizmap/templates/user_menu.tpl
- tests/end2end/playwright/header.spec.js
- tests/qgis-projects/tests/set_tests_respository_rights.sql
This allows a JavaScript script to get the current user organization and use it in the editing form.
Ticket : #
Funded by Ville d'Avignon https://cartes.mairie-avignon.com
> Header - Add authenticated user organization in hidden fields

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/app.classic.php
- tests/end2end/playwright/requests-metadata.spec.js
It's checking the version in `project.xml` against all "core Lizmap" modules thanks to the `installer.ini.php`.
It's to avoid some possible migrations issues
It will be manually backported to 3.9 and 3.8 due to Bootstrap 5.
> Admin - Display if the installation is not complete according to versions in installed modules

- lizmap/modules/lizmap/lib/Request/OGCRequest.php
- lizmap/modules/lizmap/lib/Request/Proxy.php
fix: In Guzzle, provided HTTP headers is an array
Superseeds #5510
> fix: In Guzzle, provided HTTP headers is an array

- assets/src/modules/LocateByLayer.js
After https://github.com/3liz/lizmap-web-client/pull/5334 the locateByLayer contains an error
> [Bugfix] LocatByLayer - Error after automatic ESlint 

- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/App/VersionTools.php
- tests/units/classes/App/VersionToolsTest.php
Fix regression from #5478
On Snap servers, the version is `3.10.0-pre.8697` while module versions are like `3.10.0-pre`. This was raising the message from PR #5478
AS this is for 3.8 branch, I will do another refactoring by moving version functions to this new file in another PR targeting only 3.9.
> fix: The version of LWC has a commit number in the version name, drop it for comparing to modules version

- tests/end2end/playwright/n_to_m_relations.spec.js
- tests/end2end/playwright/print.spec.js
- tests/end2end/playwright/webdav-upload.spec.js
It is necessary as bootstrap tooltips have been disactivated for some buttons in ab01c62e7c323f309a6b52e1b5b592c3c812b831
> e2e: replace `data-original-title` by `title`

- assets/src/modules/ExecuteJSFromServer.js
- lizmap/modules/view/controllers/lizMap.classic.php
- tests/end2end/playwright/filter-layer-by-user.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/project_load_warning.spec.js
- tests/qgis-projects/tests/project_cfg_warnings.qgs
- tests/qgis-projects/tests/project_cfg_warnings.qgs.cfg
Tests - Do not display a warning about outdated QGIS plugin version in tests when required, needed for checking warnings about layers
This should fix one issue from QGIS 3.40 E2E tests
> Tests - Do not display a warning about outdated QGIS plugin version in tests when required, needed for checking warnings about layers

- assets/src/modules/Digitizing.js
- tests/end2end/playwright/draw.spec.js
- tests/end2end/playwright/pages/drawpage.js
- tests/end2end/playwright/pages/project.js
When both dimension and angle constraints are set in the drawing tool, the resulting `linestring` length measurement is incorrect.
TEST NOTICE:
@Gustry,
I assumed that the `draw.spec.js` test will be refactored to be POM compliant, so for now I just added a new subtest in the "traditional" way. It makes more sense to me to refactor all the code at once, so I think it's best to keep it in a separate PR.
Backport 3.8, 3.9
Funded by Etra
> [Bugfix] Wrong measure when both angle and dimension constraints are set on drawing tool

- assets/src/modules/Search.js
The IGN address search uses the map view instead of maxExtent. So if the user a zoom, he cannot get back to an other place contains by the map's max extent.
Funded by WPD Onshore France
> [Bugfix] JS Search: IGN address search uses map view instead of maxExtent

- assets/src/legacy/atlas.js
- tests/end2end/playwright/viewport.spec.js
The features were not projection to map projection when they were used to zoom to. Regression introduced by  Zoom to features with a max scale constraint #4897
Funded By WPD Onshore France
> [Bugfix] JS Atlas: features were not projected to map

- assets/src/legacy/filter.js
Sometimes the zoom stops to work correctly
Let's use the OL10 map to zoom
Ticket : paid support 3413
Funded by SMICA
> Fix: zoom in form filter

- lizmap/www/assets/css/map.css
- lizmap/www/themes/default/css/map.css
The new CSS will make the D&D popup displays very similar to the editing form
Before
After
Funded by Destination Bretagne Sud Golfe du Morbihan
> Popup - Improve styling of Drag&Drop designed popup

- lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php
- lizmap/modules/lizmap/controllers/features.classic.php
- tests/end2end/playwright/lizmap-features-table.spec.js
- tests/qgis-projects/tests/lizmap_features_table.qgs
Thanks to https://github.com/3liz/qgis-lizmap-server-plugin/pull/109, it is possible to have more QGIS expressions to be evaluated which are in `lizmap-fields`
> Lizmap-Features-Table - Evaluate QGIS expressions which are in lizmap-field

- tests/end2end/playwright/edition-form.spec.js
- tests/end2end/playwright/embedded-relation.spec.js
- tests/end2end/playwright/n_to_m_relations.spec.js
- tests/end2end/playwright/pages/project.js
- tests/end2end/playwright/webdav-upload.spec.js
Updates some e2e tests following  https://github.com/3liz/qgis-lizmap-server-plugin/commit/1b4a14c63f8ac3c5f51bee23678e8dafa820f9ae
- `edition-form.spec.js` and `embedded-relations.spec.js` have been refactored to be POM compliant
- `n_to_m_relations_spec.js` and `webdav-upload.spec.js` have been partially refactored. These two tests requires a lot of effort to be completely refactored so for now I've just made some changes in locators to make them work properly with the new HTML template.
- 
> [Test] Refactoring e2e tests due to popup html changes

- lizmap/modules/lizmap/classes/lizmapFts.class.php
- lizmap/modules/lizmap/controllers/searchFts.classic.php
- tests/end2end/playwright/globals.js
- tests/end2end/playwright/location_search.spec.js
- tests/end2end/playwright/requests-api.spec.js
- tests/end2end/playwright/requests-metadata.spec.js
Lizmap search was always return HTTP code 200 even if the query has failed.
It returns now correct HTTP code, and logging in the admin panel at the same time in case of an exception.
Follow up from previous PR #5619
> Return correct HTTP code if the lizmap_search has failed

- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/maps.tpl
* Remove this legacy `1` or `0` about "allow user defined themes"
* Add tooltips on buttons, ref https://github.com/3liz/lizmap-web-client/issues/5607#issuecomment-2792511447
> UX - Add tooltips on buttons in the maps management page (and remove this 1/0 about user defined themes)

- lizmap/modules/view/templates/view.tpl
- tests/end2end/playwright/project-homepage.spec.js
Read my comment https://github.com/3liz/lizmap-web-client/pull/4032#issuecomment-2056588757 exactly one year ago, I'm keen to have feedbacks.
These extents are not human-readable and are not designed to be shown like this IMHO. (especially on a landing page, for end users)
~I'm even thinking to backport to 3.8.~
The next step is to remove totally this hover div I think, but first removing these numbers.
Linked to #3558 cc @gioman
> Remove BBOX and proj name from the landing page

- assets/src/legacy/map.js
- tests/end2end/playwright/popup.spec.js
The popup geometry was not cleared when the dock popup is closed and the click on the map does not return GetFeatureInfo. The popup geometry was not redraw when the dock popup is opened and contains GetFeatureInfo
Funded by Syslor
> Fix UI regression: Clear popup geometry

- lizmap/modules/admin_api/controllers/project_rest.classic.php
- lizmap/modules/lizmap/lib/Project/QgisProject.php
- tests/end2end/playwright/requests-api.spec.js
Follow up from #5596 
All variables were using camelCase convention. So I have changed in the API, despite the value in the XML which is `projectname`.
> Minor updates on docstring PHP in the project API

- assets/src/components/FeaturesTable.js
@vlebert and @mdouchin 
https://github.com/3liz/lizmap-web-client/pull/4502#issuecomment-2837866857
> However I think we miss the layer ID in addition to the feature ID. Otherwise we don't know which lizmap-features-table-container did trigger the signal and we may have different behaviour for different lizmap-features-table-container
I haven't tested, just a quick addition.
> Lizmap-features-table : Add layer ID in the signal highlighted

- assets/src/legacy/attributeTable.js
When attribute table has to format a big table, the interface can freeze. The freeze has been introduced by DOMPurify which format text as a XSS sanitizer.
Funded by Agence des 50 pas de Guadeloupe, Cartophyl, FM Projet
> JS Attribte Table: format big data

- assets/src/legacy/attributeTable.js
When attribute table has to format a big table, the interface can freeze. The freeze has been introduced by DOMPurify which format text as a XSS sanitizer.
Funded by Agence des 50 pas de Guadeloupe, Cartophyl, FM Projet
> [Release_3_9] JS Attribte Table: format big data

- assets/src/modules/Search.js
Fix: When using quick search menu you can't zoom back to a feature after moving the map
Fix #5564
Funded by 3liz
> Fix: When using quick search menu you can't zoom back to a feature after moving the map

- assets/src/modules/Search.js
> [Backport release_3_8] Fix: When using quick search menu you can't zoom back to a feature after moving the map

- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- lizmap/modules/view/templates/view.tpl
Same as #5635
Extents are not human readable. Lizmap is used by non GIS end users. If some people want to display these extents, they can still do it with some Javascript with these data-attributes `data-lizmap-bbox`, `data-lizmap-proj`
Keen to have feedback, it will be merged after #5635
Fix #3558 cc @gioman
> Remove BBOX and proj name from project info

- lizmap/app/system/mainconfig.ini.php
- lizmap/modules/admin/controllers/server_information.classic.php
- lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
- lizmap/modules/admin/templates/server_information.tpl
- lizmap/modules/lizmap/lib/Server/Server.php
- lizmap/modules/view/controllers/default.classic.php
- lizmap/modules/view/controllers/lizMap.classic.php
- lizmap/var/config/localconfig.ini.php.dist
Given the discussion in #5567 and that many "Lizmap" developers haven't used or tried QGIS FCGI for many years, I'm adding a setting to force or not Py-QGIS-Server.
By default, Py-QGIS-Server must be used according to the default value in the settings file. This can be changed of course.
Linked to https://github.com/3liz/lizmap-documentation/pull/272
> Force QGIS Server to use Py-QGIS-Server

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/testslib/WMSRequestForTests.php
`#(["\']){1}((\.\./)?media/.+\.\w{3,10})(["\']){1}#` is replaced by `#["\']((\.\./)?media/.+?\.\w{3,10})["\']#`
`.+` part is made ungreedy
Funded by AUDIAR
> Fix: incorrect replacement in `<a href="media/"><img src="media/"></a>`

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/testslib/WMSRequestForTests.php
> [Backport release_3_9] Fix: incorrect replacement in `<a href="media/"><img src="media/"></a>`

- lizmap/modules/lizmap/lib/Request/WMSRequest.php
- tests/end2end/playwright/popup.spec.js
- tests/qgis-projects/tests/popup.qgs
- tests/units/classes/Request/WMSRequestTest.php
- tests/units/testslib/WMSRequestForTests.php
> [Backport release_3_8] Fix: incorrect replacement in `<a href="media/"><img src="media/"></a>`

- assets/src/modules/state/Map.js
Use JSDoc @import to generate the right linked beetween EventDispatched and the MapState events
> JS Doc: right references to EventDispatched for MapState events

- assets/src/modules/Lizmap.js
The WMS Capability XML file sometimes does not contain `BoundingBox` elements in the root `layer` element. So the `wmsCapabilities.Capability.Layer.BoundingBox` is not an array.
Fixed #5730
Fixed #5617
> [Bugfix] The WMS Capability root layer has no bounding boxes

- assets/src/modules/Digitizing.js
When closing draw dock, the digitizing is still active. The user can continue drawing even if the interface is not available.
Funded By WPD Onshore France
> Fix Digitizing module: deactivate it when draw is closed

- assets/src/legacy/filter.js
- assets/src/legacy/map.js
> [Backport release_3_8] Fix: `0` integer is transformed to an empty string by `DOMPurify.sanitize()`

- lizmap/modules/lizmap/classes/lizmapFts.class.php
Just like item_projects in the lizmap_search view was accepting a comma sperated list of items, this enables the filter to be supplied with a list of users/groups
> Update lizmapFts.class.php - upgrade item_filter to accept comma-seperated list

- tests/README.md
- tests/docker-compose.yml
This way, `openldap` and `swagger` are not used for e2e tests
> CI: create a docker compose`dev` profile

- lizmap/modules/view/controllers/media.classic.php
- tests/end2end/playwright/media.spec.js
To be able to get a range of a file stored in media directory, the GetMedia function of the controller media of view module now supports HTTP Range headers.
Funded by Syslor
> Support HTTP Range header for files in media with GetMedia

- lizmap/modules/view/controllers/lizMap.classic.php
Add open graph tags in map page html header
It will allow various apps/social networks to propose an enriched content (image, title) when a link is posted .
It use the same values as the repository page : title , abstract, illustration image
See the result with firefox extension "open graph preview" for "montepellier" demo project
More info  : https://ogp.me/
Funded by 3Liz
> add opengraph tags for map page

- assets/src/modules/LocateByLayer.js
`DOMPurify.sanitize` needs a string and `null` value does not have a `toString` method.
Completing https://github.com/3liz/lizmap-web-client/pull/5898
Funded by Cadageo
> Fix JS: LocateByLayer does not support null value because of DOMPurify.sanitize Suite

- lizmap/modules/lizmap/classes/lizmapLog.listener.php
- lizmap/modules/lizmap/daos/logDetail.dao.xml
When anoter entry point (installed by an external lizmap module) is performing an authentication process, the "login" event will now  be `<entry-point>-login` and will be filtered from log pages (as QGIS plugin login see https://github.com/3liz/lizmap-web-client/pull/5845)
Ticket : #
Funded by 3Liz
> Detect entry point when login event and adapt event key

- tests/end2end/playwright/popup.spec.js
After 4f47864a1c53788cf1e7bbf628025c548c911b3e homogenize end2end Playwright popup tests about default buffer length.
> Fix e2e playwright tests popup: default buffer length

- tests/end2end/playwright/popup.spec.js
> [Backport release_3_9] Fix e2e playwright tests popup: default buffer length

- .github/workflows/e2e_tests.yml
- tests/Makefile
- tests/README.md
- tests/add_server_plugins.sh
- tests/docker-conf/unstable-plugin-sources.list
- tests/lizmap-ctl
Simplify commands for local and CI tests.
Deprecate `./run-docker` which is only a pass-through to make without really value-added and allows more fine grained  command execution.
> Deprecate `run-docker`

- tests/units/composer.json
In the Github wrokflows, the PHP-Unit version is 11.5.2 and 10 for local.
The default PHP version for tests is 8.2.
> Tests: PHP-Unit 11 for local like in Github workflows

- lizmap/modules/lizmap/controllers/features.classic.php
- tests/end2end/playwright/tooltip.spec.js
- tests/qgis-projects/tests/tooltip.qgs
- tests/qgis-projects/tests/tooltip.qgs.cfg
Since Lizmap Web Client 3.8 and the introduction of the new HTML template capability,
tooltips configured only with fields (originally the only method) will not work.
This PR convert the given fields into an HTML table
Ticket : #4926
Funded by 3liz
> Tooltip - Fix configured fields not used when HTML template is not defined

- tests/end2end/playwright/requests-api.spec.js
To check URL, it is better to use new URL than to compare string.
> Tests e2e Playwright: enhancing checking Getcapabilities URL in API

- lizmap/modules/admin/templates/project_list_help.tpl
- lizmap/modules/admin/zones/project_list.zone.php
- lizmap/modules/lizmap/lib/App/VersionTools.php
- lizmap/www/assets/js/admin/activate_datatable.js
- tests/units/classes/App/VersionToolsTest.php
add `VersionTools:intVersionToHumanString`  method  to convert int version to human readable string
example : `030506 `means `3.5.6`, 
keep the `intVersionToSortableString` to allow sortable string ( "03.10.XX" > "03.09.YY" but 3.10 < 3.9), so update js to convert "sortable" string to a human string 
Ticket : #5855 
Funded by 3Liz
> Fix version count

- assets/src/components/FeaturesTable.js
When the HTML component downloads data to be used and displayed, if the request is successful, but there is no data (no features returned), a JS error occured, because the table was not created beforehand.
This PR fixes this wrong behaviour
Funded by 3liz
> FeaturesTable - Fix error when the features list is empty

- lizmap/modules/lizmap/classes/lizmapLog.listener.php
When the [webdav module](https://github.com/3liz/lizmap-webdav-module) is enabled, the Login event should be logged with a specific  key (see https://github.com/3liz/lizmap-web-client/pull/5942 ) 
But #5942 didn't work as expected (request object is not instanciated yet ?) 
So the PR use `$_SERVER` vars to find the entrypoint
Funded by 3Liz
> fix : login key for other entrypoint

- lizmap/modules/lizmap/lib/Request/WFSRequest.php
In the context of editing features, Lizmap Web Client backend should access data with WFS getfeature request even if the publisher has not checked them as published in the QGIS project properties. This allows to fill the combo boxes (or multiple checkboxes) based on "value relation" or "relation reference" edit types.
Funded by 3liz
> Editing - Avoid checking valuerelation & relationreference fields as valid WFS typenames

- .github/workflows/docs.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/labeler.yml
- .github/workflows/lint.yml
- .github/workflows/milestone.yml
- .github/workflows/php-stan.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
* Bump ctrf-io/github-test-reporter from 1.0.17 to 1.0.22
* Bump cypress-io/github-action from 6.10.1 to 6.10.2
* Bump actions/setup-python from 5 to 6
* Bump actions/labeler from 5 to 6
* Bump actions/upload-pages-artifact from 3 to 4
* Bump actions/checkout from 4 to 5
* Bump actions/setup-node from 4 to 5
> Bump some Github Actions

- lizmap/modules/lizmap/controllers/service.classic.php
- lizmap/modules/lizmap/lib/App/ControllerTools.php
- lizmap/modules/view/controllers/media.classic.php
- lizmap/modules/view/locales/en_US/default.UTF-8.properties
- tests/end2end/playwright/media.spec.js
When the user is not authenticated and media must be accessed with specific rights, return a `401` instead of a `403` and add the header `WWW-Authenticate`
Funded by Valabre
> Media - Improve HTTP error codes when the user is not authenticated

- assets/src/legacy/switcher-layers-actions.js
- lizmap/modules/lizmap/lib/Project/Project.php
- tests/end2end/playwright/sub-dock-metadata.spec.js
An exporter tool was available in the layer information sub dock up to version 3.8. It has desappear with the ability to disable the export of layer in attribute layer.
To get back this feature, the exporter is available for all layer publshed in WFS if no attribute table config is defined or if export in attribute table is not disabled for any layer in attribute table.
The exporter is disable if at least it has been disabled for one layer in attribute table config and it is not enabled for this layer.
Fixes #5857
> Fix regression: exporter disappear from layer information sub dock
